### ISSUE TITLE
how to change defaultDialog buttonText Colors ?

### ISSUE THREAD

**Issue by j33tmane** [jonataslaw/get#100]
i have flowing dialog:
```
Get.defaultDialog(
        title: 'Do you really want to submit? Press OK to submit.',
        content: Text('On submitting quiz will end and your score will be calculated.',textAlign: TextAlign.center,),
        onCancel: () => print("cancle"),
        textCancel: 'Continue',
        textConfirm: 'Submit',
        buttonColor: Colors.blue,
        onConfirm: () => print("Ok"),
      backgroundColor: Get.theme.accentColor
      );
```
How can i change textCancel & textConfirm color?
I thought is Text Widget type but its String so how can i change  it?
screen shot of screen i m trying to achieve!
![Screenshot_1589458066](https://user-images.githubusercontent.com/20676577/81932592-a8dab900-9609-11ea-95bd-650cec22b583.png)

**Comment by jonataslaw** [comment]
You can simply change the "cancel" widget to the one you want, but I'll add that in the next update.

**Comment by jonataslaw** [comment]
Added
