### ISSUE TITLE
selector like feature in provider

### ISSUE THREAD

**Issue by sparcsaswat** [jonataslaw/get#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

it is a nice package. I like everything as well as your state management solution.

But in some places, we need a feature like a selector which is in the provider package, which helps unnecessary widgets rebuild.  

The basic problem is that when I try to do any change in some controller is to rebuild the whole thing. But as a developer, we should not store a single value in some specific controller. 
So we need that type of feature.

**Comment by jonataslaw** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> it is a nice package. I like everything as well as your state management solution.
> 
> But in some places, we need a feature like a selector which is in the provider package, which helps unnecessary widgets rebuild.
> 
> The basic problem is that when I try to do any change in some controller is to rebuild the whole thing. But as a developer, we should not store a single value in some specific controller.
> So we need that type of feature.

With Get you can select the widget you want to rebuild, and even impose conditions for that, in addition to GetX, released yesterday, not yet documented, change the exact widget that has the variable, and have a super mega blaster minimal reconstruction algorithm, where if you have a widget that uses a variable, another that uses another, and another that uses a get adding the two, and you add a ++ in a variable, it will reconstruct only the two that were affected by the sum, however much have 300 variables that have been 'affected' but have not changed the result.
Anxious to launch GetX, GetBuilder is really good, but GetX is without taking away a revolution in intelligent state management.

**Comment by NiranjanShah** [comment]
When is the release of GetX Planned ?



Regards
Niranjan G Shah

**Comment by jonataslaw** [comment]
I think the answer was not whole, you can use the ID in the traditional Get for a refined state control.

```
GetBuilder (
id: 'list',
```

`update (this, ['list']);`

GetX will be released as soon as it is ready, at the moment it only has Strings, Ints and Double working, I'm trying to make it work with custom classes, Lists and Maps.

**Comment by jonataslaw** [comment]
GetX released
