### ISSUE TITLE
NoSuchMethodError: the getter 'overlay' was called on null

### ISSUE THREAD

**Issue by mmc16** [jonataslaw/get#103]
**Describe the bug**
I am getting this error when I try to call Get.dialog() from a (sort of) back-end class. My app needs some user input to complete a task, but this input is necessary only in case an error occurs. That's why I needed a way to show a dialog, independent of the widget that is on the screen.

**To Reproduce**
Here's the code: 
By the way, this Calendar class is from the device_calendar plugin.

``` dart
Future<String> calendarSelection(List<Calendar> calendars) {
  List<Widget> calendarListWidget = calendars.where((c) => !c.isReadOnly).map((c) {
    return ListTile(
      leading: Radio(
        groupValue: null,
        value: c.id,
        onChanged: (String value) => Get.back(result: value),
      ),
      title: Text(c.name),
    );
  }).toList();
  return Get.dialog(AlertDialog(
    title: Text('select calendar'),
    content: ListView(
      children: calendarListWidget,
    ),
  ),useRootNavigator: true);
}
```

**Expected behavior**
To see the dialog.

**Flutter Version:**
```
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (12 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```

**Get Version:**
```
2.4.0
```

**Describe on which device you found the bug:**
Samsung SM G610M

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
I think you forgot to exchange your MaterialApp for a GetMaterialApp. 

Look at the first steps of the documentation, please.

**Comment by mmc16** [comment]
Yeah, I missed it :sweat_smile:  . Thanks though
