### ISSUE TITLE
Error using onGenerateRoute

### ISSUE THREAD

**Issue by ignaciolopez12** [jonataslaw/get#107]
Hello, in my application I was using onGenerateRoute, and I downloaded the Get package to be able to adapt it. I have an error when I want to implement it. My doubt is if with the Get package it is possible to maintain a RouteGenerator (onGenerateRouter).
The strange thing is that with version 2.0.0 it works, but with the 2.5.0 that I have now it doesn't.

Excuse my speech, I'm from Argentina

Flutter version:   sdk: ">=2.3.0 <3.0.0"
Get Version: 2.5.0
Mobile: Moto G8

**Minimal reproduce code**
> Compiler message:
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/root/root_widget.dart:66:9: Error: Type 'InitialRouteListFactory' not found.
>   final InitialRouteListFactory onGenerateInitialRoutes;
>         ^^^^^^^^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
>   void install() {
>        ^
> ../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
>   void install(OverlayEntry insertionPoint) {
>        ^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/routes/default_route.dart:243:9: Error: No named parameter with the name 'primaryRouteAnimation'.
>         primaryRouteAnimation: animation,
>         ^^^^^^^^^^^^^^^^^^^^^
> ../../../development/flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match.
>   CupertinoFullscreenDialogTransition({
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/get_main.dart:232:7: Error: No named parameter with the name 'routeSettings'.
>       routeSettings: RouteSettings(name: 'dialog'),
>       ^^^^^^^^^^^^^
> ../../../development/flutter/packages/flutter/lib/src/material/dialog.dart:693:11: Context: Found this candidate, but the arguments don't match.
> Future<T> showDialog<T>({
>           ^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/get_main.dart:260:7: Error: No named parameter with the name 'routeSettings'.
>       routeSettings: RouteSettings(name: 'dialog'),
>       ^^^^^^^^^^^^^
> ../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:1621:11: Context: Found this candidate, but the arguments don't match.
> Future<T> showGeneralDialog<T>({
>           ^^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/get_main.dart:349:7: Error: No named parameter with the name 'buttonPadding'.
>       buttonPadding: EdgeInsets.zero,
>       ^^^^^^^^^^^^^
> ../../../development/flutter/packages/flutter/lib/src/material/dialog.dart:208:9: Context: Found this candidate, but the arguments don't match.
>   const AlertDialog({
>         ^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/snackbar/snack_route.dart:289:18: Error: Too few positional arguments: 1 required, 0 given.
>     super.install();
>                  ^
> 
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/root/root_widget.dart:66:9: Error: 'InitialRouteListFactory' isn't a type.
>   final InitialRouteListFactory onGenerateInitialRoutes;
>         ^^^^^^^^^^^^^^^^^^^^^^^
> ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/root/root_widget.dart:205:13: Error: No named parameter with the name 'onGenerateInitialRoutes'.
>             onGenerateInitialRoutes: onGenerateInitialRoutes,
>             ^^^^^^^^^^^^^^^^^^^^^^^
> ../../../development/flutter/packages/flutter/lib/src/material/app.dart:165:9: Context: Found this candidate, but the arguments don't match.
>   const MaterialApp({
>         ^^^^^^^^^^^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/home/ignacio/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.
> > Process 'command '/home/ignacio/development/flutter/bin/flutter'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 9s
> Gradle task assembleDebug failed with exit code 1

**Comment by jonataslaw** [comment]
> Hello, in my application I was using onGenerateRoute, and I downloaded the Get package to be able to adapt it. I have an error when I want to implement it. My doubt is if with the Get package it is possible to maintain a RouteGenerator (onGenerateRouter).
> The strange thing is that with version 2.0.0 it works, but with the 2.5.0 that I have now it doesn't.
> 
> Excuse my speech, I'm from Argentina
> 
> Flutter version: sdk: ">=2.3.0 <3.0.0"
> Get Version: 2.5.0
> Mobile: Moto G8
> 
> **Minimal reproduce code**
> 
> > Compiler message:
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/root/root_widget.dart:66:9: Error: Type 'InitialRouteListFactory' not found.
> > final InitialRouteListFactory onGenerateInitialRoutes;
> > ^^^^^^^^^^^^^^^^^^^^^^^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
> > void install() {
> > ^
> > ../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> > void install(OverlayEntry insertionPoint) {
> > ^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/routes/default_route.dart:243:9: Error: No named parameter with the name 'primaryRouteAnimation'.
> > primaryRouteAnimation: animation,
> > ^^^^^^^^^^^^^^^^^^^^^
> > ../../../development/flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match.
> > CupertinoFullscreenDialogTransition({
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/get_main.dart:232:7: Error: No named parameter with the name 'routeSettings'.
> > routeSettings: RouteSettings(name: 'dialog'),
> > ^^^^^^^^^^^^^
> > ../../../development/flutter/packages/flutter/lib/src/material/dialog.dart:693:11: Context: Found this candidate, but the arguments don't match.
> > Future showDialog({
> > ^^^^^^^^^^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/get_main.dart:260:7: Error: No named parameter with the name 'routeSettings'.
> > routeSettings: RouteSettings(name: 'dialog'),
> > ^^^^^^^^^^^^^
> > ../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:1621:11: Context: Found this candidate, but the arguments don't match.
> > Future showGeneralDialog({
> > ^^^^^^^^^^^^^^^^^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/get_main.dart:349:7: Error: No named parameter with the name 'buttonPadding'.
> > buttonPadding: EdgeInsets.zero,
> > ^^^^^^^^^^^^^
> > ../../../development/flutter/packages/flutter/lib/src/material/dialog.dart:208:9: Context: Found this candidate, but the arguments don't match.
> > const AlertDialog({
> > ^^^^^^^^^^^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/snackbar/snack_route.dart:289:18: Error: Too few positional arguments: 1 required, 0 given.
> > super.install();
> > ^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/root/root_widget.dart:66:9: Error: 'InitialRouteListFactory' isn't a type.
> > final InitialRouteListFactory onGenerateInitialRoutes;
> > ^^^^^^^^^^^^^^^^^^^^^^^
> > ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.0/lib/src/root/root_widget.dart:205:13: Error: No named parameter with the name 'onGenerateInitialRoutes'.
> > onGenerateInitialRoutes: onGenerateInitialRoutes,
> > ^^^^^^^^^^^^^^^^^^^^^^^
> > ../../../development/flutter/packages/flutter/lib/src/material/app.dart:165:9: Context: Found this candidate, but the arguments don't match.
> > const MaterialApp({
> > ^^^^^^^^^^^
> > Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> > build failed.
> > FAILURE: Build failed with an exception.
> > 
> > * Where:
> >   Script '/home/ignacio/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
> > * What went wrong:
> >   Execution failed for task ':app:compileFlutterBuildDebug'.
> > 
> > > Process 'command '/home/ignacio/development/flutter/bin/flutter'' finished with non-zero exit value 1
> > 
> > 
> > 
> > * Try:
> >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > * Get more help at https://help.gradle.org
> > 
> > BUILD FAILED in 9s
> > Gradle task assembleDebug failed with exit code 1

Hi, What version of Flutter are you using?

**Comment by jonataslaw** [comment]
[2.0.10] #
Bump new Flutter version

You are probably using a legacy version.
As of version 2.0.10, Get stable is now compatible with the stable version, which is now 1.17.1, any version prior to that, will give an error.
Use the flutter upgrade to upgrade your Flutter, or stay on the legacy version of Get.
I recommend using namedRoutes instead of onGenerateroutes, it is much easier and simpler, and allows named routes. But you can use onGenerateRoutes if you prefer.

**Comment by ignaciolopez12** [comment]
> [2.0.10] #
> Bump new Flutter version
> 
> You are probably using a legacy version.
> As of version 2.0.10, Get stable is now compatible with the stable version, which is now 1.17.1, any version prior to that, will give an error.
> Use the flutter upgrade to upgrade your Flutter, or stay on the legacy version of Get.
> I recommend using namedRoutes instead of onGenerateroutes, it is much easier and simpler, and allows named routes. But you can use onGenerateRoutes if you prefer.


What version of flutter do I have to upgrade to so there is no error?

**Comment by ignaciolopez12** [comment]
READY, update flutter to its latest version and it works!

**Comment by ignaciolopez12** [comment]
> [2.0.10] #
> Bump new Flutter version
> 
> You are probably using a legacy version.
> As of version 2.0.10, Get stable is now compatible with the stable version, which is now 1.17.1, any version prior to that, will give an error.
> Use the flutter upgrade to upgrade your Flutter, or stay on the legacy version of Get.
> I recommend using namedRoutes instead of onGenerateroutes, it is much easier and simpler, and allows named routes. But you can use onGenerateRoutes if you prefer.


I ask you ... how to go to another Screen replacing it and removing the previous screens from the stack with Get Package?

**Comment by jonataslaw** [comment]
Get.off(Screen())
Get.offNamed('/screen')

**Comment by jonataslaw** [comment]
> READY, update flutter to its latest version and it works!

It was about using the updated package with a legacy version of Flutter. Closing based on this comment

**Comment by warulerahul** [comment]
how can I use the onGenerateRoughte  function in getX

**Comment by warulerahul** [comment]
any example of onGenerateRoughte using GetX @ignaciolopez12 @jonataslaw @jasonlaw @lsm
