### ISSUE TITLE
Wrapping the GetMaterialApp with a GetBuilder can cause memory leaks

### ISSUE THREAD

**Issue by MichaelOttink** [jonataslaw/get#108]
First of all thank you for you help with the stream controller, it works great now! I will stop using a addStream(). 

But upon that fix I noticed I still had a memory leak where the GetBuilders kept piling up. So after some searching I found that if you wrap your `GetMaterialApp()` with a `GetBuilder(`) and in some deeper nested widget you have with any builder and you rebuild the root `GetBuilder()` inside that builder memory starts leaking.

So I do this because I want to set the theme of my app and also rebuild other widgets with preferences. Previously I did this with a ChangeNotifier but after seeing how bad it's performance is I replaced my ChangeNotifier with a `GetBuilder()`. So I'm not really sure if this is something I should ever do but coming from ChangeNotifier it sure is confusing that I cannot do this.

**Describe the bug/ To Reproduce**
If you use this exact code and look at the memory profiler you'll start to see the GetBuilders piling up once you spam click the buttons a few times.

![image](https://user-images.githubusercontent.com/15832303/82112845-45f43980-9751-11ea-8fdf-78fb6a470cfd.png)

```

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([]);

    return GetBuilder<TestPreferencesController>(
      init: TestPreferencesController(),
      builder: (preferencesController) {
        final ThemeData theme = preferencesController.isDarkMode ? DarkTheme.themeData : LightTheme.themeData;
        return ListTileTheme(
          iconColor: theme.iconTheme.color,
          child: GetMaterialApp(
            home: TestWidget1(),
            theme: theme,
            debugShowCheckedModeBanner: false,
          ),
        );
      },
    );
  }
}

class TestWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      child: Text('go to widget 2'),
      onPressed: () => Get.to(TestWidget2()),
    );
  }
}

class TestWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Builder(
      builder: (context) => GetBuilder<TestPreferencesController>( // the controller that get's lost in memory
        builder: (TestPreferencesController controller) => RaisedButton(
          child: Text('go to back'),
          onPressed: () => Get.back(),
        ),
      ),
    );
  }
}

class TestPreferencesController extends GetController {

  bool isDarkMode = false;

}
```

**Note: The Builder wrapping the GetBuilder in TestWidget2 is acutally a StreamBuilder in my app but I used this to demonstate what's happening.**

**Expected behavior**
I expected that I could wrap the GetMaterialApp with a GetBuilder so I could provide my app from a theme without having any kind of memory loss. Or getting an error that it is not permitted to wrap your app with a `GetBuilder()`

Also I would love to know what would be a good way to change my GetMaterialApp's theme with Get and also update the other parts of my app with the same GetBuilder() to provide my app with preferences.

**Flutter Version:**
1.17.1

**Get Version:**
  get: ^2.4.0

**Describe on which device you found the bug:**
Android Emulator

**Comment by jonataslaw** [comment]
This is because you should NEVER wrap your GetMaterialApp in a GetBuilder, and there is no need for it to ever happen. GetMaterialApp must be your rootWidget, and any approach other than that is not good practice using Get, simply because both the rebuilding of the widget tree, as well as the assignment of context, as well as building high-level APIs depend on GetMaterialApp being a widget unchanging.
I know a lot of people are used to Provider's dirty approach of wrapping MaterialApp in a top-level widget, not least because it only works with InheritedWidget, and for him that's normal, but with Get you definitely don't need it.
Want to change the theme?
Use the GetMaterialApp API:
`Get.changeTheme(Theme.dark());`
`Get.changeTheme(Get.isDarkTheme? Theme.Light():Theme.dark());`

You don't have to go back to the Middle Ages and build a parent widget to just change a theme.

**Comment by MichaelOttink** [comment]
Okay lesson learned! Thank you so much for responding. More info about this in the documentation would be great though for future users.

**Comment by jonataslaw** [comment]
> Okay lesson learned! Thank you so much for responding. More info about this in the documentation would be great though for future users.

This would certainly be better, I really wanted to have time to document all Get's features, one day I will still be able to do this, as well as translating the readme into other languages.

**Comment by MichaelOttink** [comment]
Hey I keep getting those extra Get Builders even tho I move my preferences controller inside my GetMaterial App. It's just whenever you use a GetBuilder inside a normal builder / streambuilder this problem happens. It keeps creating builders and keeps them in memory. 

Here is the minimal reproduceable code. I have a super important deadline tommorow for a client and I don't know how I can fix this in time so I'm freaking out a little bit. Am I still doing things the wrong way? 

Also I noticed that the `onInit()` get's called every time a ReBuilder get's build. Shouldn't it just be build whenever the root builder is build? 

I would also be open to discord with you if you have the time. 

```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([]);
    return GetMaterialApp(
      home: TestWidget1(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class TestWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<TestController>(
      init: TestController(),
      builder: (TestController controller) => RaisedButton(
        child: Text('go to widget 2'),
        onPressed: () => Get.to(TestWidget2()),
      ),
    );
  }
}

class TestWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Builder(
      builder: (context) => GetBuilder<TestController>(
        builder: (TestController controller) => RaisedButton(child: Text('go back'), onPressed: () => Get.back()),
      ),
    );
  }
}

class TestController extends GetController {
  @override
  void onInit() {
    super.onInit();
    print('int');
  }
}

```
