### ISSUE TITLE
Error get.dailog with get.back() error

### ISSUE THREAD

**Issue by Raviteja11122** [jonataslaw/get#109]
`Get.back(result: [1, 2, 3])
Get.back(result: 2)
`
`In int case no error`
`if we pass list getting an error`

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
type 'List<int>' is not a subtype of type 'int' of 'result'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#0      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
#1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:2125:15)
#2      Navigator.pop (package:flutter/src/widgets/navigator.dart:1387:34)
#3      GetAlertDialogue.build.<anonymous closure> (package:classify_me/ui/widgets/search_service.dart:42:58)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#ef689
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(326.8, 741.4)
  finalLocalPosition: Offset(27.4, 17.7)
  button: 1
  sent tap down

`Note: No error if we use a separate screen`

**Comment by jonataslaw** [comment]
This is a type error, it has nothing to do with this library. Please correctly type your variable that will receive the result, and if you don't know which type you will receive, or are receiving int and list at the same time, use var or dynamic.
I tested both ways, and both work as expected, result is a dynamic, so there would be no way for him to return a type error, because it literally delivers anything back as a result without type checking.


```dart
 var data = await Get.dialog(AlertDialog(
                title: Text("Test"),
                actions: <Widget>[
                  FlatButton(
                    child: Text("Fechar"),
                    onPressed: () {
                      Get.back(result: [1, 2, 3]);
                    },
                  ),
                ],
              ));
              print(data.toString());
```

```dart
var data = await Get.dialog(AlertDialog(
                title: Text("Test"),
                actions: <Widget>[
                  FlatButton(
                    child: Text("Fechar"),
                    onPressed: () {
                      Get.back(result: 1);
                    },
                  ),
                ],
              ));
              print(data.toString());
```
