### ISSUE TITLE
Errors on building the APK

### ISSUE THREAD

**Issue by mcalooosh** [jonataslaw/get#110]
I am working on Android Studio - Developing a game with Flutter.
I added and wanted to use this library to help with building Dialog without context.

The following is my code:

`    Get.defaultDialog(
        textConfirm: "View highscores",
        textCancel: "Okay",
        onConfirm: () => print("view scores"),
        onCancel: () => print("okay"),
        middleText: "Congratulations on your score submission!");`

Got the following on building:
`
Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/root/root_widget.dart:65:9: Error: Type 'InitialRouteListFactory' not found.
  final InitialRouteListFactory onGenerateInitialRoutes;
        ^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has fewer positional arguments than those of ove
rridden method 'OverlayRoute.install'.
  void install() {
       ^
/C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/routes/default_route.dart:243:9: Error: No named parameter with the name 'primaryRouteAnimation'.
        primaryRouteAnimation: animation,
        ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/get_main.dart:220:7: Error: No named parameter with the name 'routeSettings'.
      routeSettings: RouteSettings(name: 'dialog'),
      ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/dialog.dart:693:11: Context: Found this candidate, but the arguments don't match.
Future<T> showDialog<T>({
          ^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/get_main.dart:248:7: Error: No named parameter with the name 'routeSettings'.
      routeSettings: RouteSettings(name: 'dialog'),
      ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/routes.dart:1621:11: Context: Found this candidate, but the arguments don't match.
Future<T> showGeneralDialog<T>({
          ^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/get_main.dart:345:7: Error: No named parameter with the name 'buttonPadding'.
      buttonPadding: EdgeInsets.zero,
      ^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/material/dialog.dart:208:9: Context: Found this candidate, but the arguments don't match.
  const AlertDialog({
        ^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/snackbar/snack_route.dart:289:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();
                 ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/root/root_widget.dart:65:9: Error: 'InitialRouteListFactory' isn't a type.
  final InitialRouteListFactory onGenerateInitialRoutes;
        ^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/root/root_widget.dart:204:13: Error: No named parameter with the name 'onGenerateInitialRoutes'.
            onGenerateInitialRoutes: onGenerateInitialRoutes,
            ^^^^^^^^^^^^^^^^^^^^^^^
`

**Comment by jonataslaw** [comment]
Update yout 

> I am working on Android Studio - Developing a game with Flutter.
> I added and wanted to use this library to help with building Dialog without context.
> 
> The following is my code:
> 
> ` Get.defaultDialog( textConfirm: "View highscores", textCancel: "Okay", onConfirm: () => print("view scores"), onCancel: () => print("okay"), middleText: "Congratulations on your score submission!");`
> 
> Got the following on building:
> `Compiler message: /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/root/root_widget.dart:65:9: Error: Type 'InitialRouteListFactory' not found. final InitialRouteListFactory onGenerateInitialRoutes; ^^^^^^^^^^^^^^^^^^^^^^^ /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has fewer positional arguments than those of ove rridden method 'OverlayRoute.install'. void install() { ^ /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install'). void install(OverlayEntry insertionPoint) { ^ /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/routes/default_route.dart:243:9: Error: No named parameter with the name 'primaryRouteAnimation'. primaryRouteAnimation: animation, ^^^^^^^^^^^^^^^^^^^^^ /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match. CupertinoFullscreenDialogTransition({ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/get_main.dart:220:7: Error: No named parameter with the name 'routeSettings'. routeSettings: RouteSettings(name: 'dialog'), ^^^^^^^^^^^^^ /C:/flutter/packages/flutter/lib/src/material/dialog.dart:693:11: Context: Found this candidate, but the arguments don't match. Future<T> showDialog<T>({ ^^^^^^^^^^ /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/get_main.dart:248:7: Error: No named parameter with the name 'routeSettings'. routeSettings: RouteSettings(name: 'dialog'), ^^^^^^^^^^^^^ /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:1621:11: Context: Found this candidate, but the arguments don't match. Future<T> showGeneralDialog<T>({ ^^^^^^^^^^^^^^^^^ /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/get_main.dart:345:7: Error: No named parameter with the name 'buttonPadding'. buttonPadding: EdgeInsets.zero, ^^^^^^^^^^^^^ /C:/flutter/packages/flutter/lib/src/material/dialog.dart:208:9: Context: Found this candidate, but the arguments don't match. const AlertDialog({ ^^^^^^^^^^^ /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/snackbar/snack_route.dart:289:18: Error: Too few positional arguments: 1 required, 0 given. super.install(); ^ /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/root/root_widget.dart:65:9: Error: 'InitialRouteListFactory' isn't a type. final InitialRouteListFactory onGenerateInitialRoutes; ^^^^^^^^^^^^^^^^^^^^^^^ /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.2/lib/src/root/root_widget.dart:204:13: Error: No named parameter with the name 'onGenerateInitialRoutes'. onGenerateInitialRoutes: onGenerateInitialRoutes, ^^^^^^^^^^^^^^^^^^^^^^^`

You are using a legacy version of Flutter.
update your Flutter with:
`flutter upgrade`
And all of your packages will work normally.
Using legacy versions is not a good thing, it can bring risks of vulnerabilities (not from Get, but if you used an encryption package for example, it would not be good to use versions where the errors are known).
The latest version of Get compatible with yours must be 2.0.7 (I have no way of knowing this, you should have mentioned flutter version in the issue. But just because of the error structure, I suppose it is version 1.12)
