### ISSUE TITLE
When using Get(RE)Builder inside a normal builder the GetBuilder doesn't get removed

### ISSUE THREAD

**Issue by MichaelOttink** [jonataslaw/get#115]
**Describe the bug**
I commented on my closed post, not sure if you will see it because it's closed so I'll post a new one. But the problem I had yesterday turned out to have nothing to do with the controller wrapping the GetMaterialApp.

Sorry to keep bothering you but I keep getting those extra Get Builders that aren't removed from memory. It's just whenever you use a GetBuilder inside a normal builder / streambuilder this problem happens. It keeps creating builders and keeps them in memory.

Here is the minimal reproducible code. I have a super important deadline tomorrow for a client and I don't know how I can fix this in time so I'm freaking out a little bit. Am I still doing things the wrong way?

Also I noticed that the `onInit()` get's called every time a ReBuilder get's built. Shouldn't it just be called whenever the root builder is built?

I would also be open to hop on discord if you have the time.

**To Reproduce**
If you run this code and click the button a few times and look at the memory profiler you'll see them pile up.

```
void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([]);
    return GetMaterialApp(
      home: TestWidget1(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class TestWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<TestController>(
      init: TestController(),
      builder: (TestController controller) => RaisedButton(
        child: Text('go to widget 2'),
        onPressed: () => Get.to(TestWidget2()),
      ),
    );
  }
}

class TestWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Builder(
      builder: (context) => GetBuilder<TestController>(
        builder: (TestController controller) => RaisedButton(child: Text('go back'), onPressed: () => Get.back()),
      ),
    );
  }
}

class TestController extends GetController {
  @override
  void onInit() {
    super.onInit();
    print('int');
  }
}

```

**Expected behavior**
I expect the GetBuilder to be safe to use in normal builder. And that the root builder is the only one that calls the onInit()

**Screenshots**
Same as previous screenshot
![image](https://user-images.githubusercontent.com/15832303/82152663-277e6300-9863-11ea-9ff4-c79e17a4ecad.png)

**Flutter Version:**
1.17.1

**Get Version:**
  get: ^2.5.5

**Describe on which device you found the bug:**
Android Emulator

**Comment by jonataslaw** [comment]
Hi, I was already looking at this. I believe this was a bug introduced in version 2.5.1, when I started using hashcode to eliminate GetBuilders. I'm making a new change in the GetBuilder to try to get some more performance and ram savings, and I'll fix it.

**Comment by jonataslaw** [comment]
It was definitely a bug introduced by 2.5.1, fix on 2.5.6

**Comment by MichaelOttink** [comment]
Just had a look and it looks like it's fixed! Amazing job man. I'll keep an eye on it tho. Do you want me to post here if I find something related to this issue to this or open a new issue?

**Comment by jonataslaw** [comment]
Whichever you prefer, I receive notification of any comments/issues from the library.

**Comment by MichaelOttink** [comment]
It's holding up perfectly! The `onInit() ` being called only the first build makes more sense too and! Thanks again!
