### ISSUE TITLE
MainController is getting deleted from memory.

### ISSUE THREAD

**Issue by NiranjanShah** [jonataslaw/get#119]
MainController is getting deleted from memory.

MainController is getting initialised in MyApp **home:**,

In the next page few actions of the controller are getting called, however after some time in the Log the "MainController is getting deleted from memory." is received and app crashes when Maincontroller.to.productList is called.

[GET] MainController deleted from memory

class MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return
      GetMaterialApp(
        title: 'Mahavir Mills',
        //theme: CustomTheme.of(context),
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home:
        GetBuilder<MainController> (
          init : MainController(),
          builder: (_) {
            return widget._homeWidget;
          },
        ),

        //home: MaleFemaleSelection(title: 'XYZ Emporium'),
        routes: {
          //pageRoutes.home: (context) => homePage(),
          pageRoutes.contact: (context) => contactPage(),
          pageRoutes.event: (context) => eventPage(),
          pageRoutes.profile: (context) => profilePage(),
          pageRoutes.notification: (context) => notificationPage(),
        },

      );
  }

}

**Comment by NiranjanShah** [comment]
b4 the main controller is deleted, below logs are printed

( 9954): [GOING TO ROUTE] /
I/flutter ( 9954): [GOING TO ROUTE] null
I/flutter ( 9954): [REMOVING ROUTE] /
I/flutter ( 9954): [GET] MainController deleted from memory

**Comment by NiranjanShah** [comment]
kindly guide please, is it valid to initailize the Controller as below
@override
Widget build(BuildContext context) {
return
GetMaterialApp(
title: 'Mahavir Mills',
//theme: CustomTheme.of(context),
theme: ThemeData(
primarySwatch: Colors.blue,
),
**home:
GetBuilder (
init : MainController(),
builder: (_) {
return widget._homeWidget;
},**
),

**Comment by jonataslaw** [comment]
builder: (_) {
return widget._homeWidget; /// Why are you doing this? your passing GetMaterialApp, father from GetBuilder to inside of own Getbuilder.
},


Just an addendum: GetMaterialApp needs to be inside the runApp, it cannot have any parent, at most one StatelessWidget class, without any higher hierarchy widget. This widget that will take care of your entire app, from dependency injections, to the exclusion of controllers, and you doing something like putting it into another hierarchy, will completely mess it up.

**Comment by jonataslaw** [comment]
MainController was initialized on a page that was placed, if you want to keep it in memory, in addition to init: MainController(),
use autoremove: false
