### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by gumbarros** [jonataslaw/get#120]
**Describe the bug**

**To Reproduce**
1. Go to 'main.dart'
2. Import 'package:get/get.dart'
3. Change MaterialApp to GetMaterialApp
4. Run and see the error

**Expected behavior**
The app should run

**Flutter Version:**
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (7 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

**Get Version:**
- 2.5.5

**Describe on which device you found the bug:**
- Galaxy A5 2017 - Lineage OS (Android 8)

**Minimal reproduce code**
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:qrproject/theme/colors.dart';
import 'package:qrproject/views/login/login.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:qrproject/locale/translations.dart';
import 'package:get/get.dart';
import 'package:flutter/cupertino.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await string.init();
  SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
  ));
  runApp(GetMaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: string.supportedLocales(),
      theme: ThemeData(
          primaryColor: Color.fromRGBO(34, 201, 92, 1),
          appBarTheme: AppBarTheme(brightness: Brightness.dark)),
      title: string.text("app_title"),
      home: Login(),
      debugShowCheckedModeBanner: false,
    ));
}
```

**Build error**
Launching lib/main.dart on SM A520F in debug mode...

Compiler message:
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/root/root_widget.dart:65:9: Error: Type 'InitialRouteListFactory' not found.
  final InitialRouteListFactory onGenerateInitialRoutes;
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
  void install() {
       ^
../../../Development/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/routes/default_route.dart:243:9: Error: No named parameter with the name 'primaryRouteAnimation'.
        primaryRouteAnimation: animation,
        ^^^^^^^^^^^^^^^^^^^^^
../../../Development/flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/get_main.dart:220:7: Error: No named parameter with the name 'routeSettings'.
      routeSettings: RouteSettings(name: 'dialog'),
      ^^^^^^^^^^^^^
../../../Development/flutter/packages/flutter/lib/src/material/dialog.dart:693:11: Context: Found this candidate, but the arguments don't match.
Future<T> showDialog<T>({
          ^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/get_main.dart:248:7: Error: No named parameter with the name 'routeSettings'.
      routeSettings: RouteSettings(name: 'dialog'),
      ^^^^^^^^^^^^^
../../../Development/flutter/packages/flutter/lib/src/widgets/routes.dart:1621:11: Context: Found this candidate, but the arguments don't match.
Future<T> showGeneralDialog<T>({
          ^^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/get_main.dart:345:7: Error: No named parameter with the name 'buttonPadding'.
      buttonPadding: EdgeInsets.zero,
      ^^^^^^^^^^^^^
../../../Development/flutter/packages/flutter/lib/src/material/dialog.dart:208:9: Context: Found this candidate, but the arguments don't match.
  const AlertDialog({
        ^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/snackbar/snack_route.dart:289:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();
                 ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/root/root_widget.dart:65:9: Error: 'InitialRouteListFactory' isn't a type.
  final InitialRouteListFactory onGenerateInitialRoutes;
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.5.6/lib/src/root/root_widget.dart:204:13: Error: No named parameter with the name 'onGenerateInitialRoutes'.
            onGenerateInitialRoutes: onGenerateInitialRoutes,
            ^^^^^^^^^^^^^^^^^^^^^^^
../../../Development/flutter/packages/flutter/lib/src/material/app.dart:165:9: Context: Found this candidate, but the arguments don't match.
  const MaterialApp({
        ^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/home/gumbarros/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/gumbarros/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by jonataslaw** [comment]
You are using a legacy version of Flutter.
Use:
flutter upgrade

Or use the latest compatible version (2.0.7).

**Comment by gumbarros** [comment]
It worked! Keep up the great work, congrats from a Brazilian =)
