### ISSUE TITLE
Make GetBuilder smarter / to remove "init"

### ISSUE THREAD

**Issue by d-apps** [jonataslaw/get#123]
Hello Jonny,

I was wondering if is it possible to make GetBuilder smarter when initializating Controllers, I mean, to create a way for it checks if the Controller passed in the GetBuilder (GetBuilder<**Controller**>) was already initialized, if not it initializes, if so it just uses the one initialized before, with this we won't need to use "init:" to initialize the Controller when we'll use for the first time.

Thanks.

**Comment by jonataslaw** [comment]
Vou responder em português porque sei que tu é BR. 
Então, já tem isso, é só usar o Get.lazyPut<Controller>(Controller()); antes, que somente quando o <Controller> for chamado a primeira vez, ele entrará na memória. 
Obviamente, o lugar de colocar esse lazyPut que é a divergência, porque pode ser em literalmente, qualquer lugar antes daquele GetBuilder. Estou pensando se faço algo no GetMaterialApp como "registerDependecies", ou se faço algo similar ao modular, criando um "modulo" e colocando os lazyPuts lá. A empresa que começou apoiar o projeto, usa algo similar aos modulos do modular, mas não posso colocar opensource porque não me autorizaram skaopskpaokspaoksp

**Comment by d-apps** [comment]
> Vou responder em português porque sei que tu é BR.
> Então, já tem isso, é só usar o Get.lazyPut(Controller()); antes, que somente quando o for chamado a primeira vez, ele entrará na memória.
> Obviamente, o lugar de colocar esse lazyPut que é a divergência, porque pode ser em literalmente, qualquer lugar antes daquele GetBuilder. Estou pensando se faço algo no GetMaterialApp como "registerDependecies", ou se faço algo similar ao modular, criando um "modulo" e colocando os lazyPuts lá. A empresa que começou apoiar o projeto, usa algo similar aos modulos do modular, mas não posso colocar opensource porque não me autorizaram skaopskpaokspaoksp

Tinha colocado em inglês caso algum gringo vá fazer a mesma pergunta/pedido.

Usar o Get.lazyPut é diferente kkkk 

O que eu falei é fazer com que ao tipar um GetBuilder<**Controller**>: ele já consiga checar se a instância ja existe na memória, automatizar isso, se não existe instancia desse Controller instanciar, se já existe usa a já instanciada anteriormente, para remover o parametro init do GetBuilder, sem precisar de lembrar que tem que colocar no init se for a primeira vez. Acho que isso seria foda demais se conseguisse esse comportamento no Get.

**Comment by d-apps** [comment]
Não tem algum modo que consiga comparar instancias de Controllers?

**Comment by jonataslaw** [comment]
Você pode usar o operador ==, o instanceOf<> e etc.

Quanto a pergunta, Isso só será possível, quando o Flutter ganhar suporte aos reflections do Dart (se bem que eu acho que encontraria outra saída, os reflections do dart são pesados e tem uma performance ruim). 
No futuro vai ter uma página para colocar os controladores, tipo:

```dart
dependencies(){
 return[
     Dependency(Controller());
     Dependency<Service>(Api());
    ];
}
```

Ou 

```dart
initDependencies(){
Get.lazyPut(Controller());
Get.lazyPut<Service>(Api());
}
```

Service e API é só um exemplo que vai dar pra usar a classe tipada caso queira registrar uma classe concreta com um tipo de uma classe abstrata. 

Pensando bem, gostei do segundo modelo, acho que vou implementar isso

**Comment by d-apps** [comment]
Blz então, não tem saída rsrss, tem que inicializar de alguma forma manualmente então né.

Também gostei dessa segundo modo ai, daria pra criar um registrador múltiplo, exemplo:

```
Get.lazyMultiplePut(
 [
  Controller1(),
  Controller2(),
 ]
);
```
Caso precise de vários já enviaria tudo de uma vez ou apenas aceitar lista de Controllers dentro do lazyPut comum que já existe também...

**Comment by jonataslaw** [comment]
O problema é que tem gente que usa uma classe abstrata pra mockar testes, então elas precisam de um tipo de classe diferente da instancia, tipo:
Get.lazyPut<Service>(Api());
Então não dá pra colocar só a lista e tals. 

Eu sempre vou usar init, e pra mim gerador de código não serve, mas seria fácil também criar algo como:

@RegisterSingleton
class Controller extends RxController{
}

e nesse caso não precisaria de nada disso. Seria o apice da conveniencia, e acabaria com a necessidade do init. Tem um cara que tá fazendo um projeto similar com o Get pra navegação (stacked_services), vou conversar com ele, que talvez ele tenha interesse em fz isso com o stateManager tbm, e ae eu linko o projeto dele no readme do Get normal pra quem quiser usar. 

Enfim, vou fechar isso por agora antes a impossibilidade de usar reflections, se algumas das soluções acimas for lançadas, eu anuncio aqui.

**Comment by stefandevo** [comment]
Sorry to disturb this (using Google Translate :-) >
There is this https://pub.dev/packages/injectable which is generating this stuff for get_it.
I already thought of this for Get too, but one of the reasons you created Get was to not have all these generators in the system (which could take a long time).

**Comment by jonataslaw** [comment]
> Sorry to disturb this (using Google Translate :-) >
> There is this https://pub.dev/packages/injectable which is generating this stuff for get_it.
> I already thought of this for Get too, but one of the reasons you created Get was to not have all these generators in the system (which could take a long time).

I'm now totally out of time to do something like that, but I don't rule out the idea of having something like injectable for Get in the future.

It would be very convenient to use decorations to inject dependency, make the state manager cleaner (removing the values from the variables), and could leave it as an extra package, for those who want to use it, and for whom the project allows it to be used.

**Comment by stefandevo** [comment]
Understand, not really asking for it. From your readme:

> but you need to use a code generator that for large applications, reduces productivity, you will need to drink a lot of coffees until your code is ready again after a Flutter clean

So understand that you don't want to introduce this for Get :-)
