### ISSUE TITLE
The method 'push' was called on null.

### ISSUE THREAD

**Issue by d-apps** [jonataslaw/get#124]
**Describe the bug**
Error when trying to navigate throught screen using Get.to.

**Expected behavior**
Navigate to another screen.

**Flutter Version:**
Flutter (Channel master, 1.18.0-11.1.pre, on Microsoft Windows [versÃ£o 10.0.18363.836], locale pt-BR)
    • Flutter version 1.18.0-11.1.pre at C:\src\flutter
    • Framework revision c2b7342ca4 (13 days ago), 2020-05-06 23:16:03 +0800
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Dih\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\Dih\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (3 available)
    • LG K430    • LGK4305DKZJJKN • android-arm    • Android 6.0 (API 23)
    • Web Server • web-server     • web-javascript • Flutter Tools
    • Chrome     • chrome         • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

**Get Version:**
2.5.6

**Describe on which device you found the bug:**
LGK10 - Android 6.0.

**Minimal reproduce code**
`Get.to(ScreenTwo());`

**Error:**
```
The following NoSuchMethodError was thrown while handling a gesture:
I/flutter (18746): The method 'push' was called on null.
I/flutter (18746): Receiver: null
I/flutter (18746): Tried calling: push<dynamic>(Instance of 'GetRouteBase<dynamic>')
I/flutter (18746): When the exception was thrown, this was the stack:
I/flutter (18746): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (18746): #1      Get.to (package:get/src/get_main.dart:56:41)
I/flutter (18746): #2      ScreenOne.build.<anonymous closure> (package:get_example/main.dart:47:23)
I/flutter (18746): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:772:19)
I/flutter (18746): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:855:36)
I/flutter (18746): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (18746): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
I/flutter (18746): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
I/flutter (18746): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
I/flutter (18746): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
I/flutter (18746): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
I/flutter (18746): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
I/flutter (18746): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
I/flutter (18746): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
I/flutter (18746): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
I/flutter (18746): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter (18746): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (18746): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (18746): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (18746): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (18746): #23     _invoke1 (dart:ui/hooks.dart:291:10)
I/flutter (18746): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:200:5)
I/flutter (18746): (elided 3 frames from dart:async)
I/flutter (18746): Handler: "onTap"
I/flutter (18746): Recognizer:
I/flutter (18746):   TapGestureRecognizer#11ca8
I/flutter (18746): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jonataslaw** [comment]
I think you forgot to add the GetMaterialApp.
add Get before your app stuff.
Before: MaterialApp
Then: GetMaterialApp.

**Comment by jonataslaw** [comment]
Closing this because it is the absence of GetMaterialApp.
If you face problems, do not hesitate to open another issue, and if you have questions about it, you can ask here that I answer.
