### ISSUE TITLE
Uso do variavel.value

### ISSUE THREAD

**Issue by d-apps** [jonataslaw/get#125]
Jonny peço desculpas mas também gostaria de questionar outra coisa, algo relacionado o .value do variável que criamos na classe Controller.

Existe algum possibilidade de conseguirmos acessar o valor direto, sem o uso de .value?

Em vez de usarmos assim:

```
class ScreenOneController extends RxController {

  final counter = 0.obs;

  void increment(){
    counter.value++;
  }
}
```

```
GetX<ScreenOneController>(
                init: ScreenOneController(),
                builder: (_)=> Text(_.counter.value.toString()),
              ),
```

Usarmos assim:

```
class ScreenOneController extends RxController {

  int counter = 0.obs;

  void increment(){
    counter++;
  }
}
```

```
GetX<ScreenOneController>(
                init: ScreenOneController(),
                builder: (_)=> Text(_.counter.toString()),
              ),
```

Realmente tem que extrair o valor interno da variável que criamos? Acha que consegue mudar isso futuramente? Para parecer mais com o MobX nesse caso? Porque sei que o MobX cria a classe grande g.dart, mas pelo menos na classe Controller o dado (pelo menos visivelmente para o dev) ele é diretamente modificada dentro das actions e acessada, sem precisar acessar valores internos.

Na verdade isso é mais um dúvida e possível request. Caso realmente não seja possível porque é assim que o Get consegue trabalhar, tranquilo.

**Comment by jonataslaw** [comment]
Bem, essa é uma das coisas que só dá pra fazer com gerador de código. 
Um simples metodo get e set em um gerador de código resolveria isso

Colocaria na classe .g

get counter => counter.value;

set counter(v)=> counter.value = v;

É ae que entra a questão de principios, eu poderia criar um gerador de código para apenas fazer isso, mas porque eu faria isso se MobX, faz o mesmo? kkk eu sei que é chato colocar value as primeiras vezes, eu também "vim" do MobX, mas com o tempo você acostuma, e principalmente por conta das helps 

você pode usar o .string para obter o value já transformado em String, então nesse mesmo exemplo:

MOBX:

Observer(
       builder: (_)=> Text(controller.counter.toString()),
        ),

GET:

GetX<Controller>(
       builder: (_)=> Text(_.counter.string),
        ),

Faca de dois gumes, nesse caso, não precisou usar o value e impediu que você digitasse o toString(). 

No caso dos sets, acho que até por segurança mesmo, é bom deixar explicitado o value, afinal, você não tá alterando o fluxo, e sim o valor dele. Pra quem tá fazendo o código é uma maravilha jogar um = direto, mas pro dev que vai dar manutenção, entender como uma variável final está sendo alterada... kkkkkk

**Comment by jonataslaw** [comment]
Fechando isso, porque já foi respondido acima e as issues em português vai deixar os gringos loucos haha
