### ISSUE TITLE
Get.offAllNamed lost their arguments.

### ISSUE THREAD

**Issue by ChickenAhn** [jonataslaw/get#127]
**Describe the bug**
Get.toNamed(SomeRouteName, arguments: myArguments)
Get.offNamed(SomeRouteName, arguments: myArguments)
Get.offAllNamed(SomeRouteName, arguments: myArguments)

Get offAllNamed with arguments return always null.
Is it expected behavior?

**To Reproduce**
try to call `offAllNamed` method with my arguments.
Get.offAllNamed(SomeRouteName, arguments: myArguments)

it gives always `null`.

**Expected behavior**
print(Get.arguments);
'myArguments...'

**Screenshots**

**Flutter Version:**
Channel stable, v1.17.1 on Mac OS X 10.15.1

**Get Version:**
get: ^2.5.6

**Describe on which device you found the bug:**
Ios 11 pro simulator

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
Get.routeSettings.arguments is it also null?

**Comment by jonataslaw** [comment]
Fix on 2.5.9 version.

**Comment by ChickenAhn** [comment]
Sorry for late reply and
Thank you :)
