### ISSUE TITLE
Throwing error on Flutter build

### ISSUE THREAD

**Issue by kauaicreative** [jonataslaw/get#13]
Get was working perfectly for both Android and iOS but now my app will no compile. Getting the following error when debugging or flutter build...

I have tested with dev and master flutter branches.

UPDATE:
still have this issue after: 
flutter clean
flutter pub cache repair
Tested with get: ^1.7.3 and get: ^1.7.4
Removed get and app compiles.
The issue started randomly. Not aware of any updates that could have triggered this.

```
Compiler message:
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.7.4/lib/src/snack_route.dart:279:8: 
Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
/C:/dev/flutter/packages/flutter/lib/src/widgets/routes.dart:40:8: Context: This is the overridden method ('install').
  void install() {
       ^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.7.4/lib/src/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           

FAILURE: Build failed with an exception.

* Where:
Script 'C:\dev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 817

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\dev\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      19.5s
Gradle task assembleRelease failed with exit code 1
```

**Comment by jonataslaw** [comment]
> Get was working perfectly for both Android and iOS but now my app will no compile. Getting the following error when debugging or flutter build...
> 
> I have tested with dev and master flutter branches.
> 
> UPDATE:
> still have this issue after:
> flutter clean
> flutter pub cache repair
> Tested with get: ^1.7.3 and get: ^1.7.4
> Removed get and app compiles.
> The issue started randomly. Not aware of any updates that could have triggered this.
> 
> ```
> Compiler message:
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.7.4/lib/src/snack_route.dart:279:8: 
> Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
>   void install(OverlayEntry insertionPoint) {
>        ^
> /C:/dev/flutter/packages/flutter/lib/src/widgets/routes.dart:40:8: Context: This is the overridden method ('install').
>   void install() {
>        ^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.7.4/lib/src/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
>     super.install(insertionPoint);
>                  ^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.                                                           
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\dev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 817
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildRelease'.
> > Process 'command 'C:\dev\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 18s
> Running Gradle task 'assembleRelease'...                                
> Running Gradle task 'assembleRelease'... Done                      19.5s
> Gradle task assembleRelease failed with exit code 1
> ```

Hi, this is the same as #10 

The Flutter Team are doing tests at the master branch with the solution I offered on route reconstruction. Update to the latest version from master, and/or keep the version of the master that does not show errors until They decided whether the overlayRoute will have a GlobalKey off the stage or not.
