### ISSUE TITLE
Get.isSnackbarOpen always return false

### ISSUE THREAD

**Issue by gyksj** [jonataslaw/get#132]
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G103)

get: ^2.5.6

I want to close any previous Snackbar .
like this:
      GlobalContext.scaffoldKey.currentState.removeCurrentSnackBar();

but,Get.isSnackbarOpen always return false

**Comment by jonataslaw** [comment]
Unable to reproduce in 2.5.9.
In previous versions, this could be caused by a delay in Schedulerbinding.instance.
