### ISSUE TITLE
Error passing list in Get.to/GetToNamed

### ISSUE THREAD

**Issue by RodBr** [jonataslaw/get#135]
**Describe the bug**
route_observer previousArgs assumes route arguments are a String and gives ''List<Object>' is not a subtype of type 'String'" when a list is passed.
This happens on the next Get.to after the successful Get.to with a List of args

**To Reproduce**
pass a list[] of arguments in Get.toNamed

**Get Version:**
2.5.9

Provide a minimum reproduction code for the problem
Get.toNamed('PageName', arguments:[arg1,arg2]);

In the generatedRoute file:
var arg1,arg2;
if (settings.arguments is List){
var args = settings.arguments as List;
arg1 = args[0];
arg2 = args[1];
}
return GetRouteBase(settings: settings,
page: 'PageName',
arg1: arg1,
arg2: arg2);

I believe this technique came from FilledStacks, I'll try another way but this may trip up others.

**Comment by jonataslaw** [comment]
Hi, I don't think I understand the problem. Do you want to pass a List as arguments and are you having trouble?
I tried to do that now and I didn't find any exception. Are there any specific list formats that the error is encountered in?
With this example, "first argument" is displayed on the second screen.

```dart
class First extends StatelessWidget {
  const First({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("First"),
      ),
      body: Center(
        child: FlatButton(
            onPressed: () {
              Get.toNamed('/second',
                  arguments: ['First argument', 'Second argument']);
            },
            child: Text("Go to second")),
      ),
    );
  }
}

class Second extends StatelessWidget {
  const Second({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    List args = Get.arguments;
    return Scaffold(
      appBar: AppBar(
        title: Text("second"),
      ),
      body: Center(
        child: Text(args[0]),
      ),
    );
  }
}
```

**Comment by jonataslaw** [comment]
I got it ! PreviousArgs in routeObserve raises an exception.

**Comment by RodBr** [comment]
Yep, thanks it's working again.
