### ISSUE TITLE
Extra properties of context?

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/get#139]
Ideas to have some more context related properties on get?

`bool isLandscape = context.isLandscape; //Instead of: MediaQuery.of(context).orientation == Orientation.landscape`

or `textScaleFactor`

Or just leave the `mediaQuery` exposed? But you already added width, height, etc...

`focusScope` is another property that could be useful to expose directly?

**Comment by jonataslaw** [comment]
Hi, Get.mediaQuery.orientation is avaliable. 
In fact most of the inheritedWidgets that Flutter uses are available.
MediaQuery, and Theme are examples of this.

**Comment by jonataslaw** [comment]
focusScope will probably be added, but I need more testing to see if this can't produce exceptions in some cases.

**Comment by stefandevo** [comment]
Okay. Clear!
