### ISSUE TITLE
[Feature request] Get dialougue with return

### ISSUE THREAD

**Issue by Raviteja11122** [jonataslaw/get#14]
@jonataslaw 
Can I do this same like this using any widget of get.defaultdialogue, get.snackbar or getBar
```
               bool shouldUpdate = await showDialog(
                  context: this.context,
                  child:new AlertDialog(
                    content: new FlatButton(
                      child: new Text("update home"),
                      onPressed: () => Navigator.pop(context, true),
                    ),
                  ),
                );
                setState(() {
                  shouldUpdate ? this._homeData = "updated" : null;
                });
```

**Comment by jonataslaw** [comment]
> @jonataslaw
> Can I do this same like this using any widget of get.defaultdialogue, get.snackbar or getBar
> 
> ```

>                bool shouldUpdate = await showDialog(
>                   context: this.context,
>                   child:new AlertDialog(
>                     content: new FlatButton(
>                       child: new Text("update home"),
>                       onPressed: () => Navigator.pop(context, true),
>                     ),
>                   ),
>                 );
>                 setState(() {
>                   shouldUpdate ? this._homeData = "updated" : null;
>                 });
> ```

Hi, I didn't quite understand what you meant.
Dialogs, snackbars and bottomsheets can get a return as long as you use them appropriately:


```
     var shouldUpdate = await Get.dialog(
            AlertDialog(
              content: new FlatButton(
                child: new Text("update home"),
                onPressed: () => Get.back(result: 'myReturnData'),
              ),
            ),
          );
          print(shouldUpdate);
```
 
Restarted application in 6.470ms.
I/flutter ( 3007): myReturnData

**Comment by jonataslaw** [comment]
If you have any other questions, or errors, don't hesitate to open another issue. Closing this.

**Comment by Raviteja11122** [comment]
OK. thanks 
I tried with GetBar widget it does not return value instead it uses callback for returning.

**Comment by liugangnhm** [comment]
@Raviteja11122 any solution? dialog return always null

**Comment by Raviteja11122** [comment]
@liugangnhm 
use like this Get.back(result: result); in get.dialog you will get result value
