### ISSUE TITLE
The method 'dependOnInheritedWidgetOfExactType' was called on null.

### ISSUE THREAD

**Issue by ElvisHotz** [jonataslaw/get#145]
Ola. recebo essa msg de erro ao chamar Ex: Get.snackbar('title', 'Mensagem').
Eu ja utilizo o get. mas apos a atualização do flutter esta com essa msg. 

Versao do flutter stable V1.17.1
Versao get: ^2.6.3

════════ Exception caught by gesture ═══════════════════════════════════════════
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<_InheritedTheme>()
===============================================
![6b34da77-9de4-4dc2-aad5-0638e7ec42b2](https://user-images.githubusercontent.com/11537876/82936598-381a9180-9f65-11ea-9128-ecf575e17ab0.jpg)

para ter certeza fiz um projeto novo limpo. e o mesmo erro acontece.

**Comment by jonataslaw** [comment]
Adiciona Get antes do materialApp
GetMaterialApp

**Comment by ElvisHotz** [comment]
Opa.. muito obrigado! resolvido.
