### ISSUE TITLE
Strange warning when switching themes

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/get#146]
I have been placing around with `Get` to understand its features.
I was trying the nice switch theme example from the Readme.

```
Get.changeTheme(
                  Get.isDarkMode ? ThemeData.light() : ThemeData.dark());
```

It worked - off course - but in VS Code I see following:

```
flutter: Warning: The support for configuring the foreground color of FloatingActionButtons using ThemeData.accentIconTheme has been deprecated. Please use ThemeData.floatingActionButtonTheme instead. See https://flutter.dev/go/remove-fab-accent-theme-dependency. This feature was deprecated after v1.13.2.
```

Can you confirm you have the same "issue"? Maybe it is Flutter related an not with the package.

I am on stable channel v1.17.1.

**Comment by jonataslaw** [comment]
ThemeData accentIconTheme and ThemeData accentTextTheme of ThemeData will be discontinued, this is just an alert for you to prepare yourself if you are using them.

https://github.com/flutter/flutter/pull/48435
