### ISSUE TITLE
Get.snackbar: not returning to current page if calling navigator.pop while closing animation

### ISSUE THREAD

**Issue by Al-2017** [jonataslaw/get#147]
When displaying snackbar with optional button to close the bar before automatic close and we click button to close while snackbar is animating closing, button click still active causing double pop hence not returning to current page but to previous page.

**To Reproduce**
Please run the sample code, click "goto Page 1" button, click "get snackbar" button, the snackbar will appear on top, wait until it is animating closing and click ok button of the snackbar or any area of snackbar display.

**Expected behavior**
when the snackbar is animating closing, it should disable user interaction with it to prevent unexpected behavior like double pop in case a button to close it provided to user.

**Flutter Version:**
C:\Work\Flutter\fluttertest>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

**Get Version:**
2.7.1

**Describe on which device you found the bug:**
Android emulator

**Minimal reproduce code**
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'flutter test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      // ...
      home: Page0(),
      routes: <String, WidgetBuilder> {
        '/page1'	: (BuildContext context) => Page1(),
      },
    );
  }
}

class Page0 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String title = 'Page 0';

    return Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Column(
          children: <Widget>[
            RaisedButton(
              onPressed: () => navigator.pushNamed('/page1'),
              child: Text('goto Page 1'),
            ),
          ],
        )
    );
  }
}

class Controller extends RxController {
  static Controller get to => Get.find();

  Future<bool> _back() async {
    navigator.pop();
    return true;
  }

  void _showGetSnackBar(String istr, {int iintDurationSeconds = 2}) {
    Get.snackbar(
      'title here...',
      istr,
      duration: Duration(seconds: iintDurationSeconds),
      //animationDuration: Duration(seconds: 0),
      onTap: (GetBar<Object> x) => navigator.pop(),
      mainButton: FlatButton(
        onPressed: () => navigator.pop(),
        child: const Text('Ok'),
      ),
      isDismissible: true,
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final title = 'Page 1';

    return WillPopScope(
      onWillPop: () async => await Controller.to._back(),
      child: Scaffold(
          appBar: AppBar(
            title: Text(title),
          ),
          body:
              Column(
                children: <Widget>[
                  GetX<Controller>(
                    init: Controller(),
                    builder: (Controller c) {
                      return RaisedButton(
                        onPressed: () => c._showGetSnackBar('get snackBar here...'),
                        child: Text('get snackbar'),
                      );
                    },
                  ),
                ],
              )
        ),
    );
  }
}

**Comment by jonataslaw** [comment]
Hi, thanks for reporting this.
However I need more information to understand your problem. Are you reporting that Get.back is closing two pages when a snackbar is opened?
This may not be documented in readMe, just in code, but when there is a page with dialogs, bottomSheets, snackbars, etc., the "closeOverlays = true" option in Get.back() must be enabled to return to the previous page after closing any open overlay.

**Comment by Al-2017** [comment]
Hi Jonny, first of all thanks for very useful package.
I create page 0 and page 1, from page 0 navigator.pushNamed to page 1.
In page 1, there is no dialog, bottomSheets etc. It contains only a push button for displaying snackbar. In the block called by this push button I called a function to display the snackbar with main button to call navigator.pop to give user option to close the snackbar before duration is passed.
If the user click the button before duration passed (snackbar is not started animating close), it work just fine meaning snackbar will close and user go back to page 1.
But if the user click the button while the snackbar animating close (this is where the "double pop" occurs) the user will go back to page 0.
I tried to change the code instead of using navigator.pop, I use Get.back. With closeOverlays = false it produce the same result as using navigator.pop, but with closeOverlays = true, it always goes back to page 0 if user click the button before duration passed or during closing animation.

**Comment by jonataslaw** [comment]
ok, I got it.
Well, I believe this is missing a Get.isSnackbarOpen callback on your back button.
So it works normally.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'flutter test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
// ...
      home: Page0(),
      routes: <String, WidgetBuilder>{
        '/page1': (BuildContext context) => Page1(),
      },
    );
  }
}

class Page0 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    String title = 'Page 0';

    return Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Column(
          children: <Widget>[
            RaisedButton(
              onPressed: () => navigator.pushNamed('/page1'),
              child: Text('goto Page 1'),
            ),
          ],
        ));
  }
}

class Controller extends RxController {
  static Controller get to => Get.find();

  Future _back() async {
    navigator.pop();
    return true;
  }

  void _showGetSnackBar(String istr, {int iintDurationSeconds = 2}) {
    Get.snackbar('title here...', istr,
        duration: Duration(seconds: iintDurationSeconds),
//animationDuration: Duration(seconds: 0),
        onTap: (GetBar x) => navigator.pop(),
        mainButton: FlatButton(
          onPressed: () {
            if (Get.isSnackbarOpen) navigator.pop(); // Secure pop
          },
          child: const Text('Ok'),
        ),
        isDismissible: true,
        snackPosition: SnackPosition.BOTTOM);
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final title = 'Page 1';

    return WillPopScope(
      onWillPop: () async => await Controller.to._back(),
      child: Scaffold(
          appBar: AppBar(
            title: Text(title),
          ),
          body: Column(
            children: <Widget>[
              GetX<Controller>(
                init: Controller(),
                builder: (Controller c) {
                  return RaisedButton(
                    onPressed: () => c._showGetSnackBar('get snackBar here...'),
                    child: Text('get snackbar'),
                  );
                },
              ),
            ],
          )),
    );
  }
}

```

**Comment by Al-2017** [comment]
Works perfectly, thank you
