### ISSUE TITLE
Os links (âncoras) não estão funcionando.

### ISSUE THREAD

**Issue by italofernandez** [jonataslaw/get#148]
Lá no [PubDev](https://pub.dev/packages/get) as âncoras que direcionam para os tópicos, não estão funcionando.

**Comment by jonataslaw** [comment]
> Lá no [PubDev](https://pub.dev/packages/get) as âncoras que direcionam para os tópicos, não estão funcionando.

acho que só funciona no github

**Comment by jonataslaw** [comment]
Fix on 2.10.1
