### ISSUE TITLE
Snackbar back button system handling 

### ISSUE THREAD

**Issue by sumitmatta998** [jonataslaw/get#149]
When snackbar is displayed and user clicks on back button, first click is always on the snackbar. 
I can't go back

A solution should be like whenever I am creating a snackbar I should be able to define whether I system behaviour on back click is dismissable or not

**Comment by jonataslaw** [comment]
Dynamically closing a snackbar is also a feature, if you plan to return to the screen even with an open dialog, bottomsheet or snackbar.
Get.back(closeOverlay = true / false) exists for this.

**Comment by sumitmatta998** [comment]
I have already checked this out, but my problem is with WillPopScope where the back is handled by the system and is used to directly close the app 

```
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class BottomTabContainer extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _BottomTabContainerState();
  }
}

class _BottomTabContainerState extends State<BottomTabContainer> {
  int _currentIndex = 0;
  int lastClick = 0;

  Widget build(BuildContext context) {
    return Scaffold(
      body: WillPopScope(
        onWillPop: () => _backPress(context),
        child: Container(),
      ),
    );
  }

  Future<bool> _backPress(BuildContext context) async {
    if (DateTime.now().millisecondsSinceEpoch - lastClick < 3 * 1000) {
      return true;
    } else {
      lastClick = DateTime.now().millisecondsSinceEpoch;
      await GetBar(message: "Press again to exit", duration: Duration(milliseconds: 1500)).show();
      return false;
    }
  }
}

```

From the get code, It seems like you are adding it in the stack. I am interested in a way where it will not be inserted inside the stack at the first point, rather than handling the back

```
Future<T> show() async {
    _snackRoute = route.showSnack<T>(
      snack: this,
    );
    return await Get.key.currentState.push(_snackRoute);
  }

```

**Comment by jonataslaw** [comment]
WillPopScope is not a problem, you can use Get.Back() instead of returning true.
The snackbar will always be added to the Navigation Stack, because it is a route, as well as dialogs and bottomSheets. Unfortunately, this is how things work, you can manipulate your WillPopScope, so only Get can close something, and take advantage of Get.isSnackbarOpen / closeOverlays to create the specific event you want, the way you want it.
Everything is possible with this library, including what you mentioned you want to do, but if you want to use the scaffold context so that its stack is used to display an Overlay, perhaps the default snackbar is more suitable for this situation, since what you want is just the opposite of what this library tries to provide.

**Comment by sumitmatta998** [comment]
> you can use Get.Back() instead of returning true.

I can't do this as this is I am not getting the callback for back on second click as it handled by Get snack bar itself. 

> The snackbar will always be added to the Navigation Stack  because it is a route, as well as dialogs and bottomSheets. Unfortunately, this is how things work, you can manipulate your WillPopScope, so only Get can close something, and take advantage of Get.isSnackbarOpen / closeOverlays to create the specific event you want, the way you want it.

I checked the code and get to know that this is how it works so I raised it as a feature request as I think multiple people might be needing this feature as the app grows.

> Everything is possible with this library, including what you mentioned you want to do,

this might be possible but there might a lot of code changes. or some checks need to be enabled, with my current knowledge with the library it might not be feasible at this stage, there might be some other way of doing this. and it's better if you can share some example. 

> but if you want to use the scaffold context so that its stack is used to display an Overlay, perhaps the default snackbar is more suitable for this situation, since what you want is just the opposite of what this library tries to provide.


This I will try at my end. and will share the solution once I am done.

**Comment by magnuswikhog** [comment]
I have the exact same problem. I'm displaying a Get Snackbar with the message "Press back again to exit", and if the user presses the back button within 2 seconds I want to close the app. But it seems that the Snackbar consumes the back button event, so I never get a chance to respond to the second back button press. I can't find any way to bypass the Snackbars automatic back button handling.

**Comment by jonataslaw** [comment]
This is a matter of logic in your application.
Get.isSnackbarOpen is enough for you to do anything that involves it.

**Comment by eduardoflorence** [comment]
Hi @magnuswikhog, if you use `Get.back(closeOverlays: true)` does it solve your problem?

**Comment by eduardoflorence** [comment]
@magnuswikhog, try:
```dart
return WillPopScope(
      onWillPop: () async {
        if (!Get.isSnackbarOpen) {
          Get.snackbar(
            'title',
            'message',
            duration: Duration(seconds: 5),
          );
        } else {
          Get.back(closeOverlays: true);
        }
        await Future.delayed(Duration(seconds: 2));  // Insert delay to work
        return Future.value(true);
      },
      child: Scaffold(...
```

**Comment by magnuswikhog** [comment]
@eduardoflorence It "sort of" works - but there's a delay between pressing back the second time and the route being popped. Thanks for trying, but it seems this is impossible using the Get snackbar since it consumes the back button press.
