### ISSUE TITLE
Issue with casting

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/get#150]
I almost always have to create a variable to help typecast when using `.obs` or `Get.arguments`. Are there any workarounds for this.

Example View Class:

``` dart
class PostView extends StatelessWidget {
  /*final Post post;
  PostView({this.post});
*/
  @override
  Widget build(BuildContext context) {
    Post post = Get.arguments;
    User user = Get.find<AuthenticationService>().userController.value;
    return Scaffold(
      backgroundColor: backgroundColor,
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            UIHelper.verticalSpaceLarge(),
            Text(post.title, style: headerStyle),
            Text(
              'by ${user.name}',
              style: TextStyle(fontSize: 9.0),
            ),
            UIHelper.verticalSpaceMedium(),
            Text(post.body),
            Comments(post.id)
          ],
        ),
      ),
    );
  }
}
```

Example Service Class:

```dart
class AuthenticationService {
  Api _api = Get.find<Api>();

  final userController = User.initial().obs;

  Future<bool> login(int userId) async {
    var fetchedUser = await _api.getUserProfile(userId);

    var hasUser = fetchedUser != null;
    if (hasUser) {
      print(fetchedUser.name);
      userController.value = fetchedUser;
    }

    return hasUser;
  }
}
```
Thanks in advance.

**Comment by stefandevo** [comment]
Isn't that the way Flutter works? `arguments` is of type object so when you want typed properties of it you need to cast it to `Post` in your case.
The `value` of .obs is normally the correct type and should not be casted (if it was clear for the compiler what was assigned in the first place).

**Comment by Prn-Ice** [comment]
@stefandevo I get that, just for a bit of context I'm transitioning from using get just as a navigation service to using it for pretty much everything (reactive state, dependency injection) and with the tools, I used previously I didn't have to use as many casts.

Example previous view class:

```dart
class PostView extends StatelessWidget {
  final Post post;
  PostView({this.post});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: backgroundColor,
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            UIHelper.verticalSpaceLarge(),
            Text(post.title, style: headerStyle),
            Text(
              'by ${Provider.of<User>(context).name}',
              style: TextStyle(fontSize: 9.0),
            ),
            UIHelper.verticalSpaceMedium(),
            Text(post.body),
            Comments(post.id)
          ],
        ),
      ),
    );
  }
}
```

Example previous service class:

```dart
class AuthenticationService {
  Api _api = locator<Api>();

  StreamController<User> userController = StreamController<User>();

  Future<bool> login(int userId) async {
    var fetchedUser = await _api.getUserProfile(userId);

    var hasUser = fetchedUser != null;
    if(hasUser) {
      userController.add(fetchedUser);
    }

    return hasUser;
  }
}
```
> The value of .obs is normally the correct type and should not be casted (if it was clear for the compiler what was assigned in the first place)

Not sure what you mean here but the value of my `.obs` is still an object in my view class.
It would be nice if we could add type parameters at least to the `.obs`, similar to `Get.find<T>()`. I could learn to live with Get.arguments.

**Comment by stefandevo** [comment]
Looking at the source in rx_impl.dart I see extensions for types like int, etc. So using the .obs on an int does not need cassting. But perhaps on custom classes it does.
@jonataslaw will have to help here :-)

**Comment by stefandevo** [comment]
Furthermore, you have much higher benefits if you use the RxController or Controller in your widget tree instead of services only.

**Comment by Prn-Ice** [comment]
What added benefits would I get if say my authentication service extended RxController. Also, I do use GetController in my viewmodels.

**Comment by stefandevo** [comment]
No not for the services, but in your widget tree; I see from the snippet above, that you use AuthenticationService directly in the widgetTree. This could be via a Controller (RxController, Controller as base) in such a way to optimize widget re-builds.

**Comment by Prn-Ice** [comment]
True, completely overlooked that, thank you

**Comment by Prn-Ice** [comment]
After moving the variables to the controller, I can't say It's much of an issue now that the controller handles the casting.
