### ISSUE TITLE
i have installed the package imported used snack bar and nothing happen

### ISSUE THREAD

**Issue by atta1234** [jonataslaw/get#153]
the title as enough

**Comment by jemariads** [comment]
please write your snippet of code

**Comment by jonataslaw** [comment]
> the title as enough

Please follow the issue form, inserting the reproduction code, description of the problem, expected behavior, version of Flutter, and version of Get, otherwise it will not be possible to follow up on this issue.

**Comment by atta1234** [comment]
> > the title as enough
> 
> Please follow the issue form, inserting the reproduction code, description of the problem, expected behavior, version of Flutter, and version of Get, otherwise it will not be possible to follow up on this issue.

version is latest flutter and the latest package version,    onprsesd button i m calling the get.snackbar();  but nothing happen even not showing in error

**Comment by jonataslaw** [comment]
Follow the documentation, you skipped the first step which is to exchange MaterialApp for GetMaterialApp

**Comment by alifgiant** [comment]
Hi, i already change MaterialApp to GetMaterialApp but still nothing

**Comment by alifgiant** [comment]
Oh, nevermind. I figure out the problem. I use the Snackbar to show error before closing the screen (Get.back()).

But, directly calling `Get.back()` will directly close the snack bar.

I think, it's good to add a documentation about not calling `Get.back()` directly after snackbar without a delay.

**Comment by Nipodemos** [comment]
`Get.back()` do the same as `Navigator.pop()`. So the default behavior is to close as soon as you call. I can't think on a reason to add a delay to close routes

Why you need to call the function that closes the snackbar right after open it @alifgiant ?

**Comment by alifgiant** [comment]
> `Get.back()` do the same as `Navigator.pop()`

Yes figured that out back then.

Hmm, I don't need a function that close snackbar right after I open it. The use-case is like this, A user is failed in doing something on screen B, then the app shows a snack bar before closing the screen and back to screen A. 

Sure, I can `await` the screen B then check its result before showing snackbar. But if screen B can be opened from multiple other screens, it's a chore to add it in all other places.

My previous suggestion is just add somewhere on the doc "don't call Get.back() right after you show a snackbar".

**Comment by Nipodemos** [comment]
make sense, i'll do a small update in the docs

**Comment by jonataslaw** [comment]
The point is not to warn the user "not to use", not least because many users use Get.back() precisely to close snackbars, and not the screens.
I don't remember if I explicitly put in the documentation that Get.back() closes any overlay, regardless of routes, snackbars, dialogs, etc. If not, maybe it would be a good addition.

**Comment by alifgiant** [comment]
Thanks @Nipodemos @jonataslaw . That one also works. Since, I intuitively think `Get.back` will do back navigation. Explicitly say it will also close overlay is good enough.
