### ISSUE TITLE
Is there a way to preload data before the GetMaterialApp is built?

### ISSUE THREAD

**Issue by MichaelOttink** [jonataslaw/get#156]
I need to need the device Id before the GetMaterialApp is built in order to pass it to the locale changed callback. I would like to load some data before the GetMaterialApp is build. Usually I would just use a Future builder, but from what I understood it's not recommended to wrap the GetMaterialApp with any widget. So how would I do this? I tried to do it in the main function before the mainApp() but this throws an error. Right now I am doing it with a future builder, but I wan't to do it the right way.

It would also be nice to have the option to preload data. Is it possible to get a async function for that in the GetMaterialApp()?

**Comment by Paradoxu** [comment]
Have you tried loading your data on the main by calling an async function and await for it?

**Comment by MichaelOttink** [comment]
> Have you tried loading your data on the main by calling an async function and await for it?

Yeah I got an error that probably has to do with the package I'm using to get the deviceId which is a  package flot the flutter team which cannot be called before the runApp(). So I can only get it after.

**Comment by jonataslaw** [comment]
main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Locale locale = await yourAsyncMethod();
  Get.put<Locale>(locale);


If you need on Other location:
Locale locale = Get.find();

OR
If method isn't async:

GetMaterialApp(
              onInit: () {
               locale =  yourAsyncMethod();
              },

**Comment by Paradoxu** [comment]
> > Have you tried loading your data on the main by calling an async function and await for it?
> 
> Yeah I got an error that probably has to do with the package I'm using a package to get the deviceId. Which is a package flom the flutter team which cannot be called before the runApp(). So I can only get it after. So I have to preload it when the App is being built.

Which package is that? Can you post some of your code? 

I have tried using this [package](https://pub.dev/packages/device_info) and it works well when calling before runApp(), here is an example:

`void main() async {
  // Make sure that the app is initialized before doing anything
  WidgetsFlutterBinding.ensureInitialized();

  DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
  final info = await deviceInfo.androidInfo; // put this in a try/catch 
  print(info.androidId);

  runApp(MyWidget());
}`

**Comment by MichaelOttink** [comment]
Nvm I'm stupid. I missed WidgetsFlutterBinding.ensureInitialized(); last time I tried it. Just tried it and it works. Thanks
