### ISSUE TITLE
Get.offAll() keeps Widgets in memory

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#157]
**Describe the bug**
When I have 2 widgets and I navigate to the second widget and the use Get.offAll() it keeps the widgets in memory. Am I using Get.offAll() correctly? 

My signup page has the country picker pluging and I noticed that it is not getting removed so I had almost 50mb on country flags after a while.

I get the message that the route is being removed but the widgets aren't disposed. Also the controllers closed methods aren't being called.

```
I/flutter (27731): [GOING TO ROUTE] /testwidget1
I/flutter (27731): [REMOVING ROUTE] /testwidget2
I/flutter (27731): [REMOVING ROUTE] /testwidget1
V/AudioManager(27731): querySoundEffectsEnabled...
I/flutter (27731): [GOING TO ROUTE] /testwidget2
V/AudioManager(27731): querySoundEffectsEnabled...
I/flutter (27731): [GOING TO ROUTE] /testwidget1
I/flutter (27731): [REMOVING ROUTE] /testwidget2
I/flutter (27731): [REMOVING ROUTE] /testwidget1
V/AudioManager(27731): querySoundEffectsEnabled...
I/flutter (27731): [GOING TO ROUTE] /testwidget2
V/AudioManager(27731): querySoundEffectsEnabled...
I/flutter (27731): [GOING TO ROUTE] /testwidget1
I/flutter (27731): [REMOVING ROUTE] /testwidget2
I/flutter (27731): [REMOVING ROUTE] /testwidget1
V/AudioManager(27731): querySoundEffectsEnabled...
I/flutter (27731): [GOING TO ROUTE] /testwidget2
V/AudioManager(27731): querySoundEffectsEnabled...
I/flutter (27731): [GOING TO ROUTE] /testwidget1
I/flutter (27731): [REMOVING ROUTE] /testwidget2
I/flutter (27731): [REMOVING ROUTE] /testwidget1
I/flutter (27731): [GOING TO ROUTE] /testwidget2
```

 The non global controllers are also still there in my app.

**To Reproduce**
Copy paste this code and click on the button a few times.

```
void main()  {
  runApp(GetMaterialApp(home: TestWidget1()));
}

class TestWidget1 extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      child: Text('go to widget 2'),
      onPressed: () => Get.to(TestWidget2())
    );
  }

}

class TestWidget2 extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    return GetBuilder<TestController>(
      init: TestController(),
          builder: (TestController testController) => RaisedButton(
        child: Text('off all'),
        onPressed: () => Get.offAll(TestWidget1())
      ),
    );
  }
}

class TestController extends GetController
{
  final int testValue = 5;
}
```

![image](https://user-images.githubusercontent.com/15832303/83195041-e119e580-a139-11ea-9ef3-629a737df583.png)

![image](https://user-images.githubusercontent.com/15832303/83195969-60f47f80-a13b-11ea-97b7-7aa273977e09.png)

According to the documentation I am using it correctly right? So this is a really big problem for me the app is consuming massive amounts of memory because of the flags still in memory.

> _To go to the next screen and cancel all previous routes (useful in shopping carts, polls, and tests)
> 
> Get.offAll(NextScreen());_

**Expected behavior**
I expect that the Get.offAll() goes to the new the widget and removes all the previous pages.

**Flutter Version:**
1.17

**Get Version:**
get: ^2.7.1

**Describe on which device you found the bug:**
Huawei p30 pro

**Comment by jonataslaw** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(GetMaterialApp(home: TestWidget1()));
}

class TestWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
        child: Text('go to widget 2'), onPressed: () => Get.to(TestWidget2()));
  }
}

class TestWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<TestController>(
      init: TestController(),
      builder: (TestController testController) => RaisedButton(
          child: Text('off all'), onPressed: () => Get.offAll(TestWidget1())),
    );
  }
}

class TestController extends GetController {
  final int testValue = 5;
  @override
  void onClose() {
    print("onClose testttt");
    super.onClose();
  }
}

```
log:
```
Restarted application in 2.981ms.
I/flutter (24649): [GOING TO ROUTE] /
I/flutter (24649): [GOING TO ROUTE] /testwidget2
I/flutter (24649): [GOING TO ROUTE] /testwidget1
I/flutter (24649): [REMOVING ROUTE] /testwidget2
I/flutter (24649): [REMOVING ROUTE] /
I/flutter (24649): onClose testttt
I/flutter (24649): [GET] onClose of TestController called
I/flutter (24649): [GET] TestController deleted from memory
I/flutter (24649): [GOING TO ROUTE] /testwidget2
I/flutter (24649): [GOING TO ROUTE] /testwidget1
I/flutter (24649): [REMOVING ROUTE] /testwidget2
I/flutter (24649): [REMOVING ROUTE] /testwidget1
I/flutter (24649): onClose testttt
I/flutter (24649): [GET] onClose of TestController called
I/flutter (24649): [GET] TestController deleted from memory
I/flutter (24649): [GOING TO ROUTE] /testwidget2
I/flutter (24649): [GOING TO ROUTE] /testwidget1
I/flutter (24649): [REMOVING ROUTE] /testwidget2
I/flutter (24649): [REMOVING ROUTE] /testwidget1
I/flutter (24649): onClose testttt
I/flutter (24649): [GET] onClose of TestController called
I/flutter (24649): [GET] TestController deleted from memory
I/flutter (24649): [GOING TO ROUTE] /testwidget2
I/flutter (24649): [GOING TO ROUTE] /testwidget1
I/flutter (24649): [REMOVING ROUTE] /testwidget2
I/flutter (24649): [REMOVING ROUTE] /testwidget1
I/flutter (24649): onClose testttt
I/flutter (24649): [GET] onClose of TestController called
I/flutter (24649): [GET] TestController deleted from memory
I/flutter (24649): [GOING TO ROUTE] /testwidget2
I/flutter (24649): [GOING TO ROUTE] /testwidget1
I/flutter (24649): [REMOVING ROUTE] /testwidget2
I/flutter (24649): [REMOVING ROUTE] /testwidget1
I/flutter (24649): onClose testttt
I/flutter (24649): [GET] onClose of TestController called
I/flutter (24649): [GET] TestController deleted from memory


```

onClose will always be called when a route leaves the stack, in any circumstance, so I recommend a Flutter clean in your project (as shown in the print, with its example it works perfectly), because there is currently no possibility of a Controller being in memory after the widget that started it being removed, in addition to the dispose that is called, there are route callbacks throughout the lib that will do this even if the disposition of a widget fails, so there is no chance of that happening.

As for the widget being in memory (the widget, not the controller), this is a Flutter problem and the pushAndRemoveUntil introduced in 1.17, it also happens with MaterialApp using MaterialPageRoute as well. Anyone using named routes does not face this problem, because pushNamedAndRemoveUntil is normal.
If you are using version 1.17 and up, they force the initial route to be '/' even without named routes, so I imagine that theoretically using this will solve your problem:

`Get.offAllNamed('/');`

This is theory, and if it works well, I might switch from the Get.offAll approach to running Get.offAllNamed('/') under the hood.

**Comment by MichaelOttink** [comment]
It appears to fix the problem. Quite a big bug tho, wonder why they didn't fix it in the latest release that came out today.

**Comment by jonataslaw** [comment]
> It appears to fix the problem. Quite a big bug tho, wonder why they didn't fix it in the latest release that came out today.

They are recreating the Flutter navigator from scratch.
This is not the only bug introduced in 1.17. the Get code has many "seams" to try to soften the effect of most of them. But well, if it worked for you, I'll add it as a default for offAll. I already imagined that this would happen just by reading the commits, but well, with this correction, this will no longer be a problem with Get.

**Comment by MichaelOttink** [comment]
I do have on more problem. The offAll('/'); goes back tot the splash page.

**Comment by MichaelOttink** [comment]
I do have one more problem. The Get.off('/'); goes back to the spalsh page, And I count on drawing that page only once. Somehow if I use Get.off('/'); the contents of the SignupPage and TheHomePage() don't get removed from memory after the Get.off('/');. Any idea why?

```
class TheSplashView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MediaQuery.removePadding(
      context: context,
      removeTop: true,
      removeLeft: true,
      removeRight: true,
      child: Scaffold(
        resizeToAvoidBottomInset: false,
        body: FutureBuilder(
          future: Get.find<Future<void>>(),
          builder: (_, AsyncSnapshot<void> delaySnapshot) {

            if (delaySnapshot.connectionState != ConnectionState.done)
              return _buildSplashTitle(context);

            return GetBuilder<GetFutureController<bool>>(
              init: GetFutureController<bool>(() => Get.find<AuthenticationController>().isLoggedIn()),
              global: false,
              builder: (GetFutureController<bool> authenticationController) {
                if (authenticationController.snapshot.connectionState != ConnectionState.done)
                  return PlatformCircularProgressIndicator();
                if (authenticationController.snapshot.data == false) return TheSignUpView();
                return TheHomeView();
              },
            );

          },
        ),
      ),
    );
  }

  Widget _buildSplashTitle(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final LocalizationService translator = LocalizationService.of(context);
    return Center(
      child: FractionallySizedBox(
        widthFactor: 0.75,
        child: Text(
          translator.translate('splashPageTitle'),
          style: theme.textTheme.bodyText1,
          textAlign: TextAlign.center,
        ),
      ),
    );
  }
}
```

**Comment by MichaelOttink** [comment]
Okay so I have been struggeling with this alot! And I can't seem to get it work.

I have the following routes in my GetMaterialApp

```
      namedRoutes: {
        '/' : GetRoute(page: TheSplashView(), binding: AuthenticationBinding()),
        '/signUp': GetRoute(page: TheSignUpView()),
        '/home': GetRoute(page: TheHomeView(), binding: AuthenticatedServiceBinding()),
      },
```

With the following bindings

```
class AuthenticationBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<AuthenticationController>(() => FirebaseAuthenticationController(onAuthenticated: (state) {
      Get.offAllNamed('/home');
    }, onUnauthenticated: (state) {
      Get.offAllNamed('/signUp');
    }));
  }
}

class AuthenticatedServiceBinding extends Bindings {
  @override
  void dependencies() {
    final AuthenticatedUserModel user = Get.find<AuthenticationController>().user;
    Get.lazyPut<DatabaseService>(() => FirestoreService(user));
    Get.lazyPut<NotificationService>(() => CloudMessagingService(user,
        onMessage: (NotificationModel notification) =>
            Get.dialog(PlatformAlertDialog(notification.title, notification.body))));
    Get.lazyPut<StorageService>(() => FirebaseStorageService(user));
  }
}
```

The authentication controller has the firebase onAuthenticated and onUnauthenticated callback. These will load a page once triggered.

The I have my splash page a the initial route

```
class TheSplashView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Get.find<AuthenticationController>();
    return MediaQuery.removePadding(
      context: context,
      removeTop: true,
      removeLeft: true,
      removeRight: true,
      child: Scaffold(
        resizeToAvoidBottomInset: false,
        body: PlatformCircularProgressIndicator(),
      ),
    );
  }
}
```

it get's the AuthenticationController so it's onInit get's triggered and it will subscribe to the firebase onAuthChanged event

```
  @override
  void onInit() {
    print('init auth');
    _listner =
        _authentication.onAuthStateChanged.listen((FirebaseUser firebaseUser) => _onAuthStateChanged(firebaseUser));
  }
```

And it will call the callbacks based on the event change

```
  Future<void> _onAuthStateChanged(FirebaseUser firebaseUser) async {
    if (firebaseUser != null) {
      protectedUser = await FirestoreService(AuthenticatedUserModel.fromFirebase(firebaseUser)).getUser();
      protectedState = AuthenticationState.authenticated;
    } else {
      protectedUser = null;
      protectedState = AuthenticationState.unauthenticated;
    }
    update(this);

    if (state == AuthenticationState.authenticated) {
      onAuthenticated?.call(state);
    } else {
      onUnauthenticated?.call(state);
    }
  }
```

So I open the app log in and then sign out with firebase signout (the signout page does not disappear from memory). The onAuthChanged will trigger and it will load the signUpPage again and it will duplicate it in memory which causes me to have many mb's of country code flags

![image](https://user-images.githubusercontent.com/15832303/83257538-dfd9ce80-a1b4-11ea-8d1f-d73759b7642d.png)

**Comment by jonataslaw** [comment]
I didn't quite understand your issue, but if there is a problem, for sure the problem is in a Get.find() called at random in the build method. This makes it not be linked with any device, with any route, with anything.

```dart
class TheSplashView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Get.find<AuthenticationController>(); // Don't ever do that
    return MediaQuery.removePadding(
      context: context,
      removeTop: true,
      removeLeft: true,
      removeRight: true,
      child: Scaffold(
        resizeToAvoidBottomInset: false,
        body: PlatformCircularProgressIndicator(),
      ),
    );
  }
}
```

**Comment by jonataslaw** [comment]
Without further information it will not be possible to proceed with this issue.
If you run into problems, don't hesitate to open another one, or reopen it if necessary.

**Comment by michael-ottink** [comment]
Hi my laptop broke down, so was not working on this. I just converted the signup page to a stateless widget and upgraded to the newest get version and I noticed that I got an error. Going to look into that right now.

Quick question tho. When are bindings deleted? I noticed my binding being deleted when my page is being disposed by the ofAllNamed(). So it's not like my binding put's the controller/instance in a global way but it actually binds it to the lifetime of the widget right?

**Comment by michael-ottink** [comment]
I tried removing the future from the splash page entirely and let a controller handle it. So I put() a splash controller that executes a onDone() and that put()'s the authentication controller

```
class SplashController extends GetController {
  Future duration = Future<void>.delayed(Duration(seconds: 2));
  Function onDone;

  SplashController(Function onDone);

  @override
  void onInit() {
    print('splash controller init');
    load();
    super.onInit();
  }

  void load() async {
    print('splash controller loading');
    await duration;
    onDone?.call();
    print('splash controller done loading');
  }
}
```
and

```
  void onSplashLoadDone() {
    Get.put<ConnectionController>(
      ConnectionController(
        onConnected: (result) {
          if (Get.find<AuthenticationController>().state == AuthenticationState.authenticated)
            Get.offAllNamed('/home');
          else
            Get.offAllNamed('/signUp');
        },
        onDisconnected: () {
          Get.offAll(TheDisconnectedView());
        },
      ),
    );
    Get.put<AuthenticationController>(
      FirebaseAuthenticationController(onAuthenticated: (state) {
        Get.offAllNamed('/home');
      }, onUnauthenticated: (state) {
        Get.offAllNamed('/signUp');
      }),
    );
  }
}

```
But it's onInit doesn't get executed. I remember somewhere that you shouldn't put code in a controller's contructor. So call load() in the splash controller?

**Comment by jonataslaw** [comment]
Get.put(Controller(), permanent: true); will work to you.
