### ISSUE TITLE
The getter '_allStates' was called on null. When navigating back to a previously closed view.

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/get#158]
**Describe the bug**

***Actual Problem***
When I navigate to a view, go back and then navigate to the same view again I get
```sh
════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building BaseView<PostModel>:
The getter '_allStates' was called on null.
Receiver: null
Tried calling: _allStates

The relevant error-causing widget was
    BaseView<PostModel> 
lib/…/views/post_view.dart:13
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      _GetBuilderState.initState 
package:get/…/state/get_state.dart:95
#2      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4640
#3      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4476
#4      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
...
════════════════════════════════════════════════════════════════════════════════
```

***Context***
To describe this bug I feel a bit of context is necessary.

My app is a test for a simple MVVM architecture using only the get package.

In my main method, I register all my services and view models using `Get.lazyPut`
Example:
```dart
void setupLocator() {
  Get.lazyPut<AuthenticationService>(()=> AuthenticationService());
  Get.lazyPut<Api>(()=> Api());
  Get.lazyPut<PostsService>(()=> PostsService());

  Get.lazyPut<LoginModel>(()=> LoginModel());
  Get.lazyPut<HomeModel>(()=> HomeModel());
  Get.lazyPut<CommentsModel>(()=> CommentsModel());
  Get.lazyPut<PostModel>(()=> PostModel());
  Get.lazyPut<LikeButtonModel>(()=> LikeButtonModel());
}
```
All my views implement a base view class which has the `Getbuilder`
Example:
```dart
class BaseView<T extends BaseModel> extends StatelessWidget {
  const BaseView({
    Key key,
    this.builder,
  }) : super(key: key);

  final Widget Function(T) builder;

  @override
  Widget build(BuildContext context) {
    return GetBuilder<T>(
      builder: builder,
    );
  }
}

class PostView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BaseView<PostModel>(
      builder: (model) => Scaffold(
        backgroundColor: backgroundColor,
        body: Center(),
      ),
    );
  }
}
```

All my views models implement a base model class which extends  `GetController`
Example:
```dart
class BaseModel extends GetController {
  ViewState _state = ViewState.Idle;

  ViewState get state => _state;

  void setViewState(ViewState viewState) {
    _state = viewState;
    update(this);
  }
}

class LoginModel extends BaseModel {
  final AuthenticationService _authenticationService =
      Get.find<AuthenticationService>();

  String errorMessage;

  Future<bool> login(String userIdText) async {
    setViewState(ViewState.Busy);
    var userId = int.tryParse(userIdText);
    if (userId == null) {
      errorMessage = 'Value entered is not a number';
      setViewState(ViewState.Idle);
      return false;
    }
    var success = await _authenticationService.login(userId);
    setViewState(ViewState.Idle);
    return success;
  }
}
```
My main:
```dart
void main() {
  setupLocator();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      namedRoutes: Router.namedRoutes,
      unknownRoute: Router.errorRoute,
    );
  }
}
```

**Expected behavior**
Navigate to a page go back, and be able to navigate to the page again

**Screenshots**
![Screen record from 2020-05-29 00 00 35](https://user-images.githubusercontent.com/48252841/83203174-c4cd7700-a140-11ea-9171-5d239e1cced2.gif)

**Flutter Version:**
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)

**Get Version:**
get: ^2.7.1

**Comment by jonataslaw** [comment]
Well, initially, I need to explain what's going on:

You pointed out a function that will generate an instance in the future, when Get.find () looks for its type for the first time.
As soon as Get.find () calls it for the first time, the instance is created, and the reference is destroyed.

You navigated to a route that called that controller for the first time, and Get.find () created the instance and destroyed the reference.

You tried to browse again, and you had an error, because the reference no longer exists.

Seeing this problem (as soon as I created this feature), I thought: ok, how can I solve this?

Form 01:
Instead of removing the factory function from memory, leave it there, from the beginning of the application, to the end. If you have already started it on main, it is because you have no intention of discarding it. This is a plausible argument.

Form 02, create an API capable of starting a factory as soon as a route is called, and arrange the same factory as soon as it is used, so the period it will remain in memory would be so fast that even the Dart inspect cannot catch it, and beyond addition, to be able to create a highly performative structure, with literally 0% wasted resources.

Well, the 01 form will still be added as one of the configuration options, because the intention of this lib is to make other people's lives easier.
But how about leveling up and using the bindings API? You can clean these codes from your main, it will be much more beautiful, and especially organized, in addition to using Middleware to inject dependencies for you, separating the responsibilities.


```dart
class Router {
  Map<String, GetRoute> namedRoutes = {
    '/': GetRoute(page: Login(), binding: LoginBindings()),
    '/home': GetRoute(page: Home(), binding: HomeBindings()),
    '/post': GetRoute(page: Post(), binding: PostBindings()),
  };
}

class LoginBindings extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<LoginModel>(() => LoginModel());
    Get.lazyPut<AuthenticationService>(() => AuthenticationService());
    Get.lazyPut<Api>(() => Api());
  }
}

class HomeBindings extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<PostsService>(() => PostsService());
    Get.lazyPut<HomeModel>(() => HomeModel());
    Get.lazyPut<CommentsModel>(() => CommentsModel());
    Get.lazyPut<LikeButtonModel>(() => LikeButtonModel());
  }
}

class PostBindings extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<PostModel>(() => PostModel());
  }
}

```

That way you can have a folder for each "module" of your app, and insert the Binding in each one.

Obviously, I'll give support if you want to put everything on the main too, but using Bindings will be useful when your project is huge and you won't have 70 lines of code just from initializers in your main

**Comment by MichaelOttink** [comment]
A Authentication service usually takes a user tho

**Comment by MichaelOttink** [comment]
Also I noticed that the lazy but doesn't work with the Get.find(), it says you need to use the put() is that correct?

**Comment by MichaelOttink** [comment]
You could also use my GetFutureController

**Comment by Prn-Ice** [comment]
😍️ wow that is so beautiful, such a good implementation and it works, thanks. Sorry to hit and hit again but ill probably be opening another issue immediately after this one.

**Comment by MichaelOttink** [comment]
I tried implementing this but how does it work for the initial widget load in the build method? So I have this splash page and I am loading the signUp page / homePage conditionally. But since it's not a Get.to() do the binding still work? Or am I implementing it the wrong way? 

My problem is that on the first line in my TheHomeView's builder a `Get.find<DatabaseService>()` will throw an error saying that I need to put is first

```
class TheSplashView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MediaQuery.removePadding(
      context: context,
      removeTop: true,
      removeLeft: true,
      removeRight: true,
      child: Scaffold(
        resizeToAvoidBottomInset: false,
        body: GetBuilder<GetFutureController<bool>>(
          init: GetFutureController(() => FirebaseAuthenticationService().isLoggedIn()),
          global: false,
          builder: (GetFutureController<bool> loggedInController) {
            if (loggedInController.snapshot.connectionState != ConnectionState.done ||
                !loggedInController.snapshot.hasData) return PlatformCircularProgressIndicator();

            if (!loggedInController.snapshot.data) return TheSignUpView();
            return TheHomeView();
          },
        ),
      ),
    );
  }
}
```

These are my routes

     ```
 namedRoutes: {
        '/' : GetRoute(page: TheSplashView()),
        '/signUp': GetRoute(page: TheSignUpView()),
        '/home': GetRoute(page: TheHomeView(), binding: AuthenticatedRoute()),
      },
```
And this is my binding

```
class AuthenticatedRoute extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<AuthenticationController>(() => FirebaseAuthenticationController(onAuthenticated: (state) {
      print('onAuthenticated');
      Get.offAllNamed('/home');
    }, onUnauthenticated: (state) {
      print('onUnauthenticated');
      Get.delete<DatabaseService>();
      Get.delete<NotificationService>();
      Get.delete<StorageService>();
      Get.offAllNamed('/signUp');
    }));
    final AuthenticatedUserModel user = Get.find<AuthenticationController>().user;
    Get.lazyPut<DatabaseService>(() => FirestoreService(user));
    Get.lazyPut<NotificationService>(() => CloudMessagingService(user,
        onMessage: (NotificationModel notification) =>
            Get.dialog(PlatformAlertDialog(notification.title, notification.body))));
    Get.lazyPut<StorageService>(() => FirebaseStorageService(user));
  }
}
```

**Comment by Prn-Ice** [comment]
Look at @jonataslaw's example, you have to add the bindings with GetRoute.

**Comment by Prn-Ice** [comment]
Since your splashview depends on the database service, bind it to the splashview instead of the homeview

**Comment by MichaelOttink** [comment]
> Look at @jonataslaw's example, you have to add the bindings with GetRoute.

But it's not my splashview that depends on the database service, it's my HomeView and my SignUpView. Or am I not understanding you correctly?

Also how do I use the Router() class? How do I add it to my GetMaterialApp()? Do I need the Router() or can I just use the normal named routes?

Sorry this is still really confusing to me

**Comment by MichaelOttink** [comment]
if (!loggedInController.snapshot.data) return TheSignUpView();

Is not actually going to any route, it just displays TheSignUpView widget because it's made in a builder. So that's my problem I think

**Comment by MichaelOttink** [comment]
I see what you mean now

```
      namedRoutes: {
        '/' : GetRoute(page: TheSplashView(), binding: AuthenticationBinding()),
        '/signUp': GetRoute(page: TheSignUpView(), binding: AuthenticatedServiceBinding()),
        '/home': GetRoute(page: TheHomeView(), binding: AuthenticatedServiceBinding()),
      },
```

and

```
class AuthenticationBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<AuthenticationController>(() => FirebaseAuthenticationController(onAuthenticated: (state) {
      Get.offAllNamed('/home');
    }, onUnauthenticated: (state) {
      Get.offAllNamed('/signUp');
    }));
  }
}

class AuthenticatedServiceBinding extends Bindings {
  @override
  void dependencies() {
    final AuthenticatedUserModel user = Get.find<AuthenticationController>().user;
    Get.lazyPut<DatabaseService>(() => FirestoreService(user));
    Get.lazyPut<NotificationService>(() => CloudMessagingService(user,
        onMessage: (NotificationModel notification) =>
            Get.dialog(PlatformAlertDialog(notification.title, notification.body))));
    Get.lazyPut<StorageService>(() => FirebaseStorageService(user));
  }
}
```
