### ISSUE TITLE
Cupertino Routes

### ISSUE THREAD

**Issue by ericmartineau** [jonataslaw/get#16]
The built-in cupertino routes match the feel of native ios transitions, including the ability to navigate back with a gesture.  Have you gotten these to work with Get?  I found this in the documentation:

> and if you need custom transitions, use PageRouteBuilder by adding the parameter 'opaque = false' to maintain compatibility with the library.

but this didn't work for me.  I was hoping I could use `CupertinoPageRoute.buildPageTransitions`, but got a NPE:

This is my code:
```
final getRoute = GetRoute(
      settings: settings,
      page: Builder(builder: builder),
      opaque: false,
    );
    return PageRouteBuilder(
      settings: settings,
      pageBuilder: (context, animation, secondary) {
        return builder(context);
      },
      fullscreenDialog: fullscreenDialog,
      opaque: true,
      transitionsBuilder:
          (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
        return CupertinoPageRoute.buildPageTransitions(getRoute, context, animation, secondaryAnimation, child);
      },
    );
```

This is the error I got:

```
final getRoute = GetRoute(
      settings: settings,
      page: Builder(builder: builder),
      opaque: false,
    );
    return PageRouteBuilder(
      settings: settings,
      pageBuilder: (context, animation, secondary) {
        return builder(context);
      },
      fullscreenDialog: fullscreenDialog,
      opaque: false,
      transitionsBuilder:
          (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
        return CupertinoPageRoute.buildPageTransitions(getRoute, context, animation, secondaryAnimation, child);
      },
    );
```

Flutter 1.13.6

**Comment by jonataslaw** [comment]
> The built-in cupertino routes match the feel of native ios transitions, including the ability to navigate back with a gesture. Have you gotten these to work with Get? I found this in the documentation:
> 
> > and if you need custom transitions, use PageRouteBuilder by adding the parameter 'opaque = false' to maintain compatibility with the library.
> 
> but this didn't work for me. I was hoping I could use `CupertinoPageRoute.buildPageTransitions`, but got a NPE:
> 
> This is my code:
> 
> ```
> final getRoute = GetRoute(
>       settings: settings,
>       page: Builder(builder: builder),
>       opaque: false,
>     );
>     return PageRouteBuilder(
>       settings: settings,
>       pageBuilder: (context, animation, secondary) {
>         return builder(context);
>       },
>       fullscreenDialog: fullscreenDialog,
>       opaque: true,
>       transitionsBuilder:
>           (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
>         return CupertinoPageRoute.buildPageTransitions(getRoute, context, animation, secondaryAnimation, child);
>       },
>     );
> ```
> 
> This is the error I got:
> 
> ```
> final getRoute = GetRoute(
>       settings: settings,
>       page: Builder(builder: builder),
>       opaque: false,
>     );
>     return PageRouteBuilder(
>       settings: settings,
>       pageBuilder: (context, animation, secondary) {
>         return builder(context);
>       },
>       fullscreenDialog: fullscreenDialog,
>       opaque: false,
>       transitionsBuilder:
>           (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
>         return CupertinoPageRoute.buildPageTransitions(getRoute, context, animation, secondaryAnimation, child);
>       },
>     );
> ```
> 
> Flutter 1.13.6

If you are going to use PageRouteBuilder, you don't need to use GetRoute.
You will also be able to use Cupertino routes, however you will lose GetRoute's performance optimizations, and pages will likely be rebuilt with each navigation.
For iOS I use Get's native transition effects, and I never needed Cupertino. Is there a problem with the transitions?

```
GetRoute(
            settings: settings,
            page: Home(),
            transition: Transition.rightToLeft);
)
```
Does the code above reproduce any side effects?

**Comment by ericmartineau** [comment]
This ended up working - I didn't use `GetRoute`, but the routes weren't rebuilding on every transition (which was the major reason for looking at other solutions)

```
PageRoute<T> route;
    route = PageRouteBuilder<T>(
      settings: settings,
      pageBuilder: (context, animation, secondary) {
        return builder(context);
      },
      maintainState: maintainState,
      fullscreenDialog: fullscreenDialog,
      opaque: false,
      transitionsBuilder:
          (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
        return CupertinoPageRoute.buildPageTransitions(route, context, animation, secondaryAnimation, child);
      },
    );
```

For me, the transitions were close, but not quite right.  The biggest thing that was missing, though, was the swipe back on iOS - which initiates a "back" navigation.

What other performance optimizations are there besides not triggering rebuilds on every route change?

**Comment by jonataslaw** [comment]
> This ended up working - I didn't use `GetRoute`, but the routes weren't rebuilding on every transition (which was the major reason for looking at other solutions)
> 
> ```
> PageRoute<T> route;
>     route = PageRouteBuilder<T>(
>       settings: settings,
>       pageBuilder: (context, animation, secondary) {
>         return builder(context);
>       },
>       maintainState: maintainState,
>       fullscreenDialog: fullscreenDialog,
>       opaque: false,
>       transitionsBuilder:
>           (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
>         return CupertinoPageRoute.buildPageTransitions(route, context, animation, secondaryAnimation, child);
>       },
>     );
> ```
> 
> For me, the transitions were close, but not quite right. The biggest thing that was missing, though, was the swipe back on iOS - which initiates a "back" navigation.
> 
> What other performance optimizations are there besides not triggering rebuilds on every route change?

In addition to the reconstruction, the other optimizations are related to the opening of dialogs and OverlayRoutes (snackbars). Get also centralizes all GlobalKeys regarding navigation to a single GlobalKey, avoiding memory leaks, and saving RAM.
Thanks for alerting about iOS. Opaque = false must be causing this, since the reconstruction of the back button depends on the update of the Overlay key.
It may be prudent to keep opaque = true for iOS, until Overlay is fixed. There is an approved PR who entered the master that will make Overlay's key off the stage, preventing reconstruction. You can also use CupertinoPageRoute for iOS.

I saw that you forked and typed the code, I was about to do that to make the methods safer. If you want to offer a pull, feel free.

**Comment by jonataslaw** [comment]
> The built-in cupertino routes match the feel of native ios transitions, including the ability to navigate back with a gesture. Have you gotten these to work with Get? I found this in the documentation:
> 
> > and if you need custom transitions, use PageRouteBuilder by adding the parameter 'opaque = false' to maintain compatibility with the library.
> 
> but this didn't work for me. I was hoping I could use `CupertinoPageRoute.buildPageTransitions`, but got a NPE:
> 
> This is my code:
> 
> ```
> final getRoute = GetRoute(
>       settings: settings,
>       page: Builder(builder: builder),
>       opaque: false,
>     );
>     return PageRouteBuilder(
>       settings: settings,
>       pageBuilder: (context, animation, secondary) {
>         return builder(context);
>       },
>       fullscreenDialog: fullscreenDialog,
>       opaque: true,
>       transitionsBuilder:
>           (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
>         return CupertinoPageRoute.buildPageTransitions(getRoute, context, animation, secondaryAnimation, child);
>       },
>     );
> ```
> 
> This is the error I got:
> 
> ```
> final getRoute = GetRoute(
>       settings: settings,
>       page: Builder(builder: builder),
>       opaque: false,
>     );
>     return PageRouteBuilder(
>       settings: settings,
>       pageBuilder: (context, animation, secondary) {
>         return builder(context);
>       },
>       fullscreenDialog: fullscreenDialog,
>       opaque: false,
>       transitionsBuilder:
>           (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
>         return CupertinoPageRoute.buildPageTransitions(getRoute, context, animation, secondaryAnimation, child);
>       },
>     );
> ```
> 
> Flutter 1.13.6

Get 1.11.1 probably solves this.
Use GetCupertino instead of GetRoute for full back to swipe support and native transitions are added automatically on iOS with Get.to ().
I'll soon be abstracting this so that GetRoute is just an abstraction and calling GetRoute or GetCupertino, but in the meantime, you can use GetCupertino on your named routes, or Get.to () on unnamed routes.
