### ISSUE TITLE
Question: Is it possible to force update of an observabe (.obs) value.

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/get#162]
Say for some reason I wanted to use a .obs but did not want to wrap it in a `RxController` and use it in `GetX`, I just wanted to continue using my regular GetController and GetBuilder.

Now later on in the project, I have a value that I want to be observable, and the `update(this)` function was not enough because the observable is used in separate views, `update(this)` only causes the current view to update, a hot reload or other rebuild of some sort is needed for this to work.

How can I make the observable value change for all listeners and trigger rebuild?

**Comment by Prn-Ice** [comment]
I think I can do that:
Currently, all my views use:
```dart
class BaseView<T extends BaseModel> extends StatelessWidget {
  const BaseView({
    Key key,
    this.builder,
  }) : super(key: key);

  final Widget Function(T) builder;

  @override
  Widget build(BuildContext context) {
    return GetBuilder<T>(
      builder: builder,
    );
  }
}
```

And all my viewmodels use:
```dart
class BaseModel extends GetController {
  ViewState _state = ViewState.Idle;

  ViewState get state => _state;

  void setViewState(ViewState viewState) {
    _state = viewState;
    update(this);
  }
}
```

So I'm guessing I just create maybe ObservableBaseView and ObservableBaseModel that use GetX and RxController respectively. Any final thoughts?

**Comment by jonataslaw** [comment]
In 30 seconds of work you can do a Builder together, but I will think if I will insert it in the library, because it will be heavier because it contains a mixin of two classes, and the creators of other state managers are doing anti Get campaign on Twitter and Reddit, that would be giving material to a giant text from them haha.

In case I don't insert it, you can use it immediately using this widget:

```dart
class MixinBuilder<T extends GetController> extends StatelessWidget {
  @required
  final Widget Function(T) builder;
  final bool global;
  final String id;
  final bool autoRemove;
  final void Function(State state) initState, dispose, didChangeDependencies;
  final void Function(GetBuilder oldWidget, State state) didUpdateWidget;
  final T init;
  const MixinBuilder({
    Key key,
    this.init,
    this.global = true,
    this.builder,
    this.autoRemove = true,
    this.initState,
    this.dispose,
    this.id,
    this.didChangeDependencies,
    this.didUpdateWidget,
  })  : assert(builder != null),
        super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetBuilder<T>(
        init: init,
        global: global,
        autoRemove: autoRemove,
        initState: initState,
        dispose: dispose,
        id: id,
        didChangeDependencies: didChangeDependencies,
        didUpdateWidget: didUpdateWidget,
        builder: (controller) => obx(() => builder.call(controller)));
  }
}
```

Use GetController normally, and insert the observable variables into it normally, MixinBuilder will be rebuilt both when update.this is called, and when any variable changes.

**Comment by Prn-Ice** [comment]
Will try this out soon, anti-get haha. Why on earth would the do that.

**Comment by jonataslaw** [comment]
Added on 2.10

**Comment by Prn-Ice** [comment]
Yay!!
