### ISSUE TITLE
Brazilian Portuguese translation is very outdated

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/get#165]
**Describe the bug**
It is so different that seems like it is talking of another package

if you have no problem, i can translate the new docs to portuguese, but i just want to make sure: 
for this i simply need to modify the READMEpt-br? if is only that i can do it no problem

**Comment by Nipodemos** [comment]
oh sure i can do that, but maybe it will take a while since this doc is enormous
I want to ask you something about the translation style
Can i translate names of dummy classes like `nextScreen()` or `Payment()` ? i feel it would be nice  to translate that, but i want your opinion

offtopic: are you brazilian too?

**Comment by jonataslaw** [comment]
Poxa man, que legal, você também é brasileiro? 
Por mim pode traduzir tudo, e eu sei que isso levará tempo, a documentação é gigante, e volta e meia alguém abre uma issue reclamando que a documentação tá faltando coisa (e realmente está). 
Mas é o preço que se paga por uma lib que falta fazer café kk

**Comment by Nipodemos** [comment]
cara eu fui descobrir essa lib num vídeo do filledstacks, e quando eu fui ler a documentação, eu não acreditei! eu tive um problemão com SnackBar não funcionando (acabei desistindo de tentar resolver)
tive problemas com dialogs, e acho super estranho o código do navigator pra mudar de página
aí vem um package e resolve tudo isso e deixa tudo mais simples! 
eu particularmente fiquei impressionado com o `Get.to(SegundaTela())`

sinceramente, muito obrigado por esse package tão completo, vou me esforçar pra traduzir a documentação atual!

**Comment by jonataslaw** [comment]
Que isso man, tamo junto. Objetivo é ajudar a comunidade, e fazer a comunidade brasileira crescer. Obrigado por sua ajuda, é muito bem vinda.

**Comment by cartafelipe** [comment]
Olá pessoal. Conheci agora pela manhã. Vou iniciar os estudos agora(30/05/2020 - 8:22) kkk venho do Redux com MVC e sinceramente acho muito cansativo, mas funciona. Como disse o @Nipodemos o Get.to(SeguntaTela()) só na leitura ficou sensacional. Vou pro código... abração parabéns pela iniciativa @jonataslaw .

**Comment by fabio-santana** [comment]
Passei 15 dias brigando com Navigator e SnackBar, fiz uma POG (Programação Orientada a Gambiarra) que me deixou envergonhado, mas funcionou..... e aí trombo com este package e vejo que não sou o único a sofrer com estes componentes e contextos. Vlw @jonataslaw pelo esforço e dedicação para resolver não só o seu problema, mas o de tantos outros na comunidade. Sucesso!!!!

**Comment by Katekko** [comment]
> cara eu fui descobrir essa lib num vídeo do filledstacks, e quando eu fui ler a documentação, eu não acreditei! eu tive um problemão com SnackBar não funcionando (acabei desistindo de tentar resolver)
> tive problemas com dialogs, e acho super estranho o código do navigator pra mudar de página
> aí vem um package e resolve tudo isso e deixa tudo mais simples!
> eu particularmente fiquei impressionado com o `Get.to(SegundaTela())`
> 
> sinceramente, muito obrigado por esse package tão completo, vou me esforçar pra traduzir a documentação atual!

Se precisar de ajuda, separa a documentação em partes que precisam ser refeita e eu te ajudo! 

Meu discord: Katekko#1429

**Comment by Nipodemos** [comment]
mandei amizade lá, `Alan Duarte#6930`

**Comment by jonataslaw** [comment]
Fechando essa issue, com grande emoção heuaheua 
Obrigado pelo trabalho q vc fez na tradução, isso ia atrasar demais o lançamento da versão atual.
