### ISSUE TITLE
Erro ao tentar inicializar mais de um GetController no construtor/initState do widget

### ISSUE THREAD

**Issue by Luccasoli** [jonataslaw/get#166]
**Describe the bug**
Erro ao tentar inicializar mais de um GetController no construtor/initState do widget

**Erro**
I/flutter ( 3000): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3000): The following NoSuchMethodError was thrown building Listener:
I/flutter ( 3000): The getter '_allStates' was called on null.
I/flutter ( 3000): Receiver: null
I/flutter ( 3000): Tried calling: _allStates
I/flutter ( 3000): The relevant error-causing widget was:
I/flutter ( 3000):   CustomScrollView

**To Reproduce**
Exemplo: [https://github.com/Luccasoli/flutter_ui_implementations/blob/inserting_global_state_management/cinema_app/lib/src/screens/home_screen/home_screen.dart](url)

**Expected behavior**
Que seja possível consumir os dados dos controllers na mesma tela.

**Flutter Version:**
1.17.2

**Get Version:**
2.7.1

**Describe on which device you found the bug:**
Emulador android com Sdk 22

**Minimal reproduce code**
`Get.lazyPut<TrendingMoviesController>(() => TrendingMoviesController());
    Get.lazyPut<NowPlayingMoviesList>(() => NowPlayingMoviesList());`

E aproveitando, podia me explicar qual a diferença entre put e o lazyPut? Na tentantiva e erro associei que eu devo usar o lazyPut quando eu faço uma chamada assíncrona no onInit do GetController, é isso mesmo?

Agradeço desde já!

**Comment by jonataslaw** [comment]
Qual o código de erro?

A diferença crucial entre put e lazyput é que o put insere o Controlador imediatamente na memória. LazyPut só vai inserir o Controlador na memória quando alguém precisar dele.

**Comment by Luccasoli** [comment]
@jonataslaw foi mal, nem vi que esqueci de colocar o erro rs, editei a issue adicionando o erro

**Comment by jonataslaw** [comment]
Faz uma pasta de bindings man, acho que fica muito mais organizado e vai impedir erros no teu código. 

Na se na rota X tu vai abrir X controladores, tu coloca lá no teu GetRoute: binding: ClasseXBindings()

ae tu cria uma classe só pra inicializar seus controllers:

class ClasseXBindings implements Bindings{

o seu IDE vai dizer que tu precisa implementar uma função registerDependencies, e tu clica na lampada e dá ok, e coloca os controladores daquela rota dentro. 

Assim vai evitar erros, e ainda vai dar autodispose em todos controladores quando eles não estiverem sendo usados, e se precisar deles de novo, o Get injeta ele de novo.

**Comment by Luccasoli** [comment]
Pronto, então acho que vou fazer isso mesmo, na documentação não vi exemplo do bindings, mas tinha visto nessa issue #116 o teu exemplo.

Mas tentando entender esse problema, fiz esse exemplo em que ocorre o mesmo erro, e baseado na explicação do lazyPut que tu falou aqui, parece que to usando de forma errada mesmo, tu pode corrigir esse código?

`
class Controller1 extends GetController {
  int _value = 0;

  set value(newValue) {
    _value = newValue;
  }

  int get value => _value;
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    Get.lazyPut(() => Controller1());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            GetBuilder<Controller1>(
              builder: (_) => Text(
                _.value.toString(),
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
          ],
        ),
      ),
    );
  }
}`

**Comment by jonataslaw** [comment]
Nesse exemplo tu deveria ter tipado o Get.lazyPut:

Get.lazyPut<Controller1>(() => Controller1());

Eu ainda não testei inicialização de controllers no initState, porque sou contra isso, na verdade não gosto nem da ideia de StatefulWidget desnecessário mas se o build for chamado antes do put for concluído, vai apresentar esse erro. 

Tu poderia por exemplo, mudar esse StatefulWidget pra StatelessWidget, que é mais leve, e simplesmente usar a propriedade init do GetBuilder pra inicializar seu controller:

```dart
class Controller1 extends GetController {
  int value = 0;
}

class MyHomePage extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("test"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            GetBuilder<Controller1>(
              init: Controller1(), // assim
              builder: (_) => Text(
                _.value.toString(),
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

Eu sei que quase todo mundo faz isso, um monte de youtuber faz isso, o pessoal que é mais experiente faz isso, e faz todo mundo achar que tá fazendo uma boa prática, mas isso é justamente o contrário, segundo a documentação do Dart você NÃO deve usar get e setter para expor uma instancia simples de um objeto.
https://dart-lang.github.io/linter/lints/unnecessary_getters_setters.html

**Comment by Luccasoli** [comment]
Valeu pelo toque de tornar privado um atributo sem necessidade!

Pra resolver nesse exemplo bastou acrescentar a tipagem mesmo, e no código que estou usando mesmo, eu apaguei e fiz de novo o controller pra fazer funcionar kkk (devo ter colocado alguma classe errada ao invés de uma GetController, não sei), Valeu!!

Mas surgiu um novo problema, estou usando um CustomScrollView, e quando um sliver desse scroll que consome um GetBuilder some da tela, isso é mostrado no debug console:
```
I/flutter ( 5041): [GET] onClose of TrendingMoviesController called
I/flutter ( 5041): [GET] TrendingMoviesController deleted from memory
```

ok, mas quando "dou um scroll" de volta onde estava esse sliver, esse erro ocorre: (se ficar mais organizado e caso isso seja algum problema mesmo, posso abrir outra issue)
```
The getter '_allStates' was called on null.
Receiver: null
Tried calling: _allStates
```

ps: estou convertendo o código que estou fazendo pra gerencia do Get gradualmente, aí por isso que ainda está usando esses stateful widgets :s

**Comment by jonataslaw** [comment]
Se o item não for global, tu usa:
global: false
Se o item for global (o mesmo pra todos do listview)
autoremove = false

**Comment by Luccasoli** [comment]
Não consegui, mas depois consegui de outro jeito kk

não entendi bem essa sua última resposta, deu pra entender o uso do autoremove no exemplo que você colocou na documentação, mas mesmo com autoRemove = false (não achei onde colocar o adoptID, mas tentei com o id tb), e com o global = false tb não funcionou.

ps: fiz um último teste, e funcionou quando movi GetBuilder de um filho do SliverChildListDelegate pra se tornar pai de todo o SliverList (vai acabar gerando re-build desnecessários de poucos widgets simples)

Só uma última pergunta, pra consumir mais de um GetBuilder, só é possível se eu aninhar um GetBuilder dentro de outro né?

tipo assim: 
```dart
                            GetBuilder<GenresMoviesController>(
                              builder: (genres) =>
                                  GetBuilder<NowPlayingMoviesController>(
                                builder: (_) => SliverGrid(
                                  delegate: SliverChildBuilderDelegate(
                                    (BuildContext context, int index) {
                                      return RecentMovieItemWidget(
                                        movie: _.items[index],
                                        genresList: genres.items,
                                      );
                                    },
                                    childCount: _.items.length,
                                  ),
``

**Comment by jonataslaw** [comment]
Sim, sem problemas

**Comment by jonataslaw** [comment]
adoptId era muito feito, eu removi pra relançar na versão que vou subir agora como "assignID"

**Comment by Nipodemos** [comment]
caso vc já tenha inicializado esse controller em alguma outra rota ou nessa mesma, vc sempre pode usar o Get.find() para pegar um controller

vc pode por exemplo pegar o NowPlaying e fazer algo assim (talvez):
```dart
GetBuilder<GenresMoviesController>(
  builder: (genres) => SliverGrid(
    delegate: SliverChildBuilderDelegate(
      (BuildContext context, int index) {
        NowPlayingMoviesController nowPlayingMoviesController = Get.find();
        return RecentMovieItemWidget(
          movie: nowPlayingMoviesController.items[index],
          genresList: genres.items,
        );
      },
    )
    childCount: _.items.length,
  ),
)
```

**Comment by Luccasoli** [comment]
> caso vc já tenha inicializado esse controller em alguma outra rota ou nessa mesma, vc sempre pode usar o Get.find() para pegar um controller
> 
> vc pode por exemplo pegar o NowPlaying e fazer algo assim (talvez):
> 
> ```dart
> GetBuilder<GenresMoviesController>(
>   builder: (genres) => SliverGrid(
>     delegate: SliverChildBuilderDelegate(
>       (BuildContext context, int index) {
>         NowPlayingMoviesController nowPlayingMoviesController = Get.find();
>         return RecentMovieItemWidget(
>           movie: nowPlayingMoviesController.items[index],
>           genresList: genres.items,
>         );
>       },
>     )
>     childCount: _.items.length,
>   ),
> )
> ```

Ss, só que aí eu não ia conseguir "notificar" esse widget quando eu atualizasse o estado do NowPlayingMoviesController, aí acaba sendo melhor usar o GetBuilder mesmo, mas valeu por lembrar que dá pra consumir o controller dessa forma tb! :D

**Comment by Luccasoli** [comment]
Valeu pela ajuda! @jonataslaw

**Comment by jonataslaw** [comment]
Legal da nova versão é que não vai precisar tipar nada, só usar um obs(()=> antes de qualquer widget, e usar qualquer controlador dentro do widget, desde que a variável tenha um .obs no final. 
Listas também tá uma delicia de trabalhar, tudo reativo, inclusive os itens de cada lista, a lista também não precisa do "value", tá uma coisa de louco. Vou mandar pra pub daqui a pouco. Dificil vai ser documentar tudo depois, mas tá tão legal que acho que vou mudar de 2.8 pra 2.10 logo kkk

**Comment by Nipodemos** [comment]
louco pra ver essas novidades :D 
desse jeito não vou nem usar o GetBuilder, já vou pro GetX de uma vez
