### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by angelhdz** [jonataslaw/get#167]
### Some features that would be interesting to include in Get and make it more powerful:

- Local storage like Get.load() and Get.save() or Get.store.load() and Get.store.save() ?
- Easy painting of widgets with the CustomPainter like calling Get.painter() to create a CustomPainter widget subclass, and then calling Get.paint( new Paint() ) to paint? Or passing a paint controller to the Get.painter() as named parameter, and then calling paint on the controller?
- Creating animations easily calling Get.animate() 
- Clipboard management Get.clipboard.read() and Get.clipboard.write().
- Access to keyboard and mouse/touch events like Get.on.key.down() or Get.on.tap() or maybe:
```
Get.on(
tap: () {
},
keyDown: (key) {

}
)
```

Cheers! Be safe.

**Comment by jonataslaw** [comment]
Dude, I think you don't want me to have more social life hahaha.
Well, some resources are really interesting, but there are definitely no human resources to do that.
In addition, most of them (as local storage) would transform a package (which is what Get is today) into a plugin (which would have to have code specific to each platform), and I would have to write code specific to android, ios, desktop and web.
I liked your idea, and thanks for the suggestions, but that would only be possible with the support of a maintainer, or with a large team of supporters. This is impossible for now, but thanks for the suggestions.

**Comment by angelhdz** [comment]
> Dude, I think you don't want me to have more social life hahaha.
> Well, some resources are really interesting, but there are definitely no human resources to do that.
> In addition, most of them (as local storage) would transform a package (which is what Get is today) into a plugin (which would have to have code specific to each platform), and I would have to write code specific to android, ios, desktop and web.
> I liked your idea, and thanks for the suggestions, but that would only be possible with the support of a maintainer, or with a large team of supporters. This is impossible for now, but thanks for the suggestions.

Ha ha ha good one.  😂
