### ISSUE TITLE
Get.snackBar error

### ISSUE THREAD

**Issue by bobosette** [jonataslaw/get#168]
Hi everybody. I'm trying to use get to open a snackbar inside an onTap from GestureDetector.
When the user top on the widget if there is connection they will be redirected to a play store page, but if there isn't connection i would like to show a snackbar with a message.
Whenever i try i get this error: 

`NoSuchMethodError (NoSuchMethodError: The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<_InheritedTheme>())`

this is the GestureDetector code: 

`
Container(
                      
                      width: SizeConfig.blockSizeHorizontal * 80,
                      height: SizeConfig.blockSizeVertical * 10,
                      child: GestureDetector(
                        child: Image.asset( language ?
                          Italian.LOGOPATH : English.LOGOPATH,
                          fit: BoxFit.contain,
                        ),
                        onTap: () async {
                          bool result =
                              await DataConnectionChecker().hasConnection;
                         
                          if (result) {
                            if (Platform.isIOS) {
                              _launchCaller(APPSTORE);
                            } else {
                              _launchCaller(PLAYSTORE);
                            }
                          } else {
                            Get.snackbar('Connection', 'No connection');
                          }
                        },
                      ))

`
This widget is inside a Column > inside a Container > inside a Scaffold > inside a StatefullWidget.
It seems like the package can't take the context or the state I don't know.

Please someone can help me??

Thank you

**Comment by jonataslaw** [comment]
Read the docs. 
You need change your MaterialApp to GetMaterialApp.

**Comment by bobosette** [comment]
Oh sorry, I didn't read that. Thank you very much

Il giorno dom 31 mag 2020 alle ore 22:49 Jonny Borges <
notifications@github.com> ha scritto:
