### ISSUE TITLE
Bad state: No element lançada quando tento criar uma lista vazia

### ISSUE THREAD

**Issue by Denilson-source** [jonataslaw/get#169]
Quando crio uma lista vazia  é lançado Bad state: No element. 

> class NumberStore extends RxController {
  final list = List<int>().obs;
}

a exception é lançada quando instancio a classe no Get.put()

When the exception was thrown, this was the stack:
I/flutter (18819): #0      List.last (dart:core-patch/growable_array.dart:231:5)
I/flutter (18819): #1      ListX.addAll (package:get/src/rx/rx_impl.dart:178:46)
I/flutter (18819): #2      ListX.assignAll (package:get/src/rx/rx_impl.dart:258:5)
I/flutter (18819): #3      ListExtension.obs (package:get/src/rx/rx_impl.dart:594:28)
I/flutter (18819): #4      new NumberStore (package:get_test/store/number_store.dart:9:23)
I/flutter (18819): #5      HomeBinding.dependencies (package:get_test/home_binding.dart:12:13)

**Comment by jonataslaw** [comment]
> Quando crio uma lista vazia é lançado Bad state: No element.
> 
> > class NumberStore extends RxController {
> > final list = List().obs;
> > }
> 
> a exception é lançada quando instancio a classe no Get.put()
> 
> When the exception was thrown, this was the stack:
> I/flutter (18819): #0 List.last (dart:core-patch/growable_array.dart:231:5)
> I/flutter (18819): #1 ListX.addAll (package:get/src/rx/rx_impl.dart:178:46)
> I/flutter (18819): #2 ListX.assignAll (package:get/src/rx/rx_impl.dart:258:5)
> I/flutter (18819): #3 ListExtension.obs (package:get/src/rx/rx_impl.dart:594:28)
> I/flutter (18819): #4 new NumberStore (package:get_test/store/number_store.dart:9:23)
> I/flutter (18819): #5 HomeBinding.dependencies (package:get_test/home_binding.dart:12:13)

Hi, this should be fix on 1.10.1

**Comment by jonataslaw** [comment]
Ah, você é brasileiro, o costume de responder issue inglês, eu nem vi que tava em português a issue kkk
Usa a última versão men, isso tava dando falha nos testes e já foi corrigido.

**Comment by Denilson-source** [comment]
to usando a 2.10.0

**Comment by jonataslaw** [comment]
> to usando a 2.10.0

Usa a 2.10.1
Se passou nos testes, deve tá resolvido

**Comment by Denilson-source** [comment]
Funcinou, vlw pelo atendimento a essa hr kkk
