### ISSUE TITLE
I can't find restartApp

### ISSUE THREAD

**Issue by hahai96** [jonataslaw/get#171]
I could not find the restartApp method when I upgraded to version 2.10.0, then I dropped to 2.7.1, it also didn't appear. Did you delete it?

In pubspec.yaml
get: ^2.7.1

but in pubspec.lock

get:
    dependency: "direct main"
    description:
      name: get
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.10.1"

**Comment by jonataslaw** [comment]
This API has a very low usage level, and I’m still going to decide whether to keep it, but I think you can try:

```dart
    Get().getController.restartApp();
```

**Comment by monnguyen2512** [comment]
I think you should keep it. thanks

**Comment by apoleo88** [comment]
I added the Get package only because I was curious about this function, so I hope you are going to keep it.
But anyway it seems I can't make it work:

When `Get().getController.restartApp()` is called, the only reaction I get is the printed message `restart chamado`.

**Comment by transitguide** [comment]
i commented this in another issue as well, this command simply refreshes the current screen. NOT the entire app as expected.

**Comment by apoleo88** [comment]
I would suggest then to change the name, is quite misleading.
