### ISSUE TITLE
Obx

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/get#173]
Can you update the readme with sample on how to use Obx widget? And how it relates to GetX? 
I see you do not have to wrap it in the GetX builder, but then you need to use it together with Bindings then to initialize your controller?
Thx

**Comment by fabio-santana** [comment]
Aproveitando a solicitação anterior, será que teria como você usar como exemplo uma tela simples de login, fazendo autenticação com api/REst e o uso do CircularProgressIndicator() (Simulando a espera da resposta da api com Future.delayed.. rsrsr). Quem sabe como próximo vídeo do seu canal... Obrigado.

**Comment by Nipodemos** [comment]
@fabio-santana he did a app that consumed an API and uses `CircularProgressIndicator`, he it is: [Gestão de estados DESCOMPLICADA com Flutter aplicado à comunicação API Rest](https://www.youtube.com/watch?v=3qjebK6kwSM)

@stefandevo to be honest i want to know this one too, the documentation suggests it will find the controller automatically, but is better to make sure

**Comment by jonataslaw** [comment]
Added on lastest update
