### ISSUE TITLE
Workers question

### ISSUE THREAD

**Issue by Denilson-source** [jonataslaw/get#175]
Tem alguma forma de dar dispose em um worker?

**Comment by jonataslaw** [comment]
Porque você precisaria dar dispose? Eles não ficam na memória igual as reactions do MobX

**Comment by Denilson-source** [comment]
Eu tenho um conjunto de objetos que ficam observando a localizaçao do dispositivo, mas so quando a pagina deles esta sendo exibida, assim que eu navego pra outra pagina nao é mais necessario observar essa posiçao. eu fiz um teste e vi que quando eu navego pra outra pagina o worker continua escutando mudanças, talvez eu tenha feito algo errado, qual seria o ciclo de vida do worker?

**Comment by jonataslaw** [comment]
> Eu tenho um conjunto de objetos que ficam observando a localizaçao do dispositivo, mas so quando a pagina deles esta sendo exibida, assim que eu navego pra outra pagina nao é mais necessario observar essa posiçao. eu fiz um teste e vi que quando eu navego pra outra pagina o worker continua escutando mudanças, talvez eu tenha feito algo errado, qual seria o ciclo de vida do worker?

Se tu iniciou ele no onInit, ele morre no onClose.
Talvez eu insira um "condition" nele, pra ficar mais fácil, mas como o segundo callback é uma função, tu pode fazer o seguinte:

ever(variable, callback);

callback(){
  if(Get.currentRoute == 'home'){
  // fazerAlgumaCoisa
  }
}

**Comment by Denilson-source** [comment]
ah, saquei, eu tinha iniciado no construtor, talvez seja por isso, vlw
