### ISSUE TITLE
Why we need obx ?

### ISSUE THREAD

**Issue by jemariads** [jonataslaw/get#176]
Base on your example
```
class Home extends StatelessWidget {
  final count = 0.obs;
  @override
  Widget build(context) => Scaffold(
        appBar: AppBar(title: Text("Get change you life")),
        floatingActionButton:
            FloatingActionButton(onPressed: () => count.value++),
        body: Center(child: Obx(() => Text(count.string))),
      );
}
```
Why we need obx if we can make it just use GetX?
```
class Home extends StatelessWidget {
  final count = 0.obs;
  @override
  Widget build(context) => Scaffold(
        appBar: AppBar(title: Text("Get change you life")),
        floatingActionButton:
            FloatingActionButton(onPressed: () => count.value++),
        body: Center(child: GetX(builder: (_) => Text(count.string)),
      );
}
```

**Comment by Nipodemos** [comment]
what i've noticed is if you are using bindings, then you can use Obx since it does not require to specify the controller
looks like GetX is necessary to specify type (`GetX<Controller>()`)

**Comment by jemariads** [comment]
I just get the answer from changelog
```for better RAM consumption, prefer widgets in that order: Obx => GetX => GetBuilder => MixinBuilder. Obx is the lightest of all, and MixinBuilder is a mix of the other 3, whenever possible, use the specific widget.```
