### ISSUE TITLE
Get.put / Get.find does not work properly

### ISSUE THREAD

**Issue by zl910627** [jonataslaw/get#177]
Get version : 2.10.2

![image](https://user-images.githubusercontent.com/53897531/83608844-fa92b580-a5af-11ea-8c6c-acb39c723d07.png)

1. get any data by `future`.
2. put it to singltone by `Get.put(data);`
3. get data by `Get.find<TypeOfData>()` => not registered exception!

**Comment by jonataslaw** [comment]
You are looking for: Get.find<TypeOfData>();
But you never registered a TypeOfData.
Please follow the documentation.
To use Get.put you must either type the instance: Get.put<TypeOfData>(value);
or receive it directly in a type:
TypeOfData type = Get.put(value);

**Comment by zl910627** [comment]
![image](https://user-images.githubusercontent.com/53897531/83660407-63515080-a5f7-11ea-9e30-16ef42898437.png)
![image](https://user-images.githubusercontent.com/53897531/83660441-6cdab880-a5f7-11ea-8c09-cd50edecf65b.png)

**Comment by zl910627** [comment]
![image](https://user-images.githubusercontent.com/53897531/83661377-9ea04f00-a5f8-11ea-8e5b-f97b0aa09d5e.png)

![image](https://user-images.githubusercontent.com/53897531/83661537-d9a28280-a5f8-11ea-9232-3e1f5d80e685.png)

**Comment by zl910627** [comment]
Please check above screenshots.
They would be good explain about what I want to say,

**Comment by jonataslaw** [comment]
Please, use type to your Get.put/Get.putAsync. 

Get.put<TypeOfData>(
Get.putAsync<TypeOfData>(

or:

TypeOfData t = Get.put(TypeOfData());

I still see the same mistakes that I pointed out in the first comment.

**Comment by zl910627** [comment]
Please see carefully.
Main problem is that when `Get.find`, _singl does not hold restaurant instance.

**Comment by zl910627** [comment]
When put, there were instance in Get()._singl.
https://user-images.githubusercontent.com/53897531/83661377-9ea04f00-a5f8-11ea-8e5b-f97b0aa09d5e.png

But later, when trying to `Get.find`, `Get()._singl` does not hold already registered.
https://user-images.githubusercontent.com/53897531/83661537-d9a28280-a5f8-11ea-9232-3e1f5d80e685.png

**Comment by jonataslaw** [comment]
I think you are trying to say that the instance is being removed from memory.
Well, I also saw that you are using Get.offAllNamed ('/') which will take all data out of memory, because you are removing the entire stack.
If you don't want this to happen, use a softer SmartManagement, like SmartManagement.onlyBuilder

I will need to document the aspects of SmartManagement, but for now you just need to know that the default is full "remove everything from memory when there are no references in the stack on it".
The medium is "onlyBuilder" which only removes instances related to a widget builder from the stack. The last "keepFactory" is for those who want to centralize all controllers in a single Binding.

**Comment by jonataslaw** [comment]
NOTE: SmartManagement is defined in your GetMaterialApp

**Comment by zl910627** [comment]
May I ask why 3 instances are keeping ?
According to your explain, they also should be removed?

**Comment by zl910627** [comment]
Nothing different except 3 instances are putted when app starts up, but restaurant is putted at splash screen with future.

**Comment by jonataslaw** [comment]
If an instance has been registered in an out-of-route scope (before GetMaterialApp, or before a route is called) using Get.put (the same does not happen with Get.lazyPut) it will be ignored by SmartManagement. Probably if you registered it on route '/' it will also not be removed if '/' is not removed from the stack.

**Comment by zl910627** [comment]
Wow!, really smart!
```
smartManagement: SmartManagement.onlyBuilder,
```
this line has been solve my head ache!

**Comment by jonataslaw** [comment]
My dream is to have documented everything that this library does, unfortunately I almost always have to choose between updating the code, or making the documentation, but I will open communities on social networks around Get and teach that kind of thing that was said in this issue, for others to contribute to the project (including adding documentation to the readme)
