### ISSUE TITLE
Get.Bottomsheet => The getter 'overlay' was called on null.

### ISSUE THREAD

**Issue by udiedrichsen** [jonataslaw/get#178]
**Describe the bug**
I tried to use Get.bottomSheet in Scaffold:

```
        floatingActionButton: FloatingActionButton(
          child: Icon(
            Icons.add,
          ),
          onPressed: () {
            print('Add ...');
            Get.bottomSheet(
              Container(
                child: Wrap(
                  children: <Widget>[
                    ListTile(
                        leading: Icon(Icons.music_note),
                        title: Text('Music'),
                        onTap: () => {}),
                    ListTile(
                      leading: Icon(Icons.videocam),
                      title: Text('Video'),
                      onTap: () => {},
                    ),
                  ],
                ),
              ),
            );
          },
        ),

```
But I get only this error message in the debug console:

════════ Exception caught by gesture ═══════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'overlay' was called on null.
Receiver: null
Tried calling: overlay

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      Get.overlayContext 
package:get/src/get_main.dart:912
#2      Get.bottomSheet 
package:get/src/get_main.dart:371
#3      _AttributesSectionAttributeState.build.<anonymous closure>.<anonymous closure> 
package:out_next_big_thing/…/attributes/AttributesSectionDetail.dart:55
#4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:772
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#98555
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(905.0, 523.6)
    finalLocalPosition: Offset(17.0, 29.1)
    button: 1
    sent tap down

**To Reproduce**
Click on FloatingButton and boom :-)

**Expected behavior**
I expect to see bottomsheet

**Screenshots**
No needed

**Flutter Version:**
Flutter 1.18.0-11.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2738a1148b (3 weeks ago) • 2020-05-13 15:24:36 -0700
Engine • revision ef9215ceb2
Tools • Dart 2.9.0 (build 2.9.0-8.2.beta)

**Get Version:**
2.10.2

**Describe on which device you found the bug:**
Web and Android

**Minimal reproduce code**
`        floatingActionButton: FloatingActionButton(
          child: Icon(
            Icons.add,
          ),
          onPressed: () {
            print('Add ...');
            Get.bottomSheet(
              Container(
                child: Wrap(
                  children: <Widget>[
                    ListTile(
                        leading: Icon(Icons.music_note),
                        title: Text('Music'),
                        onTap: () => {}),
                    ListTile(
                      leading: Icon(Icons.videocam),
                      title: Text('Video'),
                      onTap: () => {},
                    ),
                  ],
                ),
              ),
            );
          },
        ),`

**Comment by udiedrichsen** [comment]
I tried it also on the flutter stable channel with the same result.

**Comment by jonataslaw** [comment]
Please, read the docs. 
Change your MaterialApp to GetMaterialApp
