### ISSUE TITLE
How can I use get parameters or arguments in nested router

### ISSUE THREAD

**Issue by ChickenAhn** [jonataslaw/get#179]
**Describe the bug**
I'm trying to implement a nested router with `get`.
Navigating to each nested router is working now.
How can I get arguments or parameters in the nested route?

```
return Navigator(
      key: Get.nestedKey(1),
      initialRoute: '/',
      onGenerateRoute: (routeSettings) {
        if (routeSettings.name == '/') {
          return GetRouteBase(
            page: MyMainScreen(),
          );
        }
        if (routeSettings.name == '/nested') {
          return GetRouteBase(
            page: MyNestedScreen(),
          );
        }
      },
    );
```

Is there any way to pass some parameters with the route name?
like '/nested/:id'

Get.arguments only returns my parents arguments but the nested router's arguments

**Flutter Version:**
Flutter: 1.17.2

**Get Version:**
get: ^2.7.1

**Comment by jonataslaw** [comment]
For nested navigators, dynamic parameters are not supported, because onGenerateRoute does not support this type of feature, and I would have to create another Navigator to replace Flutter's Navigator widget and have this functionality. However with Navigator 2.0 coming, doing so now may be a waste of time.

**Comment by jonataslaw** [comment]
You can made this:

```dart
Navigator(
      key: Get.nestedKey(1),
      initialRoute: '/',
      onGenerateRoute: (routeSettings) {
        if (routeSettings.name == '/') {
          return GetRouteBase(
            page: MyMainScreen(),
          );
        }
        if (routeSettings.name == '/nested') {
          return GetRouteBase(
            page: MyNestedScreen(id: routeSettings.arguments), // Pass arguments to parameter
          );
        }
      },
    )
```

**Comment by jonataslaw** [comment]
Well, as it is a question, I am closing this.
If in the future I decide to create a widget to support nested navigation with dynamic routes, I will mark this issue to let you know.

**Comment by zzterrozz** [comment]
Hi @jonataslaw 
Any chance to have an implementation of parameters for nested navigation with dynamic routes please ?

**Comment by MoshDev** [comment]
I had to use this to make it work, not sure yet if it has any side effect somewhere else
```
Navigator(
                key: Get.nestedKey(1),
                onGenerateRoute: (settings) {
                  Get.routing.args = settings.arguments; // <---- this line 
                  return PageRedirect(settings: settings).page();
                },
              )
```

**Comment by liseipi** [comment]
> Well, as it is a question, I am closing this. If in the future I decide to create a widget to support nested navigation with dynamic routes, I will mark this issue to let you know.

Controller get args of now ?

**Comment by pzehle** [comment]
Hello. Is there any solution for this? @MoshDev 's solution is not helping me to use '/:id' parameter in route. Thank you.

**Comment by Sumit258000** [comment]
@MoshDev  Any idea how to make `Get.back()` work? because when using named routes in nested navigation `Get.back()` does not work but `Navigator.pop(context)` is working

**Comment by migalv** [comment]
Does anyone came up with some solution?

**Comment by Asif-shah786** [comment]
Does anyone came up with some solution?

**Comment by phawadshah** [comment]
> @MoshDev Any idea how to make `Get.back()` work? because when using named routes in nested navigation `Get.back()` does not work but `Navigator.pop(context)` is working

if you are using multiple Navigators for each tab then you can do this. 

class NamedNavigator extends StatelessWidget {
  final GlobalKey<NavigatorState>? navigatorKey;
  const NamedNavigator({required this.navigatorKey, super.key});

  @override
  Widget build(BuildContext context) {
    return Navigator(
      key: navigatorKey,
      initialRoute: Routes.INITIAL,
      onGenerateRoute: _onGenerateRoute,
    );
  }
}

Route<dynamic>? _onGenerateRoute(RouteSettings settings) {
  final arguments = settings.arguments as Map<String, dynamic>?;
  final newTag = arguments?['tag'] as String?;
  final newRoute = settings.name;

  switch (newRoute) {
    case Routes.CART:
      return GetPageRoute(
        routeName: Routes.CART,
        page: () => const CartScreen(),
        binding: CartBindings(),
      );
    case Routes.WISHLIST:
      return GetPageRoute(
        routeName: Routes.WISHLIST,
        page: () => WishlistScreen(
          navigationId: nestedNavigationCartId,
        ),
        binding: WishlistBindings(),
      );

    case Routes.SEARCH:
      return GetPageRoute(
        routeName: Routes.SEARCH,
        page: () => SearchScreen(
          uniqueTag: newTag,
          navigationId: nestedNavigationCartId,
        ),
        binding: SearchBindings(tag: newTag!),
      );

    case Routes.VIEWALLPRODUCTS:
      return GetPageRoute(
        routeName: Routes.VIEWALLPRODUCTS,
        page: () => ViewAllProductsScreen(
          uniqueTag: newTag,
          navigationId: nestedNavigationCartId,
        ),
        binding: ViewAllProductsBindings(tag: newTag!),
      );

    case Routes.PRODUCTDETAILS:
      return GetPageRoute(
        routeName: Routes.PRODUCTDETAILS,
        page: () => ProductDetailsScreen(
          uniqueTag: newTag,
          navigationId: nestedNavigationCartId,
        ),
        binding: ProductDetailsBindings(tag: newTag!),
      );

    default:
      return null;
  }
}

**Comment by phawadshah** [comment]
> @MoshDev Any idea how to make `Get.back()` work? because when using named routes in nested navigation `Get.back()` does not work but `Navigator.pop(context)` is working

YOU CAN DO LIKE THIS IF YOU ARE USING MULTIPLE NAVIGATORS.


class NamedNavigator extends StatelessWidget {
  final GlobalKey<NavigatorState>? navigatorKey;
  const NamedNavigator({required this.navigatorKey, super.key});

  @override
  Widget build(BuildContext context) {
    return Navigator(
      key: navigatorKey,
      initialRoute: Routes.INITIAL,
      onGenerateRoute: _onGenerateRoute,
    );
  }
}

Route<dynamic>? _onGenerateRoute(RouteSettings settings) {
  // INCASE CREATING MULTIPLE INSTANCES OF SAME CONTROLLER
  final arguments = settings.arguments as Map<String, dynamic>?;
  final newTag = arguments?['tag'] as String?;
  final newRoute = settings.name;

  switch (newRoute) {
    case Routes.OTHER:
      return GetPageRoute(
        routeName: Routes.OTHER,
        page: () => OTHERPAGE(
          navigationId: UNIQUEID,
        ),
        binding: OTHERBINDINGS(),
      );
    // THIS ROUTE HAS MULTIPLE INSTANCES OF SAME CONTROLLER
    case Routes.OTHERB:
      return GetPageRoute(
        routeName: Routes.OTHERB,
        page: () => OTHERPAGEB(
          uniqueTag: newTag,
          navigationId: UNIQUEID,
        ),
        binding: OTHERBINDINGS(tag: newTag!),
      );

    default:
      return null;
  }
}

class OTHERPAGE extends GetView<OTHERCONTROLLER> {
  final int navigationId;
  OTHERPAGE({
    required this.navigationId,
    super.key,
  }) {
    controller.navigationId = navigationId;
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class OTHERCONTROLLER extends GetxController {
  late int navigationId;
  void goBack() => Get.back(id: navigationId);
}

class OTHERPAGEB extends GetView<OTHERCONTROLLERB> {
  final int navigationId;
  final String uniqueTag;

  @override
  String? get tag => uniqueTag;

  OTHERPAGEB({
    required this.uniqueTag,
    required this.navigationId,
    super.key,
  }) {
    controller.navigationId = navigationId;
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class OTHERCONTROLLERB extends GetxController {
  late String tag;
  late int navigationId;
  void goBack() => Get.back(id: navigationId);
}
