### ISSUE TITLE
ios Right slip closing failure

### ISSUE THREAD

**Issue by 948911908** [jonataslaw/get#18]
After this is used in IOS, the right sliding close fails

**Comment by jonataslaw** [comment]
> After this is used in IOS, the right sliding close fails

Without more details it will not be possible to solve your problem.
In what situations have you experienced failure?
Using named routes? Using normal routes? Could you provide a minimal example of reproducing the problem?

**Comment by 948911908** [comment]
This is how I use it @jonataslaw 
<img width="1294" alt="WeChatb3047f190d164a159f9dd2c3e1f53fb7" src="https://user-images.githubusercontent.com/19320137/75735822-8ccbb900-5d36-11ea-8f68-426f40e2d11d.png">
<img width="722" alt="WeChat71c43c84a067fd913ac18e06de496ad0" src="https://user-images.githubusercontent.com/19320137/75735844-9ce39880-5d36-11ea-8a1b-f45a8578ca7f.png">

**Comment by 948911908** [comment]
`Get.to(_getPage(name, params), transition: Transition.rightToLeft);`

> MaterialApp(
      navigatorKey: Get.key,
      theme: ThemeData(
        appBarTheme: AppBarTheme(
          color: Color.fromRGBO(44, 173, 215, 1),
        ),
        platform: TargetPlatform.iOS,
      ),
      home: Container(
          child: Scaffold(
            resizeToAvoidBottomPadding: false, 
            body: MainWidget()
          )
        )
      );

**Comment by jonataslaw** [comment]
I still don't quite understand your code. Are you using named routes? What would the _getPage() method be?
Anyway, I did an update yesterday adding improvements to the cupertino on an experimental basis, if you want to test it, you can use GetCupertino instead of GetRoute, or just use Get.to (Screen()) for it, which it will automatically use GetCupertino and animation left to right if the device is iOS.

**Comment by 948911908** [comment]
I'm not using a named route
this is _getPage() code
![image](https://user-images.githubusercontent.com/19320137/75854953-35a81000-5e2c-11ea-9a99-3045726c03d6.png)

**Comment by 948911908** [comment]
@jonataslaw

**Comment by 948911908** [comment]
I reported an error after updating
![image](https://user-images.githubusercontent.com/19320137/75855286-e7474100-5e2c-11ea-94d6-1655e87d2a11.png)

**Comment by 948911908** [comment]
import 'package:get/src/transitions_type.dart';

I need to import this file to be normal
After updating the new version, IOS can be closed by right sliding

**Comment by jonataslaw** [comment]
> import 'package:get/src/transitions_type.dart';
> 
> I need to import this file to be normal
> After updating the new version, IOS can be closed by right sliding

It's fixed on version 1.11.1
Now you don't need to import any internal files from the library.
Thank you very much for reporting this too!
