### ISSUE TITLE
Get.until - simplify syntax

### ISSUE THREAD

**Issue by RodBr** [jonataslaw/get#181]
**Is your feature request related to a problem? Please describe.**
Currently Get.until expects a predicate which will always be  `ModalRoute.withName('pageName')`

**Describe the solution you'd like**
Replace 
```
  static void until(predicate, {int id}) {
    return _get.global(id).currentState.popUntil(predicate);
  }
```
with 
```
  static void until(page, {int id}) {
    return _get.global(id).currentState.popUntil(ModalRoute.withName(page));
  }

```
I didn't do a pull request as I wasn't sure if this was the desired functionality.

**Comment by jonataslaw** [comment]
Currently, Get.until doesn't just cover named routes, to close all open snackbars/dialogs/bottomsheets for example, you can use his callback in a Get.until, like:
`Get.until (() => Get.isSnackbarOpen);`
I can add a Get.popUntil as you suggested, it may be simpler for those using named routes, but Get.until cannot be changed, as this would break many other functions, such as the Get.back(closeOverlays: true);

**Comment by RodBr** [comment]
That's ok, now I understand.  Just got caught initially.

Thanks.
