### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by Andreigr0** [jonataslaw/get#187]
Please, add type annotations everywhere because without them IDE can't give any suggestions and it is sometimes hard to figure out what does method accept. It'd be cool if you'd use Lint

**Comment by jonataslaw** [comment]
Please specify which type notes you want to be added.
We use lint, but we have some options disabled.

**Comment by Andreigr0** [comment]
For example there are not types in functions `until`, `offUntil`, `offNamedUntil`, `removeRoute` and other methods such as `offAndToNamed` receives parameters with partial types `Future<T> offAndToNamed<T>(String page, {arguments, int id, result})` even though arguments and result are dynamic, I think it is better to annotate their types explicitly to dynamic

**Comment by jonataslaw** [comment]
Added on latest version
