### ISSUE TITLE
AppBar entre Rotas nomeadas (AppBar with named routes)

### ISSUE THREAD

**Issue by GustavoLofrano** [jonataslaw/get#189]
É possível persistir a mesma AppBar, sem precisar recriar em toda nova Rota, semelhante ao PageView?
Como se fosse um sistema de sub-rotas de uma rota do GetMaterialApp.

//// English:
Is it possible to persist the same AppBar, without having to recreate in every new Route, similar to PageView?
As if it were a sub-route system of a GetMaterialApp route.

**Comment by jonataslaw** [comment]
Não testei esse código, escrevi agora direto no comentário, mas você deve usar NestedNavigators.
///// English
I haven't tested this code, I wrote it right in the comment, but you should use NestedNavigators.

```dart
Scaffold(
appBar: AppBar(title: Text("sample")), 
body: Navigator(
  key: nestedKey(1), // create a key by index
  initialRoute: '/',
  onGenerateRoute: (settings) {
    if (settings.name == '/') {
      return GetRouteBase(
        page: Scaffold(
          body: Center(
            child: FlatButton(
              color: Colors.blue,
              onPressed: () {
                Get.toNamed('/second', id:1); // navigate by your nested route by index
              },
              child: Text("Go to second"),
            ),
          ),
        ),
      );
    } else if (settings.name == '/second') {
      return GetRouteBase(
        page: Center(
          child: Scaffold(
            body: Center(
              child:  Text("second")
            ),
          ),
        ),
      );
    }
  }
),
);
```
