### ISSUE TITLE
Undefined name 'Transition'

### ISSUE THREAD

**Issue by rommyarb** [jonataslaw/get#19]
<img width="1007" alt="Screen Shot 2020-03-04 at 16 08 42" src="https://user-images.githubusercontent.com/7745818/75863261-c386f980-5e32-11ea-8abc-cbbb1e53ebc8.png">

Hi @jonataslaw. Great library!
There's this one thing. Could you help me with how to set the transition type, because the IDE (vscode) cannot find the class Transition?

`dependencies:`
`get: ^1.11.0`

Thank you!

**Comment by jonataslaw** [comment]
> <img alt="Screen Shot 2020-03-04 at 16 08 42" width="1007" src="https://user-images.githubusercontent.com/7745818/75863261-c386f980-5e32-11ea-8abc-cbbb1e53ebc8.png">
> 
> Hi @jonataslaw. Great library!
> There's this one thing. Could you help me with how to set the transition type, because the IDE (vscode) cannot find the class Transition?
> 
> `dependencies:`
> `get: ^1.11.0`
> 
> Thank you!

I refactored the code to better support iOS swipe to back on non-native transitions, and created a new file for transitions in 1.11.0, however, to avoid breaking code and maintaining compatibility with the previous version, I sent a hotfix now to fix this and everything should work as expected in version 1.11.1 of Get.
Let me know if you need anything else, and thanks for reporting this bug.
