### ISSUE TITLE
Como fechar o drawer com o Get?

### ISSUE THREAD

**Issue by welitonxd** [jonataslaw/get#191]
Sou novo no flutter, estou tentando aprender aos poucos a metodologia do Get que já conseguir ir mais longe que os videos e informações coletadas na net.
Estou tentando fechar um drawer com o Navigator.pop pois não vi nada parecido no Get, gostaria de saber como faço isso, tentei o Navigator.pop(Get.context) mas me informa o erro abaixo, não consigo passar o context  para desfazer, talvez a duvida não seja nem sobre o Get, desculpe a pergunta teoricamente simples pra quem tem experiencia no ramo rs, aproveitar também para se tiver algum grupo relacionado ao package Get para poder entrar e ver mais formas de utilizar o mesmo nos meus projetos...

`The following assertion was thrown while handling a gesture:
 Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a
 descendant of a Navigator widget.`

meu drawer é separado do view para poder reutilizar nas outras paginas.

**Comment by jonataslaw** [comment]
Get.back();
