### ISSUE TITLE
onInit executa apenas quando é chamado pela primeira vez dentro de um builder

### ISSUE THREAD

**Issue by Denilson-source** [jonataslaw/get#199]
Talvez eu tenha entendido errado, mas o onInit do RxController nao deveria ser executado assim que a classe é instanciada? 

``` Dart
Column(
      children: [
           FlatButton(
             onPressed: UserListPageController.to.fetchUsers,
             child: Text('click'),
          ),
          Expanded(
            child: GetX<UserListPageController>(
              builder: (_) {
                return ListView.builder(
                  itemCount: _.users.length,
                  itemBuilder: (context, index) {
                    return Text(_.users[index].name);
                  },
                );
              },
            ),
          ),
        ],
      ),
```

Caso eu tire o botao o onInit executa corretamente, outra observaçao é que no builder obx()
o onInit nao executa tambem.

**Comment by Nipodemos** [comment]
Você tem duas opções:
1 - usar o `onInit:` para instanciar o controller apenas uma vez na aplicação. Se instanciar mais de uma vez, vai ter problemas inesperados.

2 - Criar uma classe bindings e usar o `Get.put(Controller())` lá dentro, aí fica instanciado lá e vc tem acesso na tela

Caso você use a segunda opção, aí sim que vc consegue usar o `Obx()`, sem ele que eu saiba vc é obrigado a usar o `GetX<Controller>()`

**Comment by Denilson-source** [comment]
``` dart
class UserListBinding implements Bindings {
  @override
  void dependencies() {
    Get.lazyPut<UserRepository>(() => UserRepository(ClientHttpService.to));
    Get.lazyPut<UserListPageController>(() => UserListPageController());
  }
}
```

  Quando uso o Get.put ele n executa o onInit de forma alguma, no lazyput ele executa, mas somente se eu usar a classe pela primeira vez num GetX.
  Na documentaçao Jonatas fala que nao é uma boa pratica iniciar coisas no contrutor que pra isso deve ser usado o onInit, por isso a minha duvida, se eu for usar ele pela primeira vez fora de um Widget por exemplo eu ja n consigo executar o onInit.

**Comment by jonataslaw** [comment]
> ```dart
> class UserListBinding implements Bindings {
>   @override
>   void dependencies() {
>     Get.lazyPut<UserRepository>(() => UserRepository(ClientHttpService.to));
>     Get.lazyPut<UserListPageController>(() => UserListPageController());
>   }
> }
> ```
> 
> Quando uso o Get.put ele n executa o onInit de forma alguma, no lazyput ele executa, mas somente se eu usar a classe pela primeira vez num GetX.
> Na documentaçao Jonatas fala que nao é uma boa pratica iniciar coisas no contrutor que pra isso deve ser usado o onInit, por isso a minha duvida, se eu for usar ele pela primeira vez fora de um Widget por exemplo eu ja n consigo executar o onInit.

Bem, inicialmente você deveria usar Bindings e usar a primeira vez sempre em um widget, mas um dos pontos abordados na atualização 2.11 que eu virei a noite fazendo é justamente mudar o ciclo de vida inteiro do Controller para não depender da View. É uma mudança de paradigma, mas vai evitar issues, porque vai funcionar fazendo de todo jeito Hahaha.
Tente a versão 2.11. Provavelmente já deve está resolvido na última versão.

**Comment by Denilson-source** [comment]
Cara, ficou perfeito, agora consigo ter uma noçao melhor do ciclo de vida das dependencias.
