### ISSUE TITLE
Controllers created in GetBuilder not removed when page is removed

### ISSUE THREAD

**Issue by RodBr** [jonataslaw/get#205]
**Describe the bug**
I have two types of controllers:
Type 1 = those I want to create at startup and use throughout the app;
Type 2 = those I want to create for an individual page and have removed when the page is removed from the stack.  They are created in GetBuilder.

Per [issue](https://github.com/jonataslaw/get/issues/188) I had `SmartManagement.onlyBuilder` set.
Now with code in Get find onInit controller will only fire with SmartManagement.full`.
```
      if (!isDependencyInit<S>() &&
          Get().smartManagement == SmartManagement.full) {
        Get().registerRouteInstance<S>(tag: tag);
        callInit = true;
```
I've made that change, but now my Type 2 controllers are not removed from memory when their page is popped from the stack.

**Expected behavior**
Type2 controllers are deleted when page is removed.

**Flutter Version:**
1.17.3

**Get Version:**
2.11.1

**Comment by michael-ottink** [comment]
Just put the global property to false :)

**Comment by RodBr** [comment]
That worked. There was also a bump in Get which seems to have taken away the need for setting the global property.  I can see the controllers from GetBuilder appearing and disappearing in DevTools.
