### ISSUE TITLE
Convert this StreamBuilder into Get in best practice

### ISSUE THREAD

**Issue by ghprod** [jonataslaw/get#207]
Hi, sorry if this isn't the right place.

I have streambuilder to detect auth status of firebase user like this

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final authService = FirebaseAuth.instance;
    
    return StreamBuilder<User>(
      stream: authService.onAuthStateChanged,
      builder: (context, snapshot) {
        final User user = snapshot.data;
        
        if (user.connectionState == ConnectionState.active) {
          return user.hasData
              ? HomePage()
              : LoginPage();
        }
        
        return const Scaffold(
          body: Center(
            child: CircularProgressIndicator(),
          ),
        );
      },
    );
  }
}
```

Do you have any suggestions to convert it using Get?

Thanks

**Comment by jonataslaw** [comment]
I am a backend programmer too, so my knowledge of firebase is limited (the last time I used firebase was 3 years ago, in native).
But based on your comment, I think you could use the same implementation you already use, or if you want to do an auth control, you can create an observable User and use BindStream to listen to firebase events as well.

final user = User().obs;
final authService = FirebaseAuth.instance;
onInit(){
user.bindStream(authService.onAuthStateChanged);
ever(user, checkLogin);
}
checkLogin(value){
// made anything when user is connected or disconnected 
}
}

**Comment by ghprod** [comment]
Thanks for your response. I'll try to learn more about obs first :)

Closed for now.
