### ISSUE TITLE
Bad state: Cannot add event while adding a stream

### ISSUE THREAD

**Issue by MostHated** [jonataslaw/get#208]
I was trying to follow the example's structure for setting up an observable in order to have a listener for a status change in order to call a function but keep getting the error "Bad state: Cannot add event while adding a stream".

I was not sure if it was actually necessary, but I created a standalone AuthStatusController and an RxStatus which was similar to the RxUser() in the example:

```dart
enum AuthStatus { signIn, signedIn, signOut, signedOut, notVerified, verified }

class RxStatus{
  final status = AuthStatus.signedOut.obs;
}

class AuthStatusController extends RxController{
  static AuthStatusController get to => Get.find();
  final rx = RxStatus();
  AuthStatus get status => rx.status.value;

  void setStatus(AuthStatus value) {
    rx.status.value = value;
  }

  set status(AuthStatus value) {
    rx.status.value = value;
  }
}
```
I was using the Event package before and setup my listener within initState() of the class in which I wanted to use it, so I had just replaced the old listener with the new one, but that is when I got the error.

This is what I was attempting to use
```dart

  @override
  void initState() {
    super.initState();

    ...
    ...
    AuthStatusController.to.rx.status.listen((status) {
      if (status == AuthStatus.notVerified) Future.microtask(() => _switchAuthMode(verify: true));
    });
  }
```
I didn't think it would make much difference, but I figured it was worth a try, so I attempted this, but it made no difference.

```dart
  addListener() async {
    await AuthStatusController.to.rx.status.listen((status) {
      if (status == AuthStatus.notVerified) Future.microtask(() => _switchAuthMode(verify: true));
    });
  }

  @override
  void initState() {
    super.initState();
	
    ...
    ...
    addListener();
  }
```

I am guessing that it must be something that I am doing incorrectly, but I am not quite sure what. I usually spend time searching and going through other people's projects/repos and looking for similar setups to try and spot what I am doing differently, but I am finding it a bit difficult to find any, unfortunately.

Thanks,
-MH

**Versions**
Flutter: (Channel master, 1.19.0-4.0.pre.81, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
get: ^2.11.1

**Comment by jonataslaw** [comment]
I think what you want to do is use `ever`. It is more appropriate for this situation, listen only takes effect after the first change, ever is perfect for what you are trying to do. Read a little bit about Workers before you go into that.

Do you really need an initState and a StatefulWidget?
I would use ever() (Worker) to listen to this event, preferably within a Controller class in his onInit.
Listen only delivers changes, and it cannot be placed before the start of the stream that will give this error, for that there is the subject.stream.listen that is able to hear everyone, but I think your project would be much more organized if you remove all that for your controller and use ever instead of listening to a stream.


```dart
class AuthStatusController extends RxController{
  static AuthStatusController get to => Get.find();
  final rx = RxStatus();
  @override
  onInit(){
  ever(rx, (status){
 if (status == AuthStatus.notVerified) Future.microtask(() => _switchAuthMode(verify: true));
 })
  }
  AuthStatus get status => rx.status.value;

  void setStatus(AuthStatus value) {
    rx.status.value = value;
  }

  set status(AuthStatus value) {
    rx.status.value = value;
  }
}
```

**Comment by MostHated** [comment]
My apologies, I should have clarified. The controller and such in the top section of code I shared are completely separate. The initState(), listener, and _switchAuthMode() are in my UI code to trigger a sequence of animations that change the login form to an email verification form once Firebase reports back if their account is verified or not.

I will give the 'ever' function and try and see if that does the trick.

Thanks,
-MH

**Comment by MostHated** [comment]
There are a few other small adjustments I need to make on my end to utilize things properly in a few more places, but the flow of user creation and login, as well as the rest of my application, are now using 100% Get and things seem to be working well. 

I definitely plan on seeing what else the package offers that I might be able to make use of, but for the bulk of things, looks like I am good to go. 👍

Thanks a lot, man. I appreciate it!
-MH

**Comment by jonataslaw** [comment]
No problem. Closing this issue, if you face problems you can open another issue. If you still have doubts you can comment right here and I will answer.
