### ISSUE TITLE
[Simple Instance Manager] Calling variables and methods from instance directly like Get_It?

### ISSUE THREAD

**Issue by d-apps** [jonataslaw/get#210]
Using Get_It package we can call a method from a registered class instance directly without need to create a variable from the class, is it possible to do that with Get's Simple Instance Manager?

**Get_It:**

```
GetIt.I.registerSingleton<Controller>(Controller());

GetIt.I<Controller>().counter = 2;
GetIt.I<Controller>().increment();
```

**Get:**

```
Get.put(HomeController());

Controller controller = Get.find();
controller.counter = 2;
controller.increment();
```

**Comment by jonataslaw** [comment]
> Using Get_It package we can call a method from a registered class instance directly without need to create a variable from the class, is it possible to do that with Get's Simple Instance Manager?
> 
> **Get_It:**
> 
> ```
> GetIt.I.registerSingleton<Controller>(Controller());
> 
> GetIt.I<Controller>().counter = 2;
> GetIt.I<Controller>().increment();
> ```
> 
> **Get:**
> 
> ```
> Get.put(HomeController());
> 
> Controller controller = Get.find();
> controller.counter = 2;
> controller.increment();
> ```

You can do it the way you see fit. This also works:

Get.put<Controller>(Controller());

Get.find<Controller>().counter = 2;
Get.find<Controller>().increment();
