### ISSUE TITLE
Not calling onInit or onClose

### ISSUE THREAD

**Issue by barriehadfield** [jonataslaw/get#212]
Sorry, this is not a bug nor question and there is no chat channel I could find, so forgive this as an issue, please. I am loving the philosophy behind Get for state management and am testing it prior to a refactor. 

My issue is that I am not seeing `onInit` or `onClose` being called.

My Controller is here:

```
import 'package:get/get.dart';

class AlfieController extends GetController {
  static AlfieController get to => Get.find();

  AlfieController() {
    print("---> in constructor");
    say = "Alfie is everything";
  }

  String say;

  @override
  void onInit() {
    print("XxXXxXXxXXxXXxXXxXXxXXxXXxXXxX init");
    super.onInit();
  }

  @override
  void onClose() {
    print("YyYYyYYyYYyYYyYYyYYyYYyYYyYYyY close");
    super.onClose();
  }

  String sentence() {
    return "Hello I am a sentence $say";
  }
}
```

And I have tried two forms of usage:

`Get.put<AlfieController>(AlfieController());`

Then

`print(AlfieController.to.sentence());`

And I also tried:

`
return GetBuilder<AlfieController>(
        init: AlfieController(),
        builder: (_) {
    ....
`

The output I am getting is:

```
---> in constructor
js_primitives.dart:32 [GOING TO ROUTE] /projects
js_primitives.dart:32 [GOING TO ROUTE] /
js_primitives.dart:32 Hello I am a sentence Alfie is everything
js_primitives.dart:32 ---> in constructor
js_primitives.dart:32 Hello I am a sentence Alfie is everything
```

The dependency injection is working fine, I am just puzzled as to why  `onInit` or `onClose` are not being called?

What am I doing wrong?

**Comment by barriehadfield** [comment]
Answering my own question as I debugged it.

Am I right in assuming that onInit is only called in the GetBuilder if the Controller has not already been initialised? 

So `print(AlfieController.to.sentence());` does not invoke `onInit()` and because I had used both methods of invocation in my code, the `GetBuilder` method was not calling `onInit` because the object had already been created.

I assume therefore that the `onInit` and `onClose` callback approach only works with the `GetBuilder`.

**Comment by michael-ottink** [comment]
Yes I think currently only the GetBuilder calls the onInit() and onClose(). I agree with you that it would be nice if the put and lazyput also had this behaviour.

**Comment by jonataslaw** [comment]
Currently, the controllers 'life cycle has no connection with the widgets' life cycle, at least if you haven't touched things like SmartManagement. If you did, I recommend that you read the documentation to find out what you are doing. Almost always the pattern (which is already configured) will suit you well, but touching it without knowing what you are doing can bring problems for you.
onInit is called when Get.put () is put into memory, regardless of where you put it.

```dart
void main() {
  runApp(GetMaterialApp(
    home: First(),
  ));
}

class AlfieController extends GetController {
  static AlfieController get to => Get.find();

  AlfieController() {
    print("---> in constructor");
    say = "Alfie is everything";
  }

  String say;

  @override
  void onInit() {
    print("XxXXxXXxXXxXXxXXxXXxXXxXXxXXxX init");
    super.onInit();
  }

  @override
  void onClose() {
    print("YyYYyYYyYYyYYyYYyYYyYYyYYyYYyY close");
    super.onClose();
  }

  String sentence() {
    return "Hello I am a sentence $say";
  }
}

class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Get.put<AlfieController>(AlfieController());
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            GetBuilder<AlfieController>(builder: (_) {
              print(_.sentence());
              return Text(
                _.sentence(),
              );
            }),
          ],
        ),
      ),
    );
  }
}

```

out:
```
flutter: [GET] GetMaterialController has been initialized
flutter: [GOING TO ROUTE] /
flutter: ---> in constructor
flutter: XxXXxXXxXXxXXxXXxXXxXXxXXxXXxX init
flutter: [GET] AlfieController has been initialized
flutter: Hello I am a sentence Alfie is everything
```


```dart
void main() {
  Get.put<AlfieController>(AlfieController());
  runApp(GetMaterialApp(
    home: First(),
  ));
}

class AlfieController extends GetController {
  static AlfieController get to => Get.find();

  AlfieController() {
    print("---> in constructor");
    say = "Alfie is everything";
  }

  String say;

  @override
  void onInit() {
    print("XxXXxXXxXXxXXxXXxXXxXXxXXxXXxX init");
    super.onInit();
  }

  @override
  void onClose() {
    print("YyYYyYYyYYyYYyYYyYYyYYyYYyYYyY close");
    super.onClose();
  }

  String sentence() {
    return "Hello I am a sentence $say";
  }
}

class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            GetBuilder<AlfieController>(builder: (_) {
              print(_.sentence());
              return Text(
                _.sentence(),
              );
            }),
          ],
        ),
      ),
    );
  }
}

```

out:
```
flutter: ---> in constructor
flutter: XxXXxXXxXXxXXxXXxXXxXXxXXxXXxX init
flutter: [GET] AlfieController has been initialized
flutter: [GET] GetMaterialController has been initialized
flutter: [GOING TO ROUTE] /
flutter: Hello I am a sentence Alfie is everything
```

As you can see in this reproduction example, everything works fine. If you are using an old version, upgrade to the latest one (the life cycle changed about 2 updates ago), and if you messed with SmartManagement, each one will behave in a different way.

**Comment by barriehadfield** [comment]
@jonataslaw thank you for the detailed reply.

I was on 2.10.2 and have now upgraded to 2.11.3.

Much appreciated. I think you have an outstanding framework and I am enjoying working with it.
