### ISSUE TITLE
Alternative to Nested Navigators

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/get#213]
**Describe the bug**
In the docs you say:
>NOTE: Creating parallel navigation stacks can be dangerous. The ideal is not to use NestedNavigators, or to use sparingly. If your project requires it, go ahead, but keep in mind that keeping multiple navigation stacks in memory may not be a good idea for RAM consumption.

Is there any alternative method you use in your own apps that provides similar functionality.

If there is, how would you refactor this code
```dart
Navigator(
  key: Get.nestedKey(1), // create a key by index
  initialRoute: '/',
  onGenerateRoute: (settings) {
    if (settings.name == '/') {
      return GetRouteBase(
        page: Scaffold(
          appBar: AppBar(
            title: Text("Main"),
          ),
          body: Center(
            child: FlatButton(
              color: Colors.blue,
              onPressed: () {
                Get.toNamed('/second', id:1); // navigate by your nested route by index
              },
              child: Text("Go to second"),
            ),
          ),
        ),
      );
    } else if (settings.name == '/second') {
      return GetRouteBase(
        page: Center(
          child: Scaffold(
            appBar: AppBar(
              title: Text("Main"),
            ),
            body: Center(
              child:  Text("second")
            ),
          ),
        ),
      );
    }
  }
),
```

**Comment by jonataslaw** [comment]
I don't know if Navigator 2.0 will bring any improvement to this, but Flutter doesn't provide a satisfactory way to do this, so use it, but use it with caution.
