### ISSUE TITLE
Question - Is GetRoute() supposed to instantiate an instance of the page upon GetMaterialApp() build?

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#216]
I am using Get 2.11.3 and Flutter 1.17.3 

And I noticed that my `'/home': GetRoute(page: TheHomeView()),` makes an instance of `TheHomePage()` before the GetMaterialApp initializes. Is this supposed to happen? So all the pages are in memory the moment the app starts right?

I bumped into this when my home page widget had a field `final controller = put<SomeController>(SomeControlleer(Get.find<someDependency>())) ` where I intended the controller to be made once an instance of the widget is made. But I gues this is not meant to be done like this right because the widgets are instantiated when the GetMaterial app initializes? I got an error on app startup saying the dependency is missing. Wich is correct because the dependency is not yet put.

So just to be clear this is intentional right? I heard you mention something about that put is completely seperated from the widgets lifecycle. 

I think I can probably solve this with bindings, but I was also doing this with my `find()`. So in my widget I would say `final someController = Get.find<SomeController >() `above the build method thinking this would only be called when routing to this page, But it doesn't work because the dependency doesn't exist yet when the app starts. **So I gues I just have to `find()` controllers in my build method right?**

So the pages are instantiated and are being reused right?

This example confused me though

```
class Home extends StatelessWidget {
  // Instantiate your class using Get.put() to make it available for all "child" routes there.
  final Controller c = Get.put(Controller());
  @override
  Widget build(context) => Scaffold(
      appBar:
          AppBar(title: Obx(() => Text("Total of clicks: " + c.count.string))),
      // Replace the 8 lines Navigator.push by a simple Get.to(). You don't need context
      body: Center(child: RaisedButton(
              child: Text("Go to Other"), onPressed: () => Get.to(Other()))),
      floatingActionButton:
          FloatingActionButton(child: Icon(Icons.add), onPressed: c.increment));
}
```

since you are putting a controller in the widget itself, so it would be put on app start when using named routes with GeRoute(). So the controller will be put on app startup instead of when you navigate to the page? 

I gues in your example it will work since it doesn't have any dependency, but just to be clear final `Controller c = Get.put(Controller());` will already be in memory for a page not yet shown when the app starts right is that efficient?

To me it would make sense if a page only is instantiated if it actually is being routed to, or at least have the option to. Am I just naive? Isn't there a way to register the pages with a builder and only build them when routed to with named routes and dispose of them when they are no longer in the routing history?

In the flutter documentation they also say named routes are being built once you navigate to them

> The initialRoute property defines which route the app should start with. The routes property defines the available named routes and the widgets to build when navigating to those routes.

So here is the minimal reproducible code

```
void main() async {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: '/',
      namedRoutes: {
        '/': GetRoute(page: Page1()),
        '/page2': GetRoute(page: Page1()),
      },
    );
  }
}

class Page1 extends StatelessWidget {
  Page1() {
    print('this is called upon app startup');
  }

  @override
  Widget build(BuildContext context) {
    return RaisedButton(child: Text('goto page 2'), onPressed: () => Get.toNamed('/page2'));
  }
}

class Page2 extends StatelessWidget {
  Page2() {
    print('this is also callled upon app startup');
  }

  @override
  Widget build(BuildContext context) {
    return RaisedButton(child: Text('goto page 1'), onPressed: () => Get.toNamed('/'));
  }
}

```

which logs

```
I/flutter (24468): this is called upon app startup
I/flutter (24468): this is called upon app startup
I/flutter (24468): [GET] GetMaterialController has been initialized
I/flutter (24468): [GOING TO ROUTE] /
```

So the two widgets are initialized upon app start

**Comment by jonataslaw** [comment]
> So I could safely do Get.put() in a widget? Or should I always do that in a binding? And Get.find() is aimed to be used in the build method of a widget right?
> 
> I noticed that I was calling the find() often so I would make a reference in the method. But when having multiple methods it gets messy having a reference in each one. I could ofcourse pass the reference as an argument to other methods but I was looking for an option to have the reference available in the entire widget when the widget is made.
> 
> Personally I don't think the builder is advanced at all since numerous flutter widgets require you to use it, and it actually would be more intuitive for people I think. But right now it's not a big problem for me.

I don't always use Bindings.
Only for projects with dozens of services.
Get.put and Get.find () within the build will solve most problems in most cases.
Time is money, if your code is not strange, or if you initialize one or two controllers per screen, it is not so necessary to use Bindings.

I even recommend everyone to start with Get.put.
Bindings are cool, but you have to follow many SmartManagement rules for it to work properly, if you forget a rule, nothing will work.

**Comment by michael-ottink** [comment]
I see there is new documentation on that. I will read that tommorow. I'll close this question.

**Comment by michael-ottink** [comment]
I would still ask you to consider using a builder for named routes `GetRoute (() => Home (), binding);` . I was looking but my signup page which is a stateless widget has all the flags of the country code package in memory even tho I have never routed to this before. This is 35k in memory. I cost me alot of performance. I truly believe this woul be the better approach.

![image](https://user-images.githubusercontent.com/15832303/84436377-a46ae580-ac33-11ea-90e5-254e623cfada.png)
