### ISSUE TITLE
Help | How to dispose TextEditingController in Controller

### ISSUE THREAD

**Issue by NiranjanShah** [jonataslaw/get#226]
I have defined a TextEditingController for all the elements in a List, is it mandatory to dispose the TextEditController from the "GetController", if yes, how ?

Also guide, if the below is the correct way to attach TextEditingController for all rows in the list.
(_ipList is of type List<Object>)

 _ipList.asMap().forEach((index, element) {
          _ipList[index].ipuValue = (index + 1).toString();
          _ipList[index].textEditingController = TextEditingController();
        });

Thanks in advance

**Comment by jonataslaw** [comment]
It is not very orthodox to insert TextEditingControllers in lists, but if you do, when the controller is removed, the list will be removed, and it will be removed. You do not need to dispose of anything.

**Comment by NiranjanShah** [comment]
"It is not very orthodox to insert TextEditingControllers in lists,"

Can you please guide me to achieve the most elegant way to do it ?

**Comment by ialameh** [comment]
up
