### ISSUE TITLE
Get.offAllNamed not passing arguments

### ISSUE THREAD

**Issue by kterto** [jonataslaw/get#227]
**Describe the bug**
I've experienced a problem trying to use Get.offAllNamed(ROUTE_NAME, arguments {
SOME_OBJECT,
},). When using the exact same arguments and ROUTE_NAME but with Get.to, Get.offNamed or Get.off, SOME_OBJETC was successfully passed to the next page, but when using Get.offAllNamed, SOME_OBJECT was found to be null. 

**To Reproduce**
1. Use Named routes and try to pass some object as argumt 
2. Use Get.offAllNamed to navigate and pass the object
3. Object is found to be null in the target page.

**Expected behavior**
One should be able to access the arguments object

Flutter Version:**
1.17.0

**Get Version:**
2.12.5

**Describe on which device you found the bug:**
Samsung A51

**Minimal reproduce code**
Get.offAllNamed(
        ROUTE_NAME,
        arguments: {
        KEY: data,
        },
      );

**Comment by jonataslaw** [comment]
I was able to confirm and that works properly.
You should probably be putting Get.arguments out of a Controller or the build method, and it probably won't work, but there is definitely no bug in Get.offAllNamed.
Please review your settings, or if you are sure this is a bug, open an issue with a reproduction case.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: '/',
      namedRoutes: {
        '/': GetRoute(page: Home()),
        '/second': GetRoute(page: Second()),
        '/third': GetRoute(page: Third())
      },
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("home build");
    print("${Get.arguments}");
    return Material(
      child: FlatButton(
          onPressed: () {
            Get.toNamed('/second');
          },
          child: Text('go to second')),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: FlatButton(
          onPressed: () {
            Get.toNamed('/third');
          },
          child: Text('go to third')),
    );
  }
}

class Third extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: FlatButton(
          onPressed: () {
            Get.offAllNamed(
              '/',
              arguments: {
                "KEY": "data",
              },
            );
          },
          child: Text('off all to home')),
    );
  }
}

```
out:
```
flutter: [GET] GetMaterialController has been initialized
flutter: [GOING TO ROUTE] /
flutter: home build
flutter: null
flutter: [GOING TO ROUTE] /second
flutter: [GOING TO ROUTE] /third
flutter: [GOING TO ROUTE] /
flutter: [REMOVING ROUTE] /third
flutter: [REMOVING ROUTE] /second
flutter: [REMOVING ROUTE] /
flutter: home build
flutter: {KEY: data}

```
