### ISSUE TITLE
Name could be improved to find it in web

### ISSUE THREAD

**Issue by antonyr** [jonataslaw/get#228]
Thank you for the great framework.

When I want to quickly search for solutions in Google, since the name is Get (as it is a very generic term), It is hard to find on web.

Please consider changing the name of the framework while retaining APIs as is.

**Comment by jonataslaw** [comment]
I know that Get really is the worst keyword I could find, but unfortunately I don't know what to do, maybe adding another keyword will help you, but it might be difficult to change the name now, there are practically 400 stars on the pub.dev .
That's really a question that I would love suggestions

**Comment by NiranjanShah** [comment]
I had suggested the same earlier, will be gr8 it you can come up with some good name.....

**Comment by jonataslaw** [comment]
Maybe I'll change the internal names and start using GetX.
This would cause minimal impact as it would only add one letter.
It would be easy to remember and I would have minimal changes.
If I change my name I will have to deprecate the current package. And by adding X, I can easily enjoy the current one.

**Comment by ghprod** [comment]
GetX :+1:

**Comment by NiranjanShah** [comment]
> GetX 👍 and thanks for accepting our request !!!!!
> 

Regards
Niranjan G Shah

**Comment by maPer77** [comment]
I thought the same thing, GET is very generic ...
GetX is good

**Comment by jonataslaw** [comment]
I am moving this discussion to that topic.

https://github.com/jonataslaw/get/issues/238
