### ISSUE TITLE
Get.put is required to use Controller ?

### ISSUE THREAD

**Issue by Victor-Dev77** [jonataslaw/get#231]
Hi,
In your example code on this repo (virus tracker), you don't register `Controller` with `Get.put`

I rewrite the counter app and use `GetBuilder` and init Controller in `init` param.

But I got an exception like this: `The following message was thrown building HomePage(dirty):
I/flutter ( 9822):  CounterController not found. You need call Get.put<CounterController>(CounterController()) before`

So I'm obligated to use `Get.put(CounterController())` above `runApp` or put the controller in widget before build method.

I don't understand how your example code no throw this exception. You can use directly the Controller without put it...

**Flutter: 1.17.1**
**Get: ^2.12.5**

**Comment by jonataslaw** [comment]
Hi, add: global = false: to you GetBuilder

**Comment by Victor-Dev77** [comment]
Ha, it's because i've a floatingButton to increment counter and use this: `CounterController.to.increment`. So `Get` try to find CounterController (`static CounterController get to => Get.find();`) but it's not put.
If I use Controller anywhere outside `GetBuilder` so i shoud use `Get.put` ?

**Comment by jonataslaw** [comment]
How are you starting your Controller?
If inside a GetBuilder:
`AutoRemove: false`

If outside:
`Permanent: true`

**Comment by Victor-Dev77** [comment]
This is my Controller: 
```
class CounterController extends GetController {

  static CounterController get to => Get.find();

  CounterModel _counter;
  CounterController() {
    _counter = CounterModel();
  }

  get value => this._counter.value;

  void increment() {
    _counter.value++;
    update();
    print(_counter.value);
  }

}
```

The CounterModel is just a simple Dart class without dependancies (no extends)

And I use it in HomePage widget (stateless, initialRoute) like this:
```
GetBuilder<CounterController>(
      init: CounterController(),
      builder: (controller) {
           return Text(
                '${controller.value}',
                style: TextStyle(color: Util.randomColor(), fontSize: 30),
            );
       },
),
```

and increment counter with FAB in same widget (homePage)
```
floatingActionButton: FloatingActionButton(
        onPressed: CounterController.to.increment,
        backgroundColor: Util.randomColor(),
        child: Icon(Icons.add),
      ),
```

With yours params, doesn't work also... I've the same exception (CounterController not found. required to `.put` controller).
It works if I use `Get.put(CounterController())` above `runApp` or in HomePage build method

But I don't understand why in your example, you don't need to put all controller

**Comment by jonataslaw** [comment]
This happens for a few reasons, without your complete code I cannot say which, but you will be able to identify with these tips:
1- init: must be in the first widget that uses the Controller.
If you put it in an appBar, for example, and use it without it in the body, you will have problems with the mentioned error, because Flutter renders the body first, then the appbar / floatingActionButton / Bottom
2- it is not safe in dart to pass functions from other classes directly by parameter. This works most of the time, but there are problems in some cases in compiling for the web due to javascript, and even mobile. I always use arrow functions in an onPressed to make sure I don't have any errors when I call another class. You can try this:

```dart
floatingActionButton: FloatingActionButton(
        onPressed: ()=> CounterController.to.increment, // add (){} or ()=>
        backgroundColor: Util.randomColor(),
        child: Icon(Icons.add),
      ),
```

Following this you will find no more errors.

**Comment by Victor-Dev77** [comment]
YES ! I was going to say the same thing to you lol.
My mistake comes with your 2nd text `() =>` .
Thank you for your explanations of the potential errors ! 👌
