### ISSUE TITLE
Snackbar not working properly in IOS

### ISSUE THREAD

**Issue by praveen-francium** [jonataslaw/get#232]
Get.snackBar not working properly in IOS but working properly in android.Snackbar is not coming at all in IOS.

```
Get.snackbar(
                          "Hello",
                          "",
                          margin: EdgeInsets.zero,
                          snackPosition: SnackPosition.BOTTOM,
                          snackStyle: SnackStyle.GROUNDED,
                          backgroundColor: Colors.black)
```

**Comment by praveen-francium** [comment]
> Get.snackBar not working properly in IOS but working properly in android.Snackbar is not coming at all in IOS.
> 
> ```
> Get.snackbar(
>                           "Hello",
>                           "",
>                           margin: EdgeInsets.zero,
>                           snackPosition: SnackPosition.BOTTOM,
>                           snackStyle: SnackStyle.GROUNDED,
>                           backgroundColor: Colors.black)
> ```

After setting instantInit = true in Get.snackbar, it is working fine.

**Comment by jonataslaw** [comment]
> > Get.snackBar not working properly in IOS but working properly in android.Snackbar is not coming at all in IOS.
> > ```
> > Get.snackbar(
> >                           "Hello",
> >                           "",
> >                           margin: EdgeInsets.zero,
> >                           snackPosition: SnackPosition.BOTTOM,
> >                           snackStyle: SnackStyle.GROUNDED,
> >                           backgroundColor: Colors.black)
> > ```
> 
> After setting instantInit = true in Get.snackbar, it is working fine.

Sorry for the delay.
I will make instantInit = true the default in future updates.
This is not a problem with Get, but with Flutter, which sometimes hangs in the SchedulingBinding.instance, and while they don't fix it, it might be better to make the default startup automatic.

Glad you solved it on your own.
