### ISSUE TITLE
Controller works without putting? 

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#233]
I use flutter 1.17.3 and get 2.12.5 and if I create an instance of a controller in a widget like this

`final _controller = GroupCreateViewController();`

instead of this

`final _controller = Get.put<GroupCreateViewController>(GroupCreateViewController());`

it still works? So why is that possible? I gues Get will not delete is for you if you do it like this right?

**Comment by ghprod** [comment]
I think it's still working because you referenced in the same file, but form #1 is kinda like a singleton pattern and usually not friendly for testing.

cmiiw

**Comment by michael-ottink** [comment]
@ghprod Aah I see, makes sense
