### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Denilson-source** [jonataslaw/get#234]
Seria interessante uma função pra fechar o teclado, tipo Get.dismissKeyboard que n precisasse de contexto, pelo menos eu uso muito essa função principalmente em formulários, eu criei uma própria mas ela precisa de contexto, passar o Get.context nao funciona nesse caso.

```Dart
static void dismiss(BuildContext context) {
    FocusScopeNode currentFocus = FocusScope.of(context);

    if (!currentFocus.hasPrimaryFocus) {
      currentFocus.unfocus();
    }
  }
```

**Comment by jonataslaw** [comment]
Get já tem essa função, ela só estava desativada porque eu ainda não tenho testes para ela. Mas vou ativar no update de agora para você testar, se quiser.

**Comment by jonataslaw** [comment]
Get.focusScope

**Comment by Denilson-source** [comment]
funcionou como e esperado, porem ela atrapalha a snackbar, quando a funçao da erro, onde devia mostrar a snackbar nada acontece, se eu der um hot reload ai a snackbar aparece.

```dart
void login() async {
    validarForm();

    if (!_formValido)
      return Get.snackbar('Erro', 'Preencha o formulário corretamente');

    Get.focusScope.unfocus();

    if (await AuthController.to.login(email.text, senha.text)) {
      Get.offAllNamed(HomeRouter.homeRoute);
    }
  }
```

AuthController.to.login
```dart
try {
      state.value = AuthState.loading;

      final _user = await _authRepository.login(email, senha);

      user.value = _user;
      state.value = AuthState.authenticated;
      return true;
    } on ApiException catch (e) {
      state.value = AuthState.unauthenticated;
      Get.snackbar('Erro', e.mensagem);
      return false;
    } catch (e) {
      print('Erro: $e');

      state.value = AuthState.unauthenticated;
      Get.snackbar(
        'Erro',
        'Ocorreu um erro ao cadastrar, verifique sua conexão e tente novamente',
      );

      return false;
    }
```

**Comment by jonataslaw** [comment]
instantInit:true na snackbar deve resolver

**Comment by Denilson-source** [comment]
Resolveu! Cara, tu possui um Patreon ou algo assim? o pacote é muito bom, meu codigo tem outra cara agora (sem contar o suporte praticamente integral que tu da aqui kkk) e gostaria de contribuir nem que seja dessa forma.

**Comment by jonataslaw** [comment]
Não tenho man, tenho só um buymeacoffee, mas fica tranquilo, faço isso pela comunidade
