### ISSUE TITLE
BottomSheet | 1 positional argument expected, but 0 found

### ISSUE THREAD

**Issue by NiranjanShah** [jonataslaw/get#237]
Get.bottomSheet(
        isScrollControlled: true,
        ignoreSafeArea: false, // add this
        builder: (_) {
          return SafeArea( // and this
            child: Container(
              child: new Column(
                children: <Widget>[
                  Expanded(
                      child: Container(
                          color: Colors.red,
                          child: Center(
                            child: Text("text"),
                          )))
                ],
              ),
            ),
          );
        }
        );

**Comment by jonataslaw** [comment]
Please read the documentation.
This code seems to be from version 1.0, it is very old.

```dart
    Get.bottomSheet(
      SafeArea(
        child: Container(
          child: new Column(
            children: [
              Expanded(
                  child: Container(
                      color: Colors.red,
                      child: Center(
                        child: Text("text"),
                      )))
            ],
          ),
        ),
      ),
      isScrollControlled: true,
      ignoreSafeArea: false, // add this
    );
```
