### ISSUE TITLE
is there any Android Studio or IntelliJ plugin?

### ISSUE THREAD

**Issue by azliabdullah** [jonataslaw/get#239]
Hello, thanks for the great soon-to-be-framework!
Anyway, I tried to find Android Studio or IntelliJ plugin. Searching for `get` in inefficient. So unable locate any plugin. I could only found Vs Code plugin fro the readme. TIA!

**Comment by jonataslaw** [comment]
There is still no plugin for android studio.
The vscode plugin was created by another user in the community, and I hope some intellij will come up soon.
I unfortunately have 0 time to think about these things, at the moment I'm focused on the new library features

**Comment by azliabdullah** [comment]
It's cool, thanks for your answer! Was just afraid it exist but I couldn't find it.

**Comment by jonataslaw** [comment]
When it is created, I will put it in the readme. You can "watch" the repository to find out when it happens.
