### ISSUE TITLE
How do I deal with multiple controllers responding to eachother?

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#240]
I have flutter version 1.17.3 and Get 2.12.5.

Okay let's say I have 2 controllers, a signup controller and a authentication controller. And I am using Firebase. So in my sign up controller I sign up with phone auth. After that I await creating a database record for my user. But Firebase doesn't care about that. It trigger's the onAuthChanged anyway. So my Authentiation's controller event will trigger a will authenticate me before the user is even registered in the database. 

How would I deal with this problem using Get? Is there a way that I can prioritize my sign up controller? Or should I have a different way of dealing with this?

Signup Controller / Vertification Complete

```
  Future<void> _verificationComplete(AuthCredential authCredential, SignUpInfo signUpInfo) async {
    try {
      final AuthResult authResult = await FirebaseAuth.instance.signInWithCredential(authCredential);
      final AuthenticatedUserModel user = AuthenticatedUserModel(
          authResult.user.uid, signUpInfo.displayName, signUpInfo.photoURL, authResult.user.phoneNumber);

      AuthenticatedUserModel.fromFirebase(authResult.user);
      final fireStore = FirestoreService(user);
      await fireStore.createUser(user);

      final String token = await CloudMessagingService(user).fetchDeviceToken();
      final DeviceInfoModel deviceInfo = Get.find<DeviceInfoModel>();
      deviceInfo.updateLanguageCode(signUpInfo.languageCode);
      deviceInfo.updateNotificationToken(token);
      await fireStore.setDeviceInfo(deviceInfo);
      
    } on PlatformException catch (error) {
      internalState = AuthenticationState.unauthenticated;
      update();
      await _authentication.signOut();
      await Get.dialog(PlatformAlertDialog(
        error.code,
        error.message,
      ));
    } catch (error) {
      internalState = AuthenticationState.unauthenticated;
      update();
      await _authentication.signOut();
      await Get.dialog(PlatformAlertDialog(
        'Error',
        'The sign up operation could not be completed',
      ));
    }
  }
```

Auth controller / onAuthStateChanged

```
  @override
  void onReady() async{
    print('auth is ready');
    super.onReady();
    await Future.delayed(Duration(seconds: 2));
    _listner =
        _authentication.onAuthStateChanged.listen((FirebaseUser firebaseUser) => _onAuthStateChanged(firebaseUser));
  }

  Future<void> _onAuthStateChanged(FirebaseUser firebaseUser) async {
    if (firebaseUser != null) {
      protectedUser = await FirestoreService(AuthenticatedUserModel.fromFirebase(firebaseUser)).getUser();
      protectedState = AuthenticationState.authenticated;
    } else {
      protectedUser = null;
      protectedState = AuthenticationState.unauthenticated;
    }
    update();
    
    if (state == AuthenticationState.authenticated) {
      onAuthenticated?.call(protectedState);
    } else {
      onUnauthenticated?.call(protectedState);
    }
  }
```

**Comment by jonataslaw** [comment]
You don't need this, but if you want it so much, you could use Get.lazyPut for what you want to update, and use Get.find () when you want to put it in memory.
You could create an intermediate screen for recording in the database.
This is a hack, I still find this approach more complicated.
I would leave the change of routes in charge of an "ever" in something like "hasSession = false.obs", and change the state to true only if the user has been authenticated and the data recorded in the database, but you seem to be wanting to "reinvent the wheel "with the current approach. Things should definitely be simpler.

**Comment by ghprod** [comment]
Maybe try to put your user creation into cloud functions with `functions.auth.user().onCreate()`? Or make Signup Controller not nested under AuthController.

**Comment by michael-ottink** [comment]
You mean I don't need the onAuthChanged? 

> I would leave the change of routes in charge of an "ever" in something like "hasSession = false.obs", and change the state to true only if the user has been authenticated and the data recorded in the

What would change the hasSession then? I have to do set that manually whenever the user presses logout for example? So it doesn't happen automatically? So if anything happens that I didn't think of that changes the authentication state, the user will stay authenticated. Isn't that vulnerable?

**Comment by michael-ottink** [comment]
> Maybe try to put your user creation into cloud functions with `functions.auth.user().onCreate()`? Or make Signup Controller not nested under AuthController.

I did use a cloud function before but it was really slow. And I need to pass info from my client, which isn't possible with a sign in.

**Comment by michael-ottink** [comment]
> Maybe try to put your user creation into cloud functions with `functions.auth.user().onCreate()`? Or make Signup Controller not nested under AuthController.

Maybe I'll try to remove the authentiction controller whenever the user is sent to the sign up screen. Could work potentially.
