### ISSUE TITLE
How do I deal with controllers updating after the widget is already deleted?

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#241]
I am using flutter version 1.17.3 and Get 2.12.5.

And I noticed that if I have a controller which is calling a callback when it's widget is already deleted a memory leak will occur. I do get a warning that this is happening. But what is a good way of dealing with this? Should I store the callback and set it to null onClose()?

**Comment by jonataslaw** [comment]
Widget deleted, the controller will be deleted.
Before the controller is deleted, onClose is called.
If the default SmartManagement is enabled, onClose will happen before the widget is deleted (as soon as you click on remove or replace a route), and onDelete will happen simultaneously at your disposal.
onClose is async, which ensures that all operations placed on it occur before onDelete. That's all you need to know to handle things on your own.

The onClose method is part of the Controllers life cycle, and you should study it and create the logic of your application just as you would with a StatefulWidget.
I would love to continue answering support questions, but unfortunately this is wasting my time.
Please, if you have support questions, ask at Stackoverflow, which I and other users can answer.
If you have a real bug demonstration, with prints, reproduction code, etc., feel free to open an issue.
