### ISSUE TITLE
Feature Request - Workers injecting the previous obs value into the callback

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#242]
I noticed that workers only inject the latest value of a obs. But there are many cases where you want to do something with the difference between the previous value and the current value. 

Let's say you have a field of type double that is bound to a location stream which is mapped to your travel speed. And you want to do something with your acceleration in your worker's callback. I could not think of a way to do this elegantly.

I assume that under the hood there is already some check in place if the value changed since the workers only trigger when the value is changed.

**Comment by jonataslaw** [comment]
In the past, the previous object was kept and a comparison was made.
However, this made the observables very expensive because they had to store two data sources, which spent more ram.
Currently, he does an ephemeral and transient check at the moment of the change, comparing the object that is being changed with the current one, and if it is the same, he already rejects the operation before making any kind of logic. This ensures greater stabilization of the CPU (you can strafe 1 billion sets on the same object, this will not cost you processing), and prevents resources from being spent unnecessarily.
Reimplementing this would perhaps be a regression, and would cause an increase in the consumption of RAM, especially when creating giant observable classes, keeping two of them in memory would not be very smart.
So I think we might not do that again, which makes it impossible to create a resource like this natively. However, what you want to do does not require a minimum of effort, just create a current variable and an old one, and simply use a worker to record them.

```dart
int previous = 0;
int actual = 0;
var change = 0.obs;

onInit(){
ever(change, (v){
previous = actual; 
actual = v;
});
}
```

**Comment by michael-ottink** [comment]
I see that would be I will try that approach. I think this would be nice to have in the docs. I'll close this for now.

**Comment by michael-ottink** [comment]
@jonataslaw is there no value at all injected anymore? When running     

`ever(_groupList, (value) => print(value));`

value will always be null

```
class GroupListController extends RxController
{
  ListX<GroupModel> _groupList = List<GroupModel>().obs;
  BoolX _hasData = false.obs;

  ListX<GroupModel> get groupList => _groupList;
  bool get isConnected => _hasData.value;

  @override 
  void onInit()
  {
    final DatabaseService databaseService = Get.find<DatabaseService>();
    _groupList.bindStream(databaseService.groupListStream());
    once(_groupList, (value) => _hasData.value = true);
    ever(_groupList, (value) => print(value));
  }
}
```

**Comment by ghprod** [comment]
which version you are using?

**Comment by michael-ottink** [comment]
I am using Get 2.13.1

This is what I am trying to do

```
class GroupController extends RxController
{
  final Rx<Object> _rxGroup;

  GroupModel get group => _rxGroup.value;

  GroupController(GroupModel group) : _rxGroup = group.obs;
  
  @override
  void onInit(){
    final GroupListController groupListController = Get.find<GroupListController>();
    ever(groupListController.groupList, onGroupListChange);
    super.onInit();
  }

  void onGroupListChange(dynamic value)
  {
    final GroupListController groupListController = Get.find<GroupListController>();
    final GroupModel groupReference = groupListController.groupList.value?.firstWhere((element) => element.id == group.id);
    if(groupReference != null)
      _rxGroup.value = groupReference;
  }
}
```

Which I now solved by finding the controller again. 

**Question**

 if my GroupController is deleted does the callback keeps existing since I am using an ever on a ListX in a different controller?

**Comment by jonataslaw** [comment]
> @ghprod I am using Get 2.13.1
> 
> This is what I am trying to do
> 
> ```
> class GroupController extends RxController
> {
>   final Rx<Object> _rxGroup;
> 
>   GroupModel get group => _rxGroup.value;
> 
>   GroupController(GroupModel group) : _rxGroup = group.obs;
>   
>   @override
>   void onInit(){
>     final GroupListController groupListController = Get.find<GroupListController>();
>     ever(groupListController.groupList, onGroupListChange);
>     super.onInit();
>   }
> 
>   void onGroupListChange(dynamic value)
>   {
>     print(value); //prints null
>     final GroupListController groupListController = Get.find<GroupListController>();
>     final GroupModel newValue = groupListController.groupList.value?.firstWhere((element) => element.id == group.id);
>     if(newValue != null)
>       _rxGroup.value = newValue ;
>   }
> }
> ```
> 
> Which I now works by finding the controller again, but I would like to just use the injected value if possible.
> 
> **Question**
> 
> If my GroupController is deleted does the callback keeps existing since I am using an ever on a ListX in a different controller?
> 
> Just tested it, and it will keep existing. Any way I can fix that? Since I do not get a reference to a listner I cannot close it in the controller's onClose()

All workers have conditions, where you can set conditions for them to stop triggering events.

**Comment by michael-ottink** [comment]
Aah yes I noticed those but they will stay in memory right? I'll use the bool for now thanks!
