### ISSUE TITLE
initialBinding does not work with namedRoutes

### ISSUE THREAD

**Issue by GustavoLofrano** [jonataslaw/get#245]
`class SplashPage extends StatelessWidget {
  @override
  Widget build(context) {
    return BaseView(
      child: FutureBuilder(
        future: Get.find<AppController>().loading(),
        builder: (_, snapshot) {
          if (!snapshot.hasData)
            return Center(
              child: CircularProgressIndicator(),
            );
          return Container();
        },
      ),
    );
  }
}
class InitialBinding implements Bindings {
  @override
  void dependencies() {
    Get.put(AppController());
  }
}
`

![image](https://user-images.githubusercontent.com/36713355/84683740-0d8d7a00-af0e-11ea-8589-fae43313d8fe.png)

**Comment by jonataslaw** [comment]
I don't think you need Bindings or FutureBuilder for what you're doing, you could just do that:
on your AppController:

bool hasData = false;
onInit() => loading();

loading()async{
final data = await Api.call();
hasData = true; 
update();
}



 GetBuilder<AppController>(
              init: AppController(),
              builder: (snapshot) {
                if (!snapshot.hasData)
                  return Center(
                    child: CircularProgressIndicator(),
                  );
                return Container();
              },
            ),

**Comment by GustavoLofrano** [comment]
With this way of doing the Controller you have to extend the GetController, correct?

**Comment by jonataslaw** [comment]
> With this way of doing the Controller you have to extend the GetController, correct?

Yes,  extending GetController will cause the event declared in "onInit" to be called when the controller enters memory.
