### ISSUE TITLE
Problema ao utilizar bindings em uma pagina que contenha tabs

### ISSUE THREAD

**Issue by Denilson-source** [jonataslaw/get#246]
```dart
return obx(() {
      return CircularCheckBox(
        value: CadastroTabController.to.termosAceitos.value,
        onChanged: CadastroTabController.to.changeTermos,
        activeColor: ColorUtil.hexToColor(AppColors.primary),
      );
    });
```
eu tenho esse checkbox em uma das tabs, a primeira vez que eu entro na tab tudo funciona normalmente, porem ao sair da tab quando volto nela e tento interagir com o checkbox é lançada essa exception.

> [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4180 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
E/flutter (11728): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (11728): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (11728): #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4180:12)
E/flutter (11728): #3      Obxx.build.<anonymous closure> (package:get/src/rx/rx_obx.dart:18:63)
E/flutter (11728): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (11728): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (11728): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (11728): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (11728): #8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (11728): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (11728): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (11728): #11     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (11728): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (11728): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (11728): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (11728): #15     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (11728): #16     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (11728): #17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (11728): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (11728): #19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (11728): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

o erro ocorre somente quando eu observo o valor, se eu por exemplo tirar o check box e mudar o valor com outro botao, sem usar esse valor a exception nao é lançada.

talvez eu esteja usando o bindings de forma errada, tentei usar um GetX<> pra instanciar o controller diretamente na tab, quando eu saio da tab o controller é destruido, porem quando eu volto nao é criada uma nova instancia.

**Comment by jonataslaw** [comment]
Isso acontece porque suas tabs estão sendo descartadas, e o smartManagement observa em tempo real o uso de controllers. Você tem duas formas de contornar isso:
1- KeepAlive nas tabs pra garantir que elas continuem na memória
2- Você pode usar no GetMaterialApp
smartManagement: SmartManagement.keepFactory. 

Dessa forma o controlador vai ser descartado, mas a "forma" de criação dele vai ser mantida, no entanto essa api não é recomendada usar com Bindings, você teria que usar o GetX/GetBuilder pra inicializar esse controller. 

3- Inicializar o controller no widget pai das tabs, e não dentro de uma delas, talvez a opção mais adequada.

**Comment by Denilson-source** [comment]
A opçao 1 funcionou. Na 3 vc diz inicializar o controller no bindings ou pelo GetX? eu tentei pelos dois, no bindigs tanto com lazyPut quanto put ainda geram a exception, e com o GetX ele ocorre o problema de destruir quando eu saiu da tab, mas n criar um novo quando eu entro novamente na tab.

**Comment by jonataslaw** [comment]
Seria na própria view, mas se a primeira deu certo, fique nela. Se tu não tiver 10 tabs, ela vai ser a melhor opção. Se tu tiver um monte de tab, ae vai na terceira.

**Comment by Luiggi13** [comment]
@jonataslaw Here you're my switch statement for tabs, maybe someone needs it in the future.

I'm in a page that contains tabs, and the method that call the pages has a switch statement and looks like this and works fine:

```
switch (selectedPage) {
      case 0:
        return GetBuilder(
          init: InfoController(),
          builder: (_) => InfoScreen(),
        );
      case 1:
        return GetBuilder(
          init: ProductController(),
          builder: (_) => ProductScreen(),
        );
      case 2:
        return GetBuilder(
          init: ProfileController(),
          builder: (_) => ProfileScreen(),
        );

        break;
      default:
        return GetBuilder(
          init: InfoController(),
          builder: (_) => InfoScreen(),
        );
    }
```

I hope can helps somebody
