### ISSUE TITLE
how to pass params?

### ISSUE THREAD

**Issue by wesleytoshio** [jonataslaw/get#25]
i need help to pass params for another page.
 ``` dart
Get.toNamed('/view_folder', {title:'page name'} )
```

**Comment by jonataslaw** [comment]
> i need help to pass params for another page.
> 
> ```dart
> Get.toNamed('/view_folder', {title:'page name'} )
> ```

Get.toNamed('page', arguments: {'title': 'page name'});

And you can recover like this:
var args = Get.args(context); // You can put this into the build method

This example of Map you could retrieve like this:
Text(args['title'])

But you don't necessarily need to pass a Map like most libs, you can pass anything through of Get arguments, even a widget or class if you want.
