### ISSUE TITLE
Duration missing as offAll() parameter

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#250]
I am using a Duration.zero for my page transitions

`Get.to(TheProfileView(), duration: Duration.zero);`

but I noticed that the offAll() does not have a duration. So now the transition differs from my Get.to(). Could this be added?

I am using Get 2.13.1 and Flutter 1.17.3

```
  /// It replaces Navigator.pushAndRemoveUntil, but needs no context
  Future<T> offAll<T>(Widget page,
      {RoutePredicate predicate,
      bool opaque = false,
      bool popGesture,
      int id,
      Object arguments,
      Bindings binding,
      bool fullscreenDialog = false,
      Transition transition}) {
    var route = (Route<dynamic> rota) => false;
```

**Comment by jonataslaw** [comment]
Fix on beta 3.0
