### ISSUE TITLE
Should the smartmagement.factory be the default?

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#251]
I am a new flutter user. And I was using smarmanagement.full before, and since I switched to smartmagement.factory my life has been so much better. The controllers being deleted with the widget and putting the controllers in the widget it self is so more intuitive. While it is almost the same as smartmanagement.full.

As a new flutter / get user I would recommend making the smartmanagement.factory the default.

**Comment by jonataslaw** [comment]
I can recommend using it without Bindings for beginners. The biggest problem with using keepFactory is that it is not compatible with multiple bindings. When only one Binding is used it is really easy and simple.
