### ISSUE TITLE
Get pushing unknown route on stack when directly accessing urls on web

### ISSUE THREAD

**Issue by arthurpiccoli** [jonataslaw/get#252]
Get is pushing an unknown route in the middle of the stack. It occurs when directly accessing the app using a dynamic url on a new chrome tab.

**To Reproduce**
If you have the following route structure: `/foo/:id/bar`
And access the app with the following link: `host/#/foo/123/bar`, the resulting navigator stack will be:
- HomeScreen (/)
- UnknownRoute (/foo which doesn't exists)
- FooScreen (/foo/:id)
- BarScreen (/foo/:id/bar)

**Expected behavior**
Get should check when pushing screens to the stack if they have the `/route/:id` format to avoid pushing non existing routes.

**Flutter Version:**
1.18.0-11.1.pre

**Get Version:**
2.13.1

**Comment by jonataslaw** [comment]
Please, update get version and use getPages rather namedRoutes.

**Comment by hsnbsst** [comment]
this problem still persists
