### ISSUE TITLE
Missing method

### ISSUE THREAD

**Issue by rguisando** [jonataslaw/get#254]
Hi,

Is "Get.delete" been deprecated?
It's missing now from the last update.

**Comment by jonataslaw** [comment]
In the last update we separated instance management from route management and state management, and used dart extensions to link them. It seems that I forgot about the delete. I will do an update to add it to GetInterface extensions

You can use GetInstance().delete while the update is not out.

**Comment by michael-ottink** [comment]
I noticed that Get.isRegistered() also has dissapeard.

**Comment by jonataslaw** [comment]
Added on 2.14.0 
Any other method you miss, you can access via:
GetInstance().Method
