### ISSUE TITLE
defaultTransition not working anymore.

### ISSUE THREAD

**Issue by Z3rolive** [jonataslaw/get#256]
**Describe the bug**
defaultransition on GetMaterialApp is not responding to the changes. I was using Transition.cupertino and it worked. I cannot figure out exactly when it stopped working. 

**To Reproduce**
1. Go to GetMaterialApp and set any transition on defaultTransition. 

**Expected behavior**
Expected navigation transition to be changed throughout the app but no matter the selection, transition is always set on fade in from bottom, i.e flutter default transition.

**Flutter Version:**
1.17.3

**Get Version:**
2.13.1

**Describe on which device you found the bug:**
ex: Pixel 2 [emulator]
Oneplus X [device on release mode]

**Minimal reproduce code**
void main() {
  runApp(
    GetMaterialApp(
      defaultTransition: Transition.cupertino, //any
      initialRoute: '/',
      namedRoutes: {
        '/': GetRoute(page: MyHomePage()),
        '/second': GetRoute(page: Second()),
        '/third': GetRoute(page: Third(),transition: Transition.cupertino);
      },
    )
  );
}

**Comment by LaoHuan** [comment]
me too

**Comment by jonataslaw** [comment]
Fix on 2.14.0
