### ISSUE TITLE
a dropdown on Bottomsheet is not rebuild

### ISSUE THREAD

**Issue by jemariads** [jonataslaw/get#257]
Hi,

I was created a dropdown on bottomsheet use get with getcontroller & getbuilder, but when I selected dropdownitem, the value was changed but the dropdown was not rebuilded. but when I used that dropdown on the page, everything just work fine. is it a bug?

thank you

**Comment by jonataslaw** [comment]
Flutter does not reconstruct all children of a widget, so you have two options:
1- Use dropdown outside the modal.
2- Encapsulate the widget you want to be changed, and not the modal by a GetBuilder.

To find out if it is a bug or not is simple. insert a print in your GetBuilder and see if it is being called. If it was called, it is not a bug, if it was not called, there would be a bug.

```dart
GetBuilder<Controller>(
builder:(_){
print("GetBuilder rebuild");
```
