### ISSUE TITLE
Get is binding controllers to the wrong route when directly accessing an url

### ISSUE THREAD

**Issue by arthurpiccoli** [jonataslaw/get#258]
**Describe the bug**
In Flutter Web when directly accessing a url through a new chrome tab, Get is binding all controllers to `/` route.

**To Reproduce**
If you have the following route structure: `/foo/:id`
And you have the following bindings:
`/` -> HomeBindings -> HomeController
`/foo/:id` -> FooBindings -> FooController

And access the app with the following link: `host/#/foo/123`, all the controllers are initiated as usual but when popping back to `/` the FooController will not be close nor removed from memory.

Upon further research I found out that when Get calls removeDependencyByRoute, the routesKey Map was registered like so:
`{HomeController: /, FooController: /}` instead of `{HomeController: /, FooController: /foo/123}` as it would be if `/foo/123` was accessing within the app not externally through an url.

**Expected behavior**
Get should register the controllers to their proper routes.

**Flutter Version:**
1.18.0-11.1.pre

**Get Version:**
2.13.1

**Comment by jonataslaw** [comment]
Please, use 'getPages' rather 'namedRoutes'
The migration is very fast, you just need to change the Map for a List and put the name of the route inside "name '.
This will likely solve your problem.
