### ISSUE TITLE
FocusNode

### ISSUE THREAD

**Issue by OptionSistemas** [jonataslaw/get#259]
The problem is in requestFocus.

FocusScope.of(Get.focusScope.context).requestFocus(focus); **work**
  
Get.focusScope.requestFocus(focus); **not work**

**Flutter Version:**
1.17.2

**Get Version:**
2.13.1

**Describe on which device you found the bug:**
ex: Android Emulator

**Comment by jonataslaw** [comment]
I think you should use:
`focus.requestFocus();`
