### ISSUE TITLE
on master channel even on ^1.12.0-dev version when add this package to pubspec.yaml i got below error but stable channel works well

### ISSUE THREAD

**Issue by farzintava** [jonataslaw/get#26]
Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:279:8: Error: The method
'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.   
  void install(OverlayEntry insertionPoint) {
       ^
/C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install() {
       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:289:18: Error: Too many positionalarguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/getroute_cupertino.dart:232:9: Error: No named     
parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments    
don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:compileFlutterBuildDebug'.
> Cannot write to file 'C:\flutter' specified for property 'outputFiles' as it is a directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         4.5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jonataslaw** [comment]
> Compiler message:
> /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:279:8: Error: The method
> 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
> void install(OverlayEntry insertionPoint) {
> ^
> /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> void install() {
> ^
> /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:289:18: Error: Too many positionalarguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
> super.install(insertionPoint);
> ^
> /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/getroute_cupertino.dart:232:9: Error: No named
> parameter with the name 'animation'.
> animation: animation,
> ^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments
> don't match.
> CupertinoFullscreenDialogTransition({
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   A problem was found with the configuration of task ':app:compileFlutterBuildDebug'.
> 
> > Cannot write to file 'C:\flutter' specified for property 'outputFiles' as it is a directory.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done 4.5s
> Exception: Gradle task assembleDebug failed with exit code 1

Which version of Master are you using?
It has been over 2 weeks since they removed the mandatory parameter for OverlayRoute.
Try the flutter upgrade to upgrade your version from the master.
If the problem persists, it means that they have made a severe rollback that will affect even the Dev Branch (I'm using it right now, with the Dev version of Get), but I haven't seen any of that in recent commits.
Let me know if the problem persists after the update.

**Comment by farzintava** [comment]
> > Compiler message:
> > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:279:8: Error: The method
> > 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
> > void install(OverlayEntry insertionPoint) {
> > ^
> > /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> > void install() {
> > ^
> > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:289:18: Error: Too many positionalarguments: 0 allowed, but 1 found.
> > Try removing the extra positional arguments.
> > super.install(insertionPoint);
> > ^
> > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/getroute_cupertino.dart:232:9: Error: No named
> > parameter with the name 'animation'.
> > animation: animation,
> > ^^^^^^^^^
> > /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments
> > don't match.
> > CupertinoFullscreenDialogTransition({
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   A problem was found with the configuration of task ':app:compileFlutterBuildDebug'.
> > 
> > > Cannot write to file 'C:\flutter' specified for property 'outputFiles' as it is a directory.
> > 
> > 
> > 
> > * Try:
> >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > * Get more help at https://help.gradle.org
> > 
> > BUILD FAILED in 3s
> > Running Gradle task 'assembleDebug'...
> > Running Gradle task 'assembleDebug'... Done 4.5s
> > Exception: Gradle task assembleDebug failed with exit code 1
> 
> Which version of Master are you using?
> It has been over 2 weeks since they removed the mandatory parameter for OverlayRoute.
> Try the `flutter upgrade` to upgrade your version from the master.
> If the problem persists, it means that they have made a severe rollback that will affect even the Dev Branch (I'm using it right now, with the Dev version of Get), but I haven't seen any of that in recent commits.
> Let me know if the problem persists after the update.

I was try the Dev branch and update flutter but problem still presists.

**Comment by jonataslaw** [comment]
> > > Compiler message:
> > > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:279:8: Error: The method
> > > 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
> > > void install(OverlayEntry insertionPoint) {
> > > ^
> > > /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> > > void install() {
> > > ^
> > > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:289:18: Error: Too many positionalarguments: 0 allowed, but 1 found.
> > > Try removing the extra positional arguments.
> > > super.install(insertionPoint);
> > > ^
> > > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/getroute_cupertino.dart:232:9: Error: No named
> > > parameter with the name 'animation'.
> > > animation: animation,
> > > ^^^^^^^^^
> > > /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments
> > > don't match.
> > > CupertinoFullscreenDialogTransition({
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > FAILURE: Build failed with an exception.
> > > 
> > > * What went wrong:
> > >   A problem was found with the configuration of task ':app:compileFlutterBuildDebug'.
> > > 
> > > > Cannot write to file 'C:\flutter' specified for property 'outputFiles' as it is a directory.
> > > 
> > > 
> > > 
> > > * Try:
> > >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > > * Get more help at https://help.gradle.org
> > > 
> > > BUILD FAILED in 3s
> > > Running Gradle task 'assembleDebug'...
> > > Running Gradle task 'assembleDebug'... Done 4.5s
> > > Exception: Gradle task assembleDebug failed with exit code 1
> > 
> > 
> > Which version of Master are you using?
> > It has been over 2 weeks since they removed the mandatory parameter for OverlayRoute.
> > Try the `flutter upgrade` to upgrade your version from the master.
> > If the problem persists, it means that they have made a severe rollback that will affect even the Dev Branch (I'm using it right now, with the Dev version of Get), but I haven't seen any of that in recent commits.
> > Let me know if the problem persists after the update.
> 
> I was try the Dev branch and update flutter but problem still presists.



> > > Compiler message:
> > > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:279:8: Error: The method
> > > 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
> > > void install(OverlayEntry insertionPoint) {
> > > ^
> > > /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> > > void install() {
> > > ^
> > > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/snack_route.dart:289:18: Error: Too many positionalarguments: 0 allowed, but 1 found.
> > > Try removing the extra positional arguments.
> > > super.install(insertionPoint);
> > > ^
> > > /C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/lib/src/getroute_cupertino.dart:232:9: Error: No named
> > > parameter with the name 'animation'.
> > > animation: animation,
> > > ^^^^^^^^^
> > > /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments
> > > don't match.
> > > CupertinoFullscreenDialogTransition({
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > FAILURE: Build failed with an exception.
> > > 
> > > * What went wrong:
> > >   A problem was found with the configuration of task ':app:compileFlutterBuildDebug'.
> > > 
> > > > Cannot write to file 'C:\flutter' specified for property 'outputFiles' as it is a directory.
> > > 
> > > 
> > > 
> > > * Try:
> > >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > > * Get more help at https://help.gradle.org
> > > 
> > > BUILD FAILED in 3s
> > > Running Gradle task 'assembleDebug'...
> > > Running Gradle task 'assembleDebug'... Done 4.5s
> > > Exception: Gradle task assembleDebug failed with exit code 1
> > 
> > 
> > Which version of Master are you using?
> > It has been over 2 weeks since they removed the mandatory parameter for OverlayRoute.
> > Try the `flutter upgrade` to upgrade your version from the master.
> > If the problem persists, it means that they have made a severe rollback that will affect even the Dev Branch (I'm using it right now, with the Dev version of Get), but I haven't seen any of that in recent commits.
> > Let me know if the problem persists after the update.
> 
> I was try the Dev branch and update flutter but problem still presists.

I just saw it in the first comment log, and it says that you are trying to use the stable version with the flutter channel dev:

`/C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-1.11.1/ <--- stable`

If you are using the dev/master channel of Flutter, you must insert it in your pubspec
get: ^1.12.0-dev

If you are trying to use this in a previously installed application, you must use
`flutter clean`
To clean up the remnants of the old version of the device/emulator

**Comment by jonataslaw** [comment]
Tested today on the 3 branches (Stable / Beta / Dev), on Android, iOS and the web, and everything works fine. Apparently, you changed the version number in your pubspec.
If you have any other problems or questions, don't hesitate to open another issue.

**Comment by alereisan** [comment]
@jonataslaw I am using Flutter (Channel master, v1.18.1-pre.20, on Mac OS X 10.14.6 18G3020, locale de-CH) 

I see the exact same errors as in the first post when starting the app with flutter run.

@farzintava did you find a solution?

**Comment by jonataslaw** [comment]
> @jonataslaw I am using Flutter (Channel master, v1.18.1-pre.20, on Mac OS X 10.14.6 18G3020, locale de-CH)
> 
> I see the exact same errors as in the first post when starting the app with flutter run.
> 
> @farzintava did you find a solution?



> @jonataslaw I am using Flutter (Channel master, v1.18.1-pre.20, on Mac OS X 10.14.6 18G3020, locale de-CH)
> 
> I see the exact same errors as in the first post when starting the app with flutter run.
> 
> @farzintava did you find a solution?

Do you is using 1.14.1-dev version ?

**Comment by farzintava** [comment]
> @jonataslaw I am using Flutter (Channel master, v1.18.1-pre.20, on Mac OS X 10.14.6 18G3020, locale de-CH)
> 
> I see the exact same errors as in the first post when starting the app with flutter run.
> 
> @farzintava did you find a solution?

try flutter clean
