### ISSUE TITLE
routingCallback to open dialog ->  Failed assertion: line 3321 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by mistyn8** [jonataslaw/get#262]
**Describe the bug**
Routing Call back to open a dialog, results in 
```Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3321 pos 12: '!_debugLocked': is not true.```

**To Reproduce**
```
routingCallback: (routing) {
      print('routing callback ${routing.current}');
      if (routing.current == '/second') {
        Get.defaultDialog(
          title: 'Hi',
          middleText: 'Default Dialog',
        );
      }
    },
```
Navigating to the /second  named route, routing callback executes but trying to open a dialog or snackbar causes an error.

**Expected behavior**
Navigating to the /second  named route open a dialog..

**Flutter Version:**
Flutter (Channel dev, 1.20.0-0.0.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-GB)

**Get Version:**
2.14.1

**Describe on which device you found the bug:**
Samsung Galaxy s5

PS the example code has ```routingCallback: (route) {``` but then uses ```routing.current ```

**Comment by mistyn8** [comment]
Tried with 
```Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18363.900], locale en-GB)```
too same issue.

**Comment by jonataslaw** [comment]
This is not just for Get. When you have 2 events competing for the build method, you must assign a postframe to the overlay, as it will appear after the screen is rendered

```dart
 routingCallback: (routing) {
        print('routing callback ${routing.current}');
        if (routing.current == '/second' && !routing.isDialog) {
          SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
            Get.defaultDialog(
              title: 'Hi',
              middleText: 'Default Dialog',
            );
          });
        }
      },
```

**Comment by mistyn8** [comment]
Thank you kindly.. I'll try and create a pr to update the documentation at "Create a MiddleWare class"

**Comment by jonataslaw** [comment]
I understand, but if it wasn't a dialog you could do it exactly as it is in the documentation, but the problem with the dialog is that it will be called before the build, since the middleware is called before the route, so you need to wrap it in a postframecallback, for all other situations this should work without needing it (snackbars and bottomsheets also need it, the snackbar will probably just set instantInit = false should solve)

**Comment by mistyn8** [comment]
Not sure if I'm missing something else.. as I can't close the dialogue by clicking outside? 

 [CLOSE DIALOG] dialog
I/flutter ( 1654): routing callback /second
I/flutter ( 1654): dialog false
I/flutter ( 1654): [OPEN DIALOG] dialog
I/flutter ( 1654): routing callback dialog
I/flutter ( 1654): dialog true

**Comment by mistyn8** [comment]
Is this the correct approach?

```routingCallback: (routing) {
      print('routing callback ${routing.current}');
      print('dialog ${routing.isDialog}');
      print('back${routing.isBack}');
      if (routing.current == '/second' && !routing.isDialog && !routing.isBack) {
        SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
          Get.defaultDialog(
            title: 'Hi',
            middleText: 'Default Dialog',
            textCancel: 'close',
            textConfirm: 'cancel',
            onConfirm: () {
              print('ok');
              Get.back();
            },            
            onCancel: () => print('cancel'),
          );
        });
      }
    },```

**Comment by MrCsabaToth** [comment]
`WidgetsBinding.instance.addPostFrameCallback` helped me
