### ISSUE TITLE
Less opinionated form of Get?

### ISSUE THREAD

**Issue by isaiahtaylor** [jonataslaw/get#267]
**Is your feature request related to a problem? Please describe.**
I'm primarily interested in Get for the easy dialogs and `Get.back()` navigation in those dialogs. I'm not quite ready for "not using StatefulWidget" and the other things this library provides. Also, I'm unsure of the effects that switching from a MaterialApp to a GetMaterialApp has had on my app. For instance, are exceptions handled differently now? I keep seeing "another exception has occured" instead of a full stack trace. I'm not sure if that's related? Also, I'm unsure how that switch is affecting analytics plugins and other pre-existing routing.

**Describe the solution you'd like**
Instructions in the documentation on how to pick and choose certain parts of the functionality (like dialogs) without changing the fundamentals of how my application works. 

I think this will help a lot with adoption!

**Comment by jonataslaw** [comment]
1- As explained in the documentation, only the imported functions are compiled, so if you don't use the state manager or anything else, it won't make any difference to you, no line of code from the state manager will be compiled into your application.
2- "are exceptions handled differently now?" Get does not change the structure of Flutter in any way, there is no possibility that Get will interfere with exception handling in any way. GetMaterialApp is just a preconfigured MaterialApp for dynamic routes, if you don't want to use dynamic routes, just add the Get key to your navigatorKey, and you're done. This is also in the documentation:
https://github.com/jonataslaw/get#other-advanced-apis-and-manual-configurations
3- "without changing the fundamentals of how my application works." get offers a range of APIs not supported by Flutter, such as knowing when a snackbar is open, triggering specific actions when a dialog or page is opened (important if you have some kind of analytics in your application to check the most accessed pages). Get does not switch anything from Flutter, at least nothing that is not problematic, like bottomSheets which have a lot of errors, and Get uses its own widget to mitigate this. I don't understand what kind of "fundamentals of how my application works" Get could change. You can look directly at the source code of GetMaterialApp, and you will see that his son is a MaterialApp, and he only manipulates things like the route list to guarantee resources that are not present in Flutter, that's all.

**Comment by isaiahtaylor** [comment]
Thanks so much! That answers my questions perfectly.
