### ISSUE TITLE
Changing locale

### ISSUE THREAD

**Issue by andressade** [jonataslaw/get#268]
I can’t figure out how to change locale in GetMaterialApp. 
As I’m understand GetMaterialApp shouldn’t wrapped with any widget or builder? How then it’s possible to switch locale in app?

**Comment by jonataslaw** [comment]
I'm not sure about the stable version, but the development version I'm developing has the property "Get.changeLocale (Locale)".
you can currently change and use something like Get.restartApp (), but we will do that better in the next major update
