### ISSUE TITLE
Allow to load resource from AssetBundle without BuildContext

### ISSUE THREAD

**Issue by camillo777** [jonataslaw/get#27]
Hello, does this package also allows to load resources from AssetBundle without the need of Context?
It could be useful as well!
Currently the only way to load a resource from assets folder needs a BuildContext.

Thank you
Camillo

**Comment by jonataslaw** [comment]
> Hello, does this package also allows to load resources from AssetBundle without the need of Context?
> It could be useful as well!
> Currently the only way to load a resource from assets folder needs a BuildContext.
> 
> Thank you
> Camillo

Have you tried using Get.context instead of context?
It provides the current BuildContext.
If it doesn't work with it, there is probably no way to do it (sometimes, a context is needed that is not linked to the navigation context, which is the case with Get, in which case, there is nothing to do).

**Comment by jonataslaw** [comment]
I will close this because in the new version, Get.context meets all needs of using context outside the tree where this is possible, but if you have another problem or doubt, do not hesitate to open another issue.
