### ISSUE TITLE
NoSuchMethodError: The getter '_updaters' was called on null

### ISSUE THREAD

**Issue by avuenja** [jonataslaw/get#270]
**Describe the bug**
O erro acontece quando navego para uma View, seguindo o Fluxo da Aplicação. Em todas as páginas que chamo acontece isso, mas se eu der um Hot Restart, ele funciona normalmente. :/

**Screenshots**
<img width="375" alt="IMG_9F889800A8E8-1" src="https://user-images.githubusercontent.com/5226773/85213572-7e7dc900-b336-11ea-9c2d-99d2681f8a1d.png">

**Flutter Version:**
Channel stable, v1.17.3, on Mac OS X 10.15.4 19E287, locale en-BR

**Get Version:**
ˆ2.14.1

**Describe on which device you found the bug:**
ex: Iphone 7 - iOS.

**Minimal reproduce code**
Possuo um Binding que inicializa todos os meus Controllers, e chamo no GetMaterialApp.
Por algum motivo, ele informa que o Controller ainda não existe (não foi inicializado).

Não sei se estou realizando algo errado.

AppBindings:
<img width="427" alt="Screen Shot 2020-06-20 at 20 46 03" src="https://user-images.githubusercontent.com/5226773/85213614-1f6c8400-b337-11ea-9bee-67bdd34ae82b.png">

Chamadas nas views:
<img width="374" alt="Screen Shot 2020-06-20 at 20 47 28" src="https://user-images.githubusercontent.com/5226773/85213628-4f1b8c00-b337-11ea-889f-66fdad32ceef.png">

Utilizo diversas chamadas assim em todas as minhas Views. Não sei se estou esquecendo de algo?
Eu gostaria de usar fora do método GetBuilder, mas aí ele não atualiza quando mudo o valor.

**Comment by jonataslaw** [comment]
A página que usa o primeiro GetBuilder está certamente sendo retirada da memória. 
Ahh, não precisa user o UserController.to nesse exemplo não, tu pode usar o 
_.baseFontSize direto, porque ele tá dentro de um GetBuilder. 

Vai no GetMaterialApp e colocar:
smartManagement: SmartManagement.keepFactory, 

e o erro deve desaparecer.

**Comment by avuenja** [comment]
@jonataslaw Muito grato! 
Funcionou mesmo!

Aproveitar, curti muito teu job com o Get! 
Parabéns 🎊

Outra coisa, consigo utilizar sem usar o GetBuilder, como li, ou somente dentro do mesmo?

Mais uma vez, parabéns!

**Comment by jonataslaw** [comment]
Sim, fora da arvore você usa o Controller.to em vez de usar o objeto entregue pelo GetBuilder. 
Bem, já que funcionou, estou fechando essa issue
