### ISSUE TITLE
Docs: Dialogs 

### ISSUE THREAD

**Issue by ghenry** [jonataslaw/get#271]
https://github.com/jonataslaw/get#dialogs

States:

`You can also use Get.generalDialog instead of showGeneralDialog.`

there is no `showGeneralDialog` though.

**Comment by jonataslaw** [comment]
Hi, showGeneralDialog is from Flutter.
Get.generalDialog is a replacement for it.

**Comment by ghenry** [comment]
Apologies, of course!
