### ISSUE TITLE
import 'package:get_state......

### ISSUE THREAD

**Issue by ghenry** [jonataslaw/get#272]
Hi,

Are there any docs that explain when to use `get_state`?

Thanks.

**Comment by Katekko** [comment]
When you sayt get_state you mean statemanagement of get? Cause' you can use RxController

**Comment by bajajsahil** [comment]
Can I use state management of "Get" package instead of "Provider" package? Is there any scenario in which I might find it cumbersome if I replace the Provider package?

**Comment by Katekko** [comment]
> Can I use state management of "Get" package instead of "Provider" package? Is there any scenario in which I might find it cumbersome if I replace the Provider package?

Yes, you can. I guess you will find more easy use GET instead Provider. If you need any help, try my discord server to ask something

https://discord.gg/U5HENYM

**Comment by jonataslaw** [comment]
Please, in the next bug description or feature request, follow the model in the repository. I was not able to understand for sure what you wanted to be clarified, but I believe it is about the use of state managers.
I didn't quite understand your question, but in the link I sent you yesterday and in the documentation there are indications and samples on how to use the state manager.
If possible, when you have a support question, look for related channels for this, such as gitter, discord, stackoverflow.
I understand that the framework is new and there are many doubts about its use, but often inserting them in appropriate places has a faster response than opening an issue, which prioritizes bugs and requests for features, and can hinder anyone looking for a description problem.

**Comment by ghenry** [comment]
Can you add something to the docs to show where the official preferred place is to ask questions? That would be very helpful. Thanks!
