### ISSUE TITLE
How to listen for Firestore changes?

### ISSUE THREAD

**Issue by aytunch** [jonataslaw/get#273]
Is there a way to use getX reactively for state management? Lets say my collection changes in Firestore and I want my UI to react automatically. 
Also are you planning on adding persistence for state management just like hydrated_bloc exists for flutter_bloc? It would be great to continue from where user left off when restarting the app.

**Comment by ghprod** [comment]
I think it depends on the Firebase. As long as they have any stream (ex. `Firebase.onAuthStateChanged`), then we can listen to it using `.obs` and `ever` combo.

Check this example https://github.com/jonataslaw/get/issues/215#issuecomment-641611736

**Comment by michael-ottink** [comment]
Wait the firestore has nothing to do with auth right? It's the same principle tho I gues. You need to have a stream and have your obs value listen to that stream.

```
final int someInt = 5.obs;

YourController(Stream<int> yourStream);

@override
void onInit()
{
  someInt.bindStream(yourStream);
  ever(someInt, (value) => print(someInt));
}
```

I typed this here not in a IDE some probably will have mistakes, but you get the point

**Comment by jonataslaw** [comment]
I think michael-ottink's answer perfectly answers your question.
Just use bind and join the firestore stream with a .obs variable.
Closing it.

**Comment by rakesh4577** [comment]
checkout this method for the stream with firebase, [link](url)
