### ISSUE TITLE
That naming though

### ISSUE THREAD

**Issue by ph55** [jonataslaw/get#274]
Is it only me or name of the package way too generic ?

P.S. Package itself is awesome.

**Comment by Nipodemos** [comment]
we agree with you
@jonataslaw made an issue asking opinons about new name and other things, you can give your idea/suggestion here: https://github.com/jonataslaw/get/issues/238

**Comment by jonataslaw** [comment]
Thanks, there is an issue fixed by me that we discussed just that, the name will be changed to GetX in version 3
