### ISSUE TITLE
Navigation through Get should respect pageTransitionTheme

### ISSUE THREAD

**Issue by itssidhere** [jonataslaw/get#275]
I have been using MaterialApp for navigation and to achieve ZoomPageTransition I was using pageTransitionTheme argument

`pageTransitionsTheme: PageTransitionsTheme(builders: const {
                      TargetPlatform.android: ZoomPageTransitionsBuilder()
                    }))`

Is there any way I can use it with Get ? or I would like Get to respect this property

**Comment by jonataslaw** [comment]
The pages must be defined dynamically, you can add custom transitions in version 3.0 beta.

**Comment by itssidhere** [comment]
@jonataslaw ZoomPageTransition which is default of Android 10 is not exposed and is private . Only the ZoomPageTransitionBuilder is exposed. Can you guide me how to get that specific transition?

**Comment by jonataslaw** [comment]
Add to your route, or defaultRoute on GetMaterialApp:
`transition: Transitions.zoom; // defaultTransition on GetMaterialApp`

**Comment by itssidhere** [comment]
@jonataslaw  I checked it and its behaviour is not similar as Flutter one replicates FADE+ZOOM just like Android 10 transition.

**Comment by itssidhere** [comment]
@jonataslaw  Also Get.to should also have an option to define route just like Get.offUntil.
