### ISSUE TITLE
How to use provider in a controller.

### ISSUE THREAD

**Issue by Kypsis** [jonataslaw/get#276]
The extension you recommend generates code like this with getcontroller snippet:

```
import 'package:get/get.dart';
import 'package:meta/meta.dart';

class MyController extends RxController {

  final MyRepository repository;
  MyController({@required this.repository}) : assert(repository != null);

  final _obj = ''.obs;
  set obj(value) => this._obj.value = value;
  get obj => this._obj.value;
}
```

How do you actually use the repository methods in the controller? I'm trying to make Firebase work with Get and store the value of fetchAllItems.obs in the controller. 

Below the code from repository:
```
final CollectionReference itemsCollection =
      Firestore.instance.collection("items");

Stream<QuerySnapshot> get fetchAllItems {
    return itemsCollection.snapshots();
  } 
```

**Comment by Kypsis** [comment]
Nevermind, found the answer in example.

**Comment by jonataslaw** [comment]
Glad you found this yourself, sorry for not having responded earlier.
