### ISSUE TITLE
Routing is different in profile and release mode

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#277]
**Describe the bug**
Normal routes are called by their class name in debug mode so `/someclass`. But they are called `/widget` in profile and release mode. I have a feeling this could cause some other issues as well.

**To Reproduce**
Just use a `Get.to(SomeWidget());` in both debug and profile/release mode and look at the difference

**Expected behavior**
I expect the routes to keep their name so I can use that name in some senarios

**Flutter Version:**
1.17.3

**Get Version:**
^2.14.1

**Describe on which device you found the bug:**
Huawei p30 pro

**Comment by jonataslaw** [comment]
This is technically impossible, I mean, there is no chance of that happening.
Please use Flutter clean before any build to remove remnants of old updates.
Everything should work in the same way in release and in debug, if there was a possibility that this was happening, you should open an issue in Flutter, not in the repository, since it is a behavior related to the compilation of Flutter, and not to the operation of lib.

**Comment by michael-ottink** [comment]
I ran this in a new project and also cleaned it. It only happens with smartManagement.full and factory  that's why I thought this is a Get thing. It doesn't happen with onlyBuilder.

**Comment by michael-ottink** [comment]
I ran this in a new project and used flutter clean, and it still happens. It's caused by `print(this.toString().toLowerCase());` which you use to name the routes. The name is different in profile / release mode. Glad it doesn't happen on your end, I will post on the flutter repo about it. I would like to know what version of flutter you are using so I can confirm that this is only happening in 1.17.3 and 1.17.4.

**Comment by jonataslaw** [comment]
I tested it on the master, but give me a break because I’ll see if that’s not an effect of Flutter’s obfuscation.

**Comment by Nipodemos** [comment]
hey, i just tested with this versions:
* Flutter Channel stable, v1.17.4,
* Get: ^2.14.1
i also created a project from scratch after switching to stable channel (i was on master before)

and in release and profile mode it worked normally

**Comment by michael-ottink** [comment]
Did you run a clean inbetween? I noticed that if I don't clean it appears to run normally. I did try it on 1.17.4 as well stange.
