### ISSUE TITLE
What would be the best way to bind a controller which does not have to be called from the widget

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#278]
I have a widget that needs to trigger an audio fragment every 5 seconds.

```
class TheGroupNotificationView extends StatefulWidget {
  static AudioCache player = new AudioCache();
  static const alarmAudioPath = "audio/alerts/beep.wav";

  TheGroupNotificationView();

  @override
  _TheGroupNotificationViewState createState() => _TheGroupNotificationViewState();
}

class _TheGroupNotificationViewState extends State<TheGroupNotificationView> {
  Timer timer;

  @override
  void initState() {
    super.initState();
    _onTick();
    timer = Timer.periodic(Duration(seconds: 5), (Timer t) => _onTick());
  }

  void _onTick() {
    TheGroupNotificationView.player.play(TheGroupNotificationView.alarmAudioPath);
  }

  @override
  void dispose() {
    timer?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Text('the build method doesnt matter');
  }
}
```

The timer needs to be disposed when the widget is disposed. How would I make this statefull widget into a stateless widget by using a GetController or a RxController?

Since this has nothing to do with building the widget, and needs to be bound to the widgets lifetime. I have no clue how to do this. So it's mostly about the timer, not so much about the audio.

**Comment by Katekko** [comment]
You can use simples as that

```
class TimerController extends RxController {
  static AudioCache player = new AudioCache();
  static const alarmAudioPath = "audio/alerts/beep.wav";

  @override
  void onInit() {
    super.onInit();
    _onTick();
    timer = Timer.periodic(Duration(seconds: 5), (Timer t) => _onTick());
  }

  void _onTick() {
    TheGroupNotificationView.player.play(
      TheGroupNotificationView.alarmAudioPath,
    );
  }

  @override
  void onClose() {
    timer?.cancel();
    super.dispose();
  }
}
```

The RxController has lifetime methods too.
When o call this RxController, the onInit will be called and when the controller is no longer needed the onClose will be called. (There is more life time methods)

So you can create a RxController like that and use in your widget or whatever you want (in the man you can use too

**Comment by jonataslaw** [comment]
@Katekko answered your question.
Read about the lifecycle of controllers in the documentation, onInit and onClose can most often replace initState and dispose.
As it is a support question, already answered, I am closing this.

**Comment by michael-ottink** [comment]
I'll move these type of questions to stackoverflow. My b. 

But just to be clear it was not about how to make the controller but on how to put it.
