### ISSUE TITLE
Controllers are getting closed differently in debug mode than in profile / release mode

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#279]
**Describe the bug / To Reproduce**
I have a controller which I lazyput in my home page widget. Then I navigate to some widget and call get.back() then I navigate to it again. 

This is no problem in debug mode, the controller will be there working correctly. But in profile and release mode I get the following error as shown in the image below

```
I/flutter (29240): ══╡  ╞══════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (29240): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I'm not sure but it might be having a connection to my previous post https://github.com/jonataslaw/get/issues/277#issue-643393573

**Expected behavior**
The debug mode seems to be working correctly to me. 

**Screenshots**
![image](https://user-images.githubusercontent.com/15832303/85343093-4ddf9000-b4ec-11ea-97be-06711f8c9029.png)

**Flutter Version:**
1.17.3

**Get Version:**
get: ^2.14.1

**Describe on which device you found the bug:**
Hauwei p30 pro

**Minimal reproduce code**

```
void main() {
  runApp(App());
}

class App extends StatelessWidget {
  App();

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      home: TestWidget(),
    );
  }
}

class TestWidget extends StatelessWidget {

  TestWidget()
  {
    Get.lazyPut<SomeController>(() => SomeController('Back'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: RaisedButton(child: Text('go to some page'), onPressed: () => Get.to(SomePage()))),
    );
  }
}

class SomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            FractionallySizedBox(
              widthFactor: 0.7,
              child: Text('Navigate back from here and then navigate to this page again in profile mode' +
              'and notice how the dependencies are no longer there in profile mode'),
            ),
            RaisedButton(
              child: Text(Get.find<SomeController>().buttonText),
              onPressed: () => Get.back(),
            ),
          ],
        ),
      ),
    );
  }
}

class SomeController extends GetController{
  final String buttonText;

  SomeController(this.buttonText);
}

```

**Comment by michael-ottink** [comment]
I tagged the wrong post. I mean it could have some connection to https://github.com/jonataslaw/get/issues/277#issue-643393573

**Comment by jonataslaw** [comment]
tried to reproduce in debug mode, tested in profile, and tested in release, and both are the same.
If that were possible (which I believe is not), you should open an issue in Flutter's git, since compilation is not dealt with in that lib.
But maybe there is an old cache that may be returning an old build, use flutter clean before building any projects.

There is a log of your audio right after the Get log, so this is definitely not a bug or problem related to Get.

**Comment by michael-ottink** [comment]
I ran this in a new project and also cleaned it. It only happens with smartManagement.full and factory  that's why I thought this is a Get thing. It doesn't happen with onlyBuilder.

**Comment by michael-ottink** [comment]
When I remove the `Get.find<SomeController>().buttonText` it stops from happening in profile mode. I'm not making this up.

**Comment by jonataslaw** [comment]
"onlyBuilders" will remove smartManagement by routes, and will rely on the disposition of each widget. When you navigate through a screen without a named route, the name of the widget is used as a reference for smartManagement, which is why a widget is appearing in the print. This can be a protection of the AOT to prevent people from knowing the original name of the classes, they are doing tests to make sure of it.

**Comment by michael-ottink** [comment]
I have a fix in place. I'm only bringing this up for other users. I hope they can fix it so this doesn't happen anymore.

**Comment by michael-ottink** [comment]
I have a fix in place. I just posted this so that you are notified of the problem and it get's fixed for other people. I also made a post on the flutter repo. I hope other people can soon run the script posted above in profile mode without any problems.

**Comment by Nipodemos** [comment]
link the issue you made on flutter 😄 i would like to follow that issue

**Comment by michael-ottink** [comment]
Here is is :) https://github.com/flutter/flutter/issues/60075#issuecomment-648767965
