### ISSUE TITLE
Close all dialogs

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#281]
I've had some senarios where I wanted to close all dialogs. I used a while loop to do this together with the Get.isDialogOpen. But I gues this is not that elegant. Could we have it implemented in Get? So Get.closeAllDialogs() ? Let me know what you think :)

**Comment by jonataslaw** [comment]
Why don't you use Get.until for this?
This is not documented, but let's say you have a base on Navigator.popUntil, you should know that it closes all routes until a bool function returns true.
Get already has isDialogOpen, snackbarOpen and etc, I think it would be even intuitive for you to try something like:

```dart
 Get.until((route) => Get.isDialogOpen);
```

**Comment by michael-ottink** [comment]
I love that! Thanks I will use that.
