### ISSUE TITLE
MVC Pattern and Repositories

### ISSUE THREAD

**Issue by ghenry** [jonataslaw/get#283]
Hi all,

Coming from web MVC and Elixir/Phoenix, in relation to login with a 3rd party authentication system, is the pattern thin controllers and fat models in general as per the example app?

Following on from #223 I'm unsure where my logic for CRUD auth tokens should live and my AppAuth OAuth2 dance. In my head I have that this lives in a Model and is called from my Auth Controller , but what lives in the UserRepository? Is that just for mapping user data to a user object?

Ultimately, in my `ever` call I am setting the isLoggedIn obs to true if I load a non-expired refresh token from flutter secure storage. 

Thanks.

**Comment by ghenry** [comment]
This recommended? https://www.c-sharpcorner.com/UploadFile/3d39b4/crud-using-the-repository-pattern-in-mvc/

**Comment by jonataslaw** [comment]
This was not done by me, but it matches the VsCode snippet extension.
It is in another language, I think Google translator will be necessary to understand:

https://translate.google.com/translate?hl=&sl=pt&tl=en&u=https%3A%2F%2Fkauemurakami.github.io%2Fgetx_pattern%2F

**Comment by ghenry** [comment]
Awesome, that's exactly the type of structure and example I was looking for. Tanks @jonataslaw

**Comment by jonataslaw** [comment]
You're welcome
