### ISSUE TITLE
[Proposal] Optional debugging messages

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/get#30]
It looks like you are currently printing debug messages (at least on the RouteObserver).
Can you make it an optional setting to be able to turn it off? 

Thanks!

**Comment by jonataslaw** [comment]
> It looks like you are currently printing debug messages (at least on the RouteObserver).
> Can you make it an optional setting to be able to turn it off?
> 
> Thanks!

I will add this feature soon when Get.settings is ready. Thank you for reminding me of this.

**Comment by jonataslaw** [comment]
Added on lastest version

https://github.com/jonataslaw/get/commit/d147007d3a2b7cfb5fdeceda5ada8e88f425dc51
