### ISSUE TITLE
 NoSuchMethodError: The method 'pushReplacement' was called on null.

### ISSUE THREAD

**Issue by fixer112** [jonataslaw/get#33]
Why am i getting this error? is it becase i already have flutter named route defined?

**Comment by jonataslaw** [comment]
> Why am i getting this error? is it becase i already have flutter named route defined?

Please attach your code snippet, your routes class, and your version of Flutter.
Without further details it will not be possible to proceed with your issue.

**Comment by jonataslaw** [comment]
You either forgot to add Get.key, or this error is not related to the plugin.
Anyway, without the information provided, it is impossible to have a minimal reproduction of the problem. Closed that.
If you encounter problems with the plugin, do not hesitate to open another issue, reporting the error, a code snippet, and your current version of the plugin and Flutter.

**Comment by fixer112** [comment]
@jonataslaw you are very correct, silly mistake, forgot to add Get.key
