### ISSUE TITLE
Transition.material?

### ISSUE THREAD

**Issue by VictorUvarov** [jonataslaw/get#36]
The default transition seems to be fade. 
- Are there plans to support the default material transition? 
- Or does it have a different transition name?

**Comment by jonataslaw** [comment]
> The default transition seems to be fade.
> 
> * Are there plans to support the default material transition?
> * Or does it have a different transition name?

Hi, the default transition is always the native transition.
If you use iOS and do not enter any transitions, Transitions.cupertino will be used. If you use Android, Transitions.fade will be used.
Transitions.fade uses the Material theme transition available in the framework, so unless you are using an old version, which does not support GetPlatform, I don't understand where your question is.

**Comment by VictorUvarov** [comment]
Alright, I didn't know fade was the default transition. Seemed different to me. Thanks for the response.
