### ISSUE TITLE
Snack bar message should be optional

### ISSUE THREAD

**Issue by VictorUvarov** [jonataslaw/get#37]
Currently the SnackBar message is required, which leads to a large sized SnackBar. Sometimes a small quick message is all I want to show.

**Comment by jonataslaw** [comment]
> Currently the SnackBar message is required, which leads to a large sized SnackBar. Sometimes a small quick message is all I want to show.

Hi, Get.snackbar was designed to have a title and a message. If you want to build a different snackbar, use GetBar().show (don't forget the "show" to have it displayed), and you will have all the customizable details to decide.

Example:

```dart
  GetBar(
          messageText: Text("Anything"),
          duration: Duration(seconds: 3),
        ).show();
```

**Comment by VictorUvarov** [comment]
Thanks didn't know that API existed

**Comment by jonataslaw** [comment]
> Thanks didn't know that API existed

My mistake, there was this documentation and at some point it ended up being removed.
I will include it again in the documentation asap
