### ISSUE TITLE
GetRoute Duration doesn't seem to work

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/get#38]
I'm trying to use custom transitions on named routes:

```
class Router {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case Routes.PriorityHome:
        return GetRoute(
          settings: settings,
          page: PriorityHomeScreen(),
          duration: Duration(milliseconds: 0),
        );
      case Routes.PriorityPatient:
        return GetRoute(
          settings: settings,
          page: PriorityPatientScreen(),
          duration: Duration(milliseconds: 0),
        );
      default:
        return GetRoute(
          settings: settings,
          transition: Transition.fade,
          page: Scaffold(
            body: Center(
              child: Text('No route defined for ${settings.name}'),
            ),
          ),
        );
    }
  }
}

```

My expectation is for no animation to occur (since milliseconds is 0), but it is still happening. 
Changing the value to other values (higher than the default 400 for example) doesn't change anything either

**Comment by jonataslaw** [comment]
This is a known error. In the last update of Flutter to beta / dev / master I had to restructure the whole GetRoute, and one of the sacrificed functions was the duration. In yesterday's update on stable, to keep the same base, I also temporarily removed the support for duration, however, I already found a way around this and it will be released in the next update.

**Comment by jlubeck** [comment]
Nice! Looking forward to it

**Comment by jonataslaw** [comment]
Fix on Lastest version

**Comment by jlubeck** [comment]
You didn't ask, but I confirmed it's working :D
