### ISSUE TITLE
How to use Get with firebase_Analytics ?

### ISSUE THREAD

**Issue by Dangtrungphu** [jonataslaw/get#4]
How can I add firebase_Analytics to my project using Get?

**Comment by jonataslaw** [comment]
> How can I add firebase_Analytics to my project using Get?

I believe there is no problem. Firebase Analytics uses navigatorObservers (a midleware that watches each route navigation), and Get uses a navigatorKey (which inserts Get's navigatorKey in place of the default navigatorKey, allowing currentContext access outside the widgets tree).

If you encounter any problems, you can enter the error log in this issue, but I don't believe there is any problem using both.

**Comment by Dangtrungphu** [comment]
Thank you. I am a new frame flutter, I feel this lib is easy for me. so I still don't know how to use it with Firebase Analytics. Can you give me a specific example?

**Comment by jonataslaw** [comment]
FirebaseAnalytics analytics = FirebaseAnalytics();

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: Get.key,
      home: Home(),
      navigatorObservers: [
        FirebaseAnalyticsObserver(analytics: analytics),
      ],
    );
  }
}
If you have any other questions, or errors, don't hesitate to open another issue.
