### ISSUE TITLE
Is there a way to check which one is the current route?

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/get#41]
I have a navigation bar when I call `Get.toNamed(routeName)` whenever I tap on a button.

But I'd like to prevent that call when the currentRoute is the same as routeName. 

Couldn't find a way to get the current route name except from within the middleware. Would be nice to get an accesor to the current route from Get directly, like `Get.currentRoute` or something

**Comment by jonataslaw** [comment]
class MiddleWare {
  static MiddleWare _instance;

  factory MiddleWare() {
    if (_instance == null) _instance = MiddleWare._();
    return _instance;
  }

  MiddleWare._();

  static Routing _routing;

  static Routing get routing => _routing;

  static observer(Routing rt) {
    _routing = rt;
  }
}

class Foo {
  yourMethod() {
  if(MiddleWare.routing.current == routeName){
  //Made anything
 }
  }
}

**Comment by jlubeck** [comment]
Awesome, thanks

**Comment by esDotDev** [comment]
Couple things:
1. Can't we just get Get.CurrentRoute? Would be much nicer.
2. Why do we have to do this and how does it work... seems like a bizarre solution (just curious)

**Comment by jonataslaw** [comment]
> Couple things:
> 
> 1. Can't we just get Get.CurrentRoute? Would be much nicer. The currently selected page is an important part of global state, should be readily accessible?
> 2. Why do we have to do this (Create a Middleware class)... seems like a bizarre solution (just curious)

Currently Get.currentRoute does the job.
This issue is very old, it is version 1.0 of Get, at that time there were not even 1/3 of the resources that Get has today.

**Comment by esDotDev** [comment]
Ah, my bad. I assumed the list on pub.dev README was exhaustive.

Thanks for the framework, it's really impressive.
