### ISSUE TITLE
Flutter Test

### ISSUE THREAD

**Issue by alfaodin** [jonataslaw/get#42]
First at all very good job, it is a nice plugin. This is not really an issue but I am trying to test a logic service, and this calls to "Get.offNamed", but I could not find a way to mock it or get around it in order to pass my test. Sorry if this is not the best way to ask about this and thank you.

**Comment by jonataslaw** [comment]
You can use the mock test of the Flutter Navigator to test the Get functions. Just replace the corresponding function with that of Get.

https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/navigator_test.dart

A more simplistic approach is to use GetObserver, insert the Routing variable as a global variable, push the route, and receive something by argument (Flutter even uses this approach, they use TestObserver as a kind of GetObserver, and observe the parameter sent by route).

I am creating an easy API to access arguments outside of classes, and this can make your testing easier, as you can test whether the current argument is the one sent, and whether the current route is the first in the stack. This API is undergoing internal testing, and will be made available to the dev branch soon.

Note:
In your test, insert Get.key in your MaterialApp, GetObserver also needs to be there for the second approach, and you need to create a mock with at least 3 routes to test Get.offNamed (if you intend to test whether the last route became the first in the pile and all others have been discarded)
Depending on the level of your tests, you may want to create your own Observer, within it you can expose route.isFirst (passing a Function (bool isFirst) in the constructor, for example) to check if all other routes have left the stack.
I'm sorry for not providing individual tests for each role, I would love to do that, but as I am the sole maintainer of this library, I have focused my time on stability and adding new features. A lot of things required rebuilding from scratch (like snackbars, dialogs, bottomsheets and GetRoute), and I didn't have time to build basic things like testing and documenting all APIs. But if you need help, don't hesitate to comment.

**Comment by evandroneder** [comment]
try add 

TestWidgetsFlutterBinding.ensureInitialized();
Get.testMode = true;
