### ISSUE TITLE
Get Snackbar causes an exception in scheduler library

### ISSUE THREAD

**Issue by Jpec57** [jonataslaw/get#46]
**Describe the bug**
Hi, many thanks for your work !

Unfortunately, while trying to use your Snackbar after an API Call, it raises an exception 
![image](https://user-images.githubusercontent.com/23074039/79849483-d6459580-83c2-11ea-863d-4ff48e35594a.png)
I am simply calling it like the documentation said: 
<img width="503" alt="Capture d’écran 2020-04-21 à 11 26 03" src="https://user-images.githubusercontent.com/23074039/79849544-e5c4de80-83c2-11ea-8850-d5cd61854a59.png">
I've tried to add a blank ThemeData in my MaterialApp Widget but with no success.
Have I done something wrong here ?

**Flutter Version:**
Enter the version of the Flutter you are using
Flutter 1.12.13+hotfix.9

**Get Version:**
Enter the version of the Get you are using
  get: ^1.17.0

**Describe on which device you found the bug:**
Nexus 5X

**Comment by jonataslaw** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> Hi, many thanks for your work !
> 
> Unfortunately, while trying to use your Snackbar after an API Call, it raises an exception
> ![image](https://user-images.githubusercontent.com/23074039/79849483-d6459580-83c2-11ea-863d-4ff48e35594a.png)
> I am simply calling it like the documentation said:
> <img alt="Capture d’écran 2020-04-21 à 11 26 03" width="503" src="https://user-images.githubusercontent.com/23074039/79849544-e5c4de80-83c2-11ea-8850-d5cd61854a59.png">
> I've tried to add a blank ThemeData in my MaterialApp Widget but with no success.
> Have I done something wrong here ?
> 
> **Flutter Version:**
> Enter the version of the Flutter you are using
> Flutter 1.12.13+hotfix.9
> 
> **Get Version:**
> Enter the version of the Get you are using
> get: ^1.17.0
> 
> **Describe on which device you found the bug:**
> Nexus 5X

Hi, thanks for describing this problem. You don't know much about the error with your print, but the iconTheme used to define the font color and the color of the Get.snackbar icon is returning null. Unless Flutter changed something in the last hotfix, that would be impossible to do, because the theme is inherited directly from MaterialApp. Did you add "Get.key" to your MaterialApp? If you forget to add the Get key to your MaterialApp, Get will not receive the context, and will not be able to invoke ThemeData.

**Comment by Jpec57** [comment]
I am really sorry to have bother you with this, I have indeed forgotten to add it... Thank for your answer and reactivity !
