### ISSUE TITLE
How to return multiple pages

### ISSUE THREAD

**Issue by 948911908** [jonataslaw/get#48]
RT
We have a requirement to close the current page and the previous page or pages. Does "get" support

**Comment by jonataslaw** [comment]
Get.offAll(close all previous pages)
Get.close(close number of pages, ex: 3)
Get.until(close all previous pages until the page required). 

All methods for named navigation along with these are in the documentation.

**Comment by 948911908** [comment]
Get.close is satisfied, but it doesn't seem to want to take arguments to the returned page like get.back @jonataslaw

**Comment by jonataslaw** [comment]
> Get.close está satisfeito, mas parece não querer levar argumentos para a página retornada, como get.back @jonataslaw

That's not possible. The Flutter API does not allow data to be sent to another route.

You can do some alternative work with this, it is very ugly, but it is your only solution if you do not want to adopt named routes:

On the page where you want to receive the data:
var data = await Get.to(PageTwo());
print("$data");

on PageTwo:
var data = await Get.to(PageThree());
Get.back(result: data);

on PageThree:
String test = "Test callback";
Get.back(result: test);

**Comment by jonataslaw** [comment]
Closing this because it is not a description of BUG. If you encounter problems with Get, open an issue by filling out the bug-opening form.
