### ISSUE TITLE
Are there plans to support cupertino?

### ISSUE THREAD

**Issue by VictorUvarov** [jonataslaw/get#50]
**Is your feature request related to a problem? Please describe.**
Currently this package only supports material apps. I see ThemeData and MaterialLocalizations being used.

**Describe the solution you'd like**
Check the platform before using things like ThemeData.

**Describe alternatives you've considered**
The solution will probably find all the occurrences of material dependencies and add a platform check there.

**Comment by jonataslaw** [comment]
> **Is your feature request related to a problem? Please describe.**
> Currently this package only supports material apps. I see ThemeData and MaterialLocalizations being used.
> 
> **Describe the solution you'd like**
> Check the platform before using things like ThemeData.
> 
> **Describe alternatives you've considered**
> The solution will probably find all the occurrences of material dependencies and add a platform check there.

This library has full support for the cupertino. Even the swipe to back (popGesture) is present.
All route components are also present, the snackbar follows the Human Guidelines (not even Flutter's own snackbar is not doing this), the routes besides using all Cupertino transitions natively on iOS, still makes it possible to do the same on android.
I definitely think you've looked at lines of code and presuppose that, but no, the package is not Material based, and what you saw was just aliases for some functions like the defaultDialog (which this is only material, and will continue to be ).
Having references to the Material code does not mean that it does not support cupertino, it means that it also supports Material.

If you want to use Get with the native iOS dialog, or any iOS widget that uses context, you can still use Get.context or Get.overlayContext (in the case of modals) to do this.

**Comment by VictorUvarov** [comment]
Okay thank you
