### ISSUE TITLE
Erro ao acessar Get.arguments

### ISSUE THREAD

**Issue by Luccasoli** [jonataslaw/get#51]
Antes de tudo, parabéns pela Lib!
Precisei recentemente abrir um snackbar, mas tive dificuldade excessiva pra realizar uma "tarefa tão simples", e acabei vindo experimentar o Get, que se mostrou bem prático nesse e em todos os outros quesitos de navegação, mas agora estou tendo dificuldades com a passagem de parâmetros com rotas nomeadas em um projeto de estudo. 

Acredito que o codigo que fiz esteja conforme foi exemplificado na documentação.

**Describe the bug**
Tento navegar com Get.toNamed passando um argumento, na tela de destino, ao acessar Get.arguments uma Exceção é lançada.

Erro:
```
The getter 'args' was called on null.
Receiver: null
Tried calling: args
```

**To Reproduce**
1. Clique em um dos items listados na GridView.

**Expected behavior**
Acessar o valor enviado via arguments no widget/tela de destino.

**Flutter Version:**
environment:
  sdk: ">=2.1.0 <3.0.0"
Flutter 1.12.13+hotfix.9

**Get Version:**
get: ^1.17.3

**Describe on which device you found the bug:**
ex: AVD com SDK 21 - Android 5.1.1.

**Minimal reproduce code**
`import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() => runApp(MyApp());

class Routes {
  static const PRODUCT_DETAIL = '/product-detail';
}

class Router {
  static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case '/':
        return GetRoute(
          settings: settings,
          page: ProductsOverviewScreen(),
        );
      case Routes.PRODUCT_DETAIL:
        return GetRoute(
          settings: settings,
          page: ProductDetailsScreen(),
        );
      default:
        return GetRoute(
          settings: settings,
          page: Scaffold(
            body: Center(child: Text('No route defined for ${settings.name}')),
          ),
        );
    }
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: Get.key,
      title: 'Minha Loja',
      theme: ThemeData(
        primarySwatch: Colors.purple,
        accentColor: Colors.deepOrange,
      ),
      initialRoute: '/',
      onGenerateRoute: Router.generateRoute,
    );
  }
}

class ProductsOverviewScreen extends StatelessWidget {
  final List<String> items = ['item 1', 'item 2'];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Minha loja',
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(10.0),
        child: GridView.builder(
            itemCount: items.length,
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
              childAspectRatio: 3 / 2,
              crossAxisSpacing: 10,
              mainAxisSpacing: 10,
            ),
            itemBuilder: (context, i) {
              return InkWell(
                onTap: () {
                  Get.toNamed(Routes.PRODUCT_DETAIL, arguments: items[i]);
                },
                child: Text(
                  items[i],
                ),
              );
            }),
      ),
    );
  }
}

class ProductDetailsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('antes');
    print(Get.arguments);
    print('depois');

    return Scaffold(
      appBar: AppBar(
        title: Text(Get.arguments),
      ),
    );
  }
}
`

**Comment by jonataslaw** [comment]
Para APIs avançadas que usam "onisciência" como argumentos dinamicos, snackbar observer (isSnackbarOpen), dialogObserver e etc, é necessário adicionar o GetObserver, conforme a documentação. 

Seu materialApp tá assim:

```dart
return MaterialApp(
navigatorKey: Get.key,
title: 'Minha Loja',

```
Apenas mude para: 

```dart
return MaterialApp(
navigatorKey: Get.key,
navigatorObservers: [GetObserver()], // Adicione isso aqui
title: 'Minha Loja',
```
E você vai poder acessar os argumentos de qualquer lugar e usar as demais APIs avançadas do Get..

**Comment by Luccasoli** [comment]
Entendi, eu tinha lido só a parte de Send data to named Routes:
Era uma boa ter essa informação nesse tópico também, e valeu pela rápida resposta!

**Comment by Luccasoli** [comment]
@jonataslaw Boa noite, estou tentando fazer novamente isso que você explicou aqui:
`return MaterialApp(
navigatorKey: Get.key,
navigatorObservers: [GetObserver()],`

no get: ^2.5.3 e o flutter: 1.17.1, porém, o mesmo erro acontece,

Vi que agora existe GetMaterialApp, mas pra acessar essa API avançada (Get.arguments) a documentação indica pra fazer dessa maneira que você citou quando me respondeu na primeira vez.

O código que tenho testado:

`import 'package:cinema_app/screens/home_page.dart';
import 'package:cinema_app/screens/movie_details.dart';
import 'package:cinema_app/utils.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Route {
  static GetRouteBase onGenerateRoute(RouteSettings settings) {
    switch (settings.name) {
      case '/':
        return GetRouteBase(
          settings: settings,
          page: HomePage(),
        );
        break;
      case '/MovieDetails':
        return GetRouteBase(
          settings: settings,
          page: MovieDetails(),
        );
      default:
        return GetRouteBase(
          settings: settings,
          page: HomePage(),
        );
    }
  }

  static Map<String, GetRoute> namedRoutes = {
    '/': GetRoute(page: HomePage()),
    '/MovieDetails': GetRoute(page: MovieDetails()),
  };
}

void main(List<String> args) {
  runApp(
    Main(),
  );
}

class Main extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final primaryColor = hexToColor('#4947a7');
    final accentColor = hexToColor('#483785');
    return GetMaterialApp(
      initialRoute: '/',
      namedRoutes: Route.namedRoutes,
      // onGenerateRoute: Route.onGenerateRoute,
      navigatorObservers: [GetObserver()],
      debugShowCheckedModeBanner: false,
      title: 'Cinema App',
      theme: ThemeData(
        primaryColor: primaryColor,
        accentColor: accentColor,
        textTheme: ThemeData().textTheme.copyWith(
              headline6:
                  ThemeData().textTheme.headline6.copyWith(color: accentColor),
              bodyText1:
                  ThemeData().textTheme.bodyText1.copyWith(color: accentColor),
              bodyText2:
                  ThemeData().textTheme.bodyText2.copyWith(color: accentColor),
            ),
      ),
    );
  }
}
`

**Comment by Luccasoli** [comment]
ps: não sei pq o código está indo sem formatação, talvez seja o código extenso... desculpa aí por isso.

**Comment by jonataslaw** [comment]
Nada do que você leu se aplica pra agora, houve um bump de versão 1 pra 2, o que significa mudança na estrutura, broken changes. 
Mas você migrou corretamente as namedRoutes (poderia apagar o resto), 
remova também essa linha:
 `navigatorObservers: [GetObserver()],`
Você não precisa mais observar o navegador. 
Só precisa do GetMaterialApp e da namedRoutes com initialRoute, o resto pode excluir tudo. 
Get.arguments está trabalhando normal, recomendo remover a linha acima e tentar um flutter clean, se não resolver, coloca como vc tá enviando as rotas, porque definitivamente, não tem qualquer razão pra os argumentos não estarem sendo enviados.

**Comment by Luccasoli** [comment]
Pior que ainda não funcionou :/, fiz as correções que você disse, e executeio flutter clean

`
class Route {
  static Map<String, GetRoute> namedRoutes = {
    '/': GetRoute(page: HomePage()),
    '/MovieDetails': GetRoute(page: MovieDetails()),
  };
}
`

`class Main extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: '/',
      namedRoutes: Route.namedRoutes,
      debugShowCheckedModeBanner: false,
      title: 'Cinema App'
    );
  }
}`

Navego assim: `Get.toNamed('/MovieDetails', arguments: movie);`
e no initState da tela MovieDetails tento acessar dessa forma: ` Movie movie = Get.arguments;`

É nesse projeto que estou usando: https://github.com/Luccasoli/flutter_ui_implementations/tree/master/cinema_app

**Comment by jonataslaw** [comment]
Obrigado pelo código de exemplo, foi fixado na versão get: ^2.5.5
Testei e o ID chega corretamente, mas apenas para titulo de aviso, você deve envolver tudo em um FutureBuilder ou similar se quiser carregar dados da API na pagina 2

**Comment by Luccasoli** [comment]
Agora funcionou! E valeu pela dica, não conhecia esse widget, realmente do jeito que está ainda ta bem longe do ideal kkk.

Sucesso pra vc com o Get!
