### ISSUE TITLE
get version 1.17.3

### ISSUE THREAD

**Issue by sonnny** [jonataslaw/get#55]
Hi,

     I tried to run your example on the emulator and I get errors below.

Running "flutter pub get" in get_demo...                            0.3s
Launching lib/main.dart on Android SDK built for x86 in debug mode...

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
../../flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install() {
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
../../flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install() {
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.
* Where:
Script '/home/gi/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/gi/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by jonataslaw** [comment]
> Hi,
> 
> ```
>  I tried to run your example on the emulator and I get errors below.
> ```
> 
> Running "flutter pub get" in get_demo... 0.3s
> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> 
> Compiler message:
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
> void install(OverlayEntry insertionPoint) {
> ^
> ../../flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> void install() {
> ^
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
> animation: animation,
> ^^^^^^^^^
> ../../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
> CupertinoFullscreenDialogTransition({
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
> super.install(insertionPoint);
> ^
> 
> Compiler message:
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
> void install(OverlayEntry insertionPoint) {
> ^
> ../../flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> void install() {
> ^
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
> animation: animation,
> ^^^^^^^^^
> ../../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
> CupertinoFullscreenDialogTransition({
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
> super.install(insertionPoint);
> ^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script '/home/gi/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command '/home/gi/flutter/bin/flutter'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 6s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

Please read the documentation and add the version of Get compatible with your Flutter branch.

**Comment by SaifAlrawi** [comment]
Dear how you solve this error I get it in flutter version v1.17.2 channel stable

**Comment by SaifAlrawi** [comment]
Dear how you solve this error ? ? I get it in flutter version v1.17.2 channel stable
@sonnny @jonataslaw

**Comment by jonataslaw** [comment]
> Dear how you solve this error ? ? I get it in flutter version v1.17.2 channel stable
> @sonnny @jonataslaw

use the last version:
get: ^2.10.2

**Comment by SaifAlrawi** [comment]
dear how you solve this ?!, I face it with flutter 1.17.2 on stable channel
@sonnny @jonataslaw

**Comment by SaifAlrawi** [comment]
> > Dear how you solve this error ? ? I get it in flutter version v1.17.2 channel stable
> > @sonnny @jonataslaw
> 
> use the last version:
> get: ^2.10.2

Solved, Thanks dear @jonataslaw appreciated
