### ISSUE TITLE
can't start example app  from pub.dev

### ISSUE THREAD

**Issue by yeras-is** [jonataslaw/get#56]
stack trace 
`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/root/root_widget.dart:82:23: Error: Type 'ActionFactory' not found.
  final Map<LocalKey, ActionFactory> actions;
                      ^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
/C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install() {
       ^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/root/root_widget.dart:82:23: Error: 'ActionFactory' isn't a type.
  final Map<LocalKey, ActionFactory> actions;
                      ^^^^^^^^^^^^^

Compiler message:
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/root/root_widget.dart:82:23: Error: Type 'ActionFactory' not found.
  final Map<LocalKey, ActionFactory> actions;
                      ^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
/C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install() {
       ^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/root/root_widget.dart:82:23: Error: 'ActionFactory' isn't a type.
  final Map<LocalKey, ActionFactory> actions;
                      ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 883

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by jonataslaw** [comment]
> stack trace
> `Launching lib\main.dart on Android SDK built for x86 in debug mode...
> Running Gradle task 'assembleDebug'...
> 
> Compiler message:
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/root/root_widget.dart:82:23: Error: Type 'ActionFactory' not found.
> final Map<LocalKey, ActionFactory> actions;
> ^^^^^^^^^^^^^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
> void install(OverlayEntry insertionPoint) {
> ^
> /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> void install() {
> ^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
> animation: animation,
> ^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
> CupertinoFullscreenDialogTransition({
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
> super.install(insertionPoint);
> ^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/root/root_widget.dart:82:23: Error: 'ActionFactory' isn't a type.
> final Map<LocalKey, ActionFactory> actions;
> ^^^^^^^^^^^^^
> 
> Compiler message:
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/root/root_widget.dart:82:23: Error: Type 'ActionFactory' not found.
> final Map<LocalKey, ActionFactory> actions;
> ^^^^^^^^^^^^^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
> void install(OverlayEntry insertionPoint) {
> ^
> /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
> void install() {
> ^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
> animation: animation,
> ^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
> CupertinoFullscreenDialogTransition({
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
> super.install(insertionPoint);
> ^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-2.0.1/lib/src/root/root_widget.dart:82:23: Error: 'ActionFactory' isn't a type.
> final Map<LocalKey, ActionFactory> actions;
> ^^^^^^^^^^^^^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 883
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 12s
> Exception: Gradle task assembleDebug failed with exit code 1
> `

You are using the Beta/Dev/Master version of Flutter.
Read the documentation, you must use Flutter 2.0.0-dev

**Comment by alirezat66** [comment]
do you solve this problem? If yes, please describe your soloution.

**Comment by jonataslaw** [comment]
> do you solve this problem? If yes, please describe your soloution.

There is no "problem", just update your version of Flutter, it is legacy and you cannot use any updated plugin/packages.
