### ISSUE TITLE
Order changelogs by latest 

### ISSUE THREAD

**Issue by chimon2000** [jonataslaw/get#58]
**Is your feature request related to a problem? Please describe.**
Generally, it's considered a best practice to organize changelogs [latest first](https://keepachangelog.com/en/1.0.0/).  

Most changelogs in pub read most recent first. **get** however, reads in reverse.

This means that if you're subscribing to pub changes via an RSS reader, or just viewing the changes on pub.dev, you will always have to scroll to see the latest version.

**Describe the solution you'd like**
Change the order of the changelog to the most recent first.

**Describe alternatives you've considered**
If you are looking for a great tool for auto-generating changelogs, I cannot recommend https://github.com/git-chglog/git-chglog enough. It offers transparent configuration and has builtin support for common changelog templates.

**Comment by jonataslaw** [comment]
> **Is your feature request related to a problem? Please describe.**
> Generally, it's considered a best practice to organize changelogs [latest first](https://keepachangelog.com/en/1.0.0/).
> 
> Most changelogs in pub read most recent first. **get** however, reads in reverse.
> 
> This means that if you're subscribing to pub changes via an RSS reader, or just viewing the changes on pub.dev, you will always have to scroll to see the latest version.
> 
> **Describe the solution you'd like**
> Change the order of the changelog to the most recent first.
> 
> **Describe alternatives you've considered**
> If you are looking for a great tool for auto-generating changelogs, I cannot recommend https://github.com/git-chglog/git-chglog enough. It offers transparent configuration and has builtin support for common changelog templates.

I was going to do that, but as the package started to be updated practically every 3 days the changelog got really big.
Thanks for the suggestion, and I'll try to rearrange the changelogs when I have time. It is not my case.
If you want to offer a PR, feel free to do so.

**Comment by jonataslaw** [comment]
Updated on pub.dev
