### ISSUE TITLE
Bottom sheet

### ISSUE THREAD

**Issue by Raviteja11122** [jonataslaw/get#6]
Is it shows bottom sheet without context?
If not can you add??

**Comment by jonataslaw** [comment]
> Is it shows bottom sheet without context?
> If not can you add??

BottomSheet works differently on android and IOS, so I will need to recreate the logic of the bottomsheet and cupertinobottomsheet, but I will add this in version 1.7.0, along with the blurred snackbars. I'm already working on the next update.

**Comment by jonataslaw** [comment]
> Is it shows bottom sheet without context?
> If not can you add??

Added on 1.7.3 version

**Comment by Raviteja11122** [comment]
Thanks, buddy. I will use it.
also, update the documentation
GetRoute(settings: settings, builder: (_) => Home(), transition: Transition.fade); In this line there is no builder property it has child property right??
