### ISSUE TITLE
typo in Get.bottomSheet

### ISSUE THREAD

**Issue by jameswasher** [jonataslaw/get#63]
I believe you are missing the line "builder: (_) {"  in the readme for the Get.bottomSheet.  It should be ...

```
Get.bottomSheet(
 builder: (_) {
     Container(
            child: Wrap(
            children: <Widget>[
            ListTile(
            leading: Icon(Icons.music_note),
            title: Text('Music'),
            onTap: () => {}          
          ),
            ListTile(
            leading: Icon(Icons.videocam),
            title: Text('Video'),
            onTap: () => {},          
          ),
            ],
          ),
       );
      }
    );
```

**Comment by jonataslaw** [comment]
Thanks for this issue.
I actually did this update, then I had to do a regression in the dialogs API to keep it compatible with the latest version of Flutter, so Flutter did a regression in his dialogs API, and I didn't update again. I will do that now.

**Comment by jonataslaw** [comment]
Fixed as documentation

**Comment by NiranjanShah** [comment]
The above example is not compiling with error "1 position arguments expected, received 0"
