### ISSUE TITLE
Get breaking in Flutter 1.12.x release

### ISSUE THREAD

**Issue by wgoudsbloem** [jonataslaw/get#64]
The following error happens:

../../Programs/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.3/lib/src/root/root_widget.dart:82:23: Error: 'ActionFactory' isn't a type.
  final Map<LocalKey, ActionFactory> actions;

Looks like the following change is the issue:
https://flutter.dev/docs/release/breaking-changes/actions-api-revision

This is my current version:
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (5 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

**Comment by jonataslaw** [comment]
> The following error happens:
> 
> ../../Programs/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.3/lib/src/root/root_widget.dart:82:23: Error: 'ActionFactory' isn't a type.
> final Map<LocalKey, ActionFactory> actions;
> 
> Looks like the following change is the issue:
> https://flutter.dev/docs/release/breaking-changes/actions-api-revision
> 
> This is my current version:
> Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision f139b11009 (5 weeks ago) • 2020-03-30 13:57:30 -0700
> Engine • revision af51afceb8
> Tools • Dart 2.7.2

This should definitely not happen, in my stable version it works normally, it seems that there is a difference between the version downloaded by sdk releases and that of each branch.
But thanks for opening this issue, I'm going to find a way around this now.

**Comment by jonataslaw** [comment]
> The following error happens:
> 
> ../../Programs/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.3/lib/src/root/root_widget.dart:82:23: Error: 'ActionFactory' isn't a type.
> final Map<LocalKey, ActionFactory> actions;
> 
> Looks like the following change is the issue:
> https://flutter.dev/docs/release/breaking-changes/actions-api-revision
> 
> This is my current version:
> Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision f139b11009 (5 weeks ago) • 2020-03-30 13:57:30 -0700
> Engine • revision af51afceb8
> Tools • Dart 2.7.2

Could you please confirm if on 2.0.4 it's fixed? Please, I don't can reproduce it on my stable version (ActionFactory is present in it).

**Comment by wgoudsbloem** [comment]
Confirmed that it's working on 2.0.4 & 2.0.5, no errors anymore.

Thanks!
