### ISSUE TITLE
Custom Dialog Animation/Curves

### ISSUE THREAD

**Issue by scullabyte** [jonataslaw/get#66]
**Is your feature request related to a problem? Please describe.**
It appears you don't have any options for custom dialog animations. 

**Describe the solution you'd like**
Similar setup to your snackbar, where you can add custom animations. This can be implemented by using `showGeneralDialog` over (current) `showDialog`

**Describe alternatives you've considered**
I can submit a pull-request. If you're not currently working on anything conflicting let me know and I can probably push something up in the next 24 hrs.

**Comment by jonataslaw** [comment]
Hi, really, I hadn't stopped to think about it. showGeneralDialog allows the use of PageRouteBuilder, and much more customization than showDialog.
Great observation.

Well, I'm a little busy for the next 15 hours, if you can offer a PR, I would appreciate it.

Thank's

**Comment by jonataslaw** [comment]
Added Get.generalDialog on 2.0.10

**Comment by scullabyte** [comment]
Awesome man! I'll check it out tonight!!
