### ISSUE TITLE
Error compiling on device

### ISSUE THREAD

**Issue by isadoraoliv** [jonataslaw/get#68]
**Describe the bug**
I'm trying to use the package in my application, but it returns the error when compiling for the device:

Compiler message:
    ../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/snackbar/snack_route.dart:2
    79:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method
    'OverlayRoute.install'.
      void install(OverlayEntry insertionPoint) {
           ^
    ../../../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the
    overridden method ('install').
      void install() {
           ^
    ../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/routes/default_route.dart:2
    42:9: Error: No named parameter with the name 'animation'.
            animation: animation,
            ^^^^^^^^^
    ../../../../../development/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this
    candidate, but the arguments don't match.
      CupertinoFullscreenDialogTransition({
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/snackbar/snack_route.dart:2
    89:18: Error: Too many positional arguments: 0 allowed, but 1 found.
    Try removing the extra positional arguments.
        super.install(insertionPoint);

**Flutter Version:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.4 19E266, locale en-BR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

**Get Version:**
2.0.6

**Describe on which device you found the bug:**
Emulator iPhone 11 Pro Max, but this error takes place in others devices.

**Minimal reproduce code**
I add GetMaterial in my main.dart
return GetMaterialApp( ... );

and use this in other file in my code:

Get.to(
        OtherPage<String>(
          items: listItems(),
          onSelected: addItem,
        ),
        transition: Transition.downToUp,
        duration: Duration(milliseconds: 300));
  }

**Comment by jonataslaw** [comment]
> **Describe the bug**
> I'm trying to use the package in my application, but it returns the error when compiling for the device:
> 
> Compiler message:
> ../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/snackbar/snack_route.dart:2
> 79:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method
> 'OverlayRoute.install'.
> void install(OverlayEntry insertionPoint) {
> ^
> ../../../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the
> overridden method ('install').
> void install() {
> ^
> ../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/routes/default_route.dart:2
> 42:9: Error: No named parameter with the name 'animation'.
> animation: animation,
> ^^^^^^^^^
> ../../../../../development/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this
> candidate, but the arguments don't match.
> CupertinoFullscreenDialogTransition({
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/snackbar/snack_route.dart:2
> 89:18: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
> super.install(insertionPoint);
> 
> **Flutter Version:**
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.4 19E266, locale en-BR)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [✓] Connected device (3 available)
> 
> ! Doctor found issues in 1 category.
> 
> **Get Version:**
> 2.0.6
> 
> **Describe on which device you found the bug:**
> Emulator iPhone 11 Pro Max, but this error takes place in others devices.
> 
> **Minimal reproduce code**
> I add GetMaterial in my main.dart
> return GetMaterialApp( ... );
> 
> and use this in other file in my code:
> 
> Get.to(
> OtherPage(
> items: listItems(),
> onSelected: addItem,
> ),
> transition: Transition.downToUp,
> duration: Duration(milliseconds: 300));
> }

Hi, by your log you are in the beta version of Flutter (v1.17.0-3.2.pre)

On docs:
How to use? #
Flutter Master/Dev/Beta: version 2.0.x-dev

You must use the correct version according to the documentation:
change you pubspec to this:
```
dependencies:
  get: ^2.0.9-dev
```

**Comment by jonataslaw** [comment]
Flutter update to new version. 
Flutter updated to the new version, you can use Get normally now with version 2.0.10
