### ISSUE TITLE
Use Get inside a FutureBuilder

### ISSUE THREAD

**Issue by bobosette** [jonataslaw/get#69]
Hi everybody. I have this issue: I'm using get to display a dialog with a future builder  inside(I want to show a progress indicator till my future is complete). When i have the value I want to call Get.back() (to close the dialog) and Get.to() to open another page but an error comes. I can understand the error but how to handle it?

`
Get.dialog(CustomProgressDialog(
                              needFuture: true,
                              future: FutureBuilder(
                                  future: compute(convertData, onPrefsValue),
                                  builder: (BuildContext context,
                                      AsyncSnapshot<dynamic> snapshot) {
                                    Widget child;
                                    if (snapshot.hasData) {
                                      if (snapshot.data != null) {
                                       
                                        pat = snapshot.data;
                                        
                                       
                                         
                                         Get.back();
                                         Get.to(GraphPage(patData: pat,));
                                        
                                        child = Container();
                                      }
                                    } else if (snapshot.hasError) {
                                      child = Text('error');
                                    } else {
                                      child = Row(
                                        children: <Widget>[
                                          const SizedBox(width: 8.0),
                                          Align(
                                            alignment: Alignment.centerLeft,
                                            child: Padding(
                                              padding: const EdgeInsets.only(bottom: 20),
                                              child:SizedBox(
                                              width: 60.0,
                                              height: 60.0,
                                              child: JumpingDotsProgressIndicator(fontSize: 30,),
                                            )),
                                          ),
                                          Expanded(
                                            child: Text(
                                                    'Charts Data Loading',
                                                    textAlign: TextAlign.left,
                                                    style: const TextStyle(
                                                        color: Colors.black,
                                                        fontSize: 18.0,
                                                        fontWeight:
                                                            FontWeight.w600),
                                                  )
                                          ),
                                          const SizedBox(width: 8.0)
                                        ],
                                      );
                                    }
                                    return child;
                                  }),
                            ));
` 

the error...

`
    state: _FutureBuilderState<PatData>#76a0a
When the exception was thrown, this was the stack
#0      Element.markNeedsBuild.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3896
#1      Element.markNeedsBuild 
package:flutter/…/widgets/framework.dart:3911
#2      State.setState 
package:flutter/…/widgets/framework.dart:1168
#3      _ModalScopeState._routeSetState 
package:flutter/…/widgets/routes.dart:664
#4      ModalRoute.setState 
package:flutter/…/widgets/routes.dart:784
...
The AnimationController notifying status listeners was: AnimationController#dfce6(◀ 1.000; for _DialogRoute<dynamic>)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
setState() or markNeedsBuild() called during build.
The relevant error-causing widget was
    FutureBuilder<PatData> 
lib\widget\drawer.dart:264
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
The getter 'status' was called on null.
Receiver: null
Tried calling: status
The relevant error-causing widget was
    MaterialApp 
lib\main.dart:31
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
The method 'drive' was called on null.
Receiver: null
Tried calling: drive<Offset>(Instance of '_ChainedEvaluation<Offset>')
The relevant error-causing widget was
    MaterialApp 
lib\main.dart:31
═════════════════════════════════
`

Any suggestion?
Thank you

**Comment by jonataslaw** [comment]
This has nothing to do with Get.
You must use SchedulerBinding.instance API to prevent setState from being called during a route or dialog transition.


SchedulerBinding.instance.addPostFrameCallback((_) => Get.dialog());

I have no way of knowing where the error is in your code, because you didn't put a reproducible example here (I don't know for example when Get.dialog is being called).
If you are trying to call Get.dialog directly from the build method, or from initState, you would need to insert Get.dialog into a SchedulerBinding.instance. Otherwise, you have to wrap Get.back() or Get.to() with the SchedulerBinding.instance rather Get.dialog();.
What you have to keep in mind is that the transition animation (of dialog, routes, or anything) cannot be performed during a setState, or during the execution of the build method, and a futureBuilder for example, gives a setState internally in your children. To prevent these behaviors, Flutter uses the SchedulerBinding.instance which listens to the end of setState to call the method.

**Comment by bobosette** [comment]
Thank. I just solve using compute().then() instead of FutureBuilder.

Let me say the Get is incredible. I love it

Il giorno mer 6 mag 2020 alle ore 17:19 Jonny Borges <
notifications@github.com> ha scritto:
