### ISSUE TITLE
Break in new stable channel 1.17.0

### ISSUE THREAD

**Issue by hdeyana** [jonataslaw/get#71]
**Describe the bug**
I try to launch flutter in new stable Chanel

**To Reproduce**
just build
and get error
`
Compiler message:
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
../../../Downloads/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install() {
       ^
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../Downloads/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.6/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);`

**Flutter Version:**
1.17.0

**Get Version:**
2.0.6

**Describe on which device you found the bug:**
ex: Oppo k3 - Android.

**Comment by jonataslaw** [comment]
Wow! Finally version 1.17 became stable, I couldn't take any more workround to listen to dialogs because the previous version didn't even have the RouteSettings property.

I will do the update now, but you can use the version
get: ^2.0.9-dev

Thanks for notifying me!

**Comment by hdeyana** [comment]
Great !! work on 2.0.9-dev

**Comment by hdeyana** [comment]
Solve in 2.0.10
