### ISSUE TITLE
Compiler error message with example (^2.0.10)

### ISSUE THREAD

**Issue by ChickenAhn** [jonataslaw/get#76]
**Describe the bug**
I faced this error whenever trying to implement route with `get`.

**To Reproduce**
1. MaterialApp -> GetMaterialApp -> Error
2. MaterialApp ( ... navigatorKey: Get.key ...) -> Error
3. MaterialApp ( ... namedRoute: { ...GetRoute ... } ) -> Error

Every try did not work for me. 
Thank you and help me some.

**Screenshots**
```

Compiler message:
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/root/root_widget.dart:61:9: Error: Type 'InitialRouteListFactory' not found.
  final InitialRouteListFactory onGenerateInitialRoutes;
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
  void install() {
       ^
../../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/routes/default_route.dart:243:9: Error: No named parameter with the name 'primaryRouteAnimation'.
        primaryRouteAnimation: animation,
        ^^^^^^^^^^^^^^^^^^^^^
../../../../development/flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/get_main.dart:202:7: Error: No named parameter with the name 'routeSettings'.
      routeSettings: RouteSettings(name: 'dialog'),
      ^^^^^^^^^^^^^
../../../../development/flutter/packages/flutter/lib/src/material/dialog.dart:693:11: Context: Found this candidate, but the arguments don't match.
Future<T> showDialog<T>({
          ^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/get_main.dart:230:7: Error: No named parameter with the name 'routeSettings'.
      routeSettings: RouteSettings(name: 'dialog'),
      ^^^^^^^^^^^^^
../../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:1621:11: Context: Found this candidate, but the arguments don't match.
Future<T> showGeneralDialog<T>({
          ^^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/snackbar/snack_route.dart:289:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();
                 ^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/root/root_widget.dart:61:9: Error: 'InitialRouteListFactory' isn't a type.
  final InitialRouteListFactory onGenerateInitialRoutes;
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/root/root_widget.dart:180:7: Error: No named parameter with the name 'onGenerateInitialRoutes'.
      onGenerateInitialRoutes: widget.onGenerateInitialRoutes,
      ^^^^^^^^^^^^^^^^^^^^^^^
../../../../development/flutter/packages/flutter/lib/src/material/app.dart:165:9: Context: Found this candidate, but the arguments don't match.
  const MaterialApp({
        ^^^^^^^^^^^
```

**Flutter Version:**
1.12.13+hotfix.9

**Get Version:**
^2.0.10

**Describe on which device you found the bug:**
ex: Moto z2 - Android.

**Minimal reproduce code**
Provide a minimum reproduction code for the problem

**Comment by jonataslaw** [comment]
> **Describe the bug**
> I faced this error whenever trying to implement route with `get`.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. MaterialApp -> GetMaterialApp -> Error
> 2. MaterialApp ( ... navigatorKey: Get.key ...) -> Error
> 3. MaterialApp ( ... namedRoute: { ...GetRoute ... } ) -> Error
> 
> Every try did not work for me.
> Thank you and help me some.
> 
> **Screenshots**
> 
> ```
> 
> Compiler message:
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/root/root_widget.dart:61:9: Error: Type 'InitialRouteListFactory' not found.
>   final InitialRouteListFactory onGenerateInitialRoutes;
>         ^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
>   void install() {
>        ^
> ../../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
>   void install(OverlayEntry insertionPoint) {
>        ^
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/routes/default_route.dart:243:9: Error: No named parameter with the name 'primaryRouteAnimation'.
>         primaryRouteAnimation: animation,
>         ^^^^^^^^^^^^^^^^^^^^^
> ../../../../development/flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match.
>   CupertinoFullscreenDialogTransition({
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/get_main.dart:202:7: Error: No named parameter with the name 'routeSettings'.
>       routeSettings: RouteSettings(name: 'dialog'),
>       ^^^^^^^^^^^^^
> ../../../../development/flutter/packages/flutter/lib/src/material/dialog.dart:693:11: Context: Found this candidate, but the arguments don't match.
> Future<T> showDialog<T>({
>           ^^^^^^^^^^
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/get_main.dart:230:7: Error: No named parameter with the name 'routeSettings'.
>       routeSettings: RouteSettings(name: 'dialog'),
>       ^^^^^^^^^^^^^
> ../../../../development/flutter/packages/flutter/lib/src/widgets/routes.dart:1621:11: Context: Found this candidate, but the arguments don't match.
> Future<T> showGeneralDialog<T>({
>           ^^^^^^^^^^^^^^^^^
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/snackbar/snack_route.dart:289:18: Error: Too few positional arguments: 1 required, 0 given.
>     super.install();
>                  ^
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/root/root_widget.dart:61:9: Error: 'InitialRouteListFactory' isn't a type.
>   final InitialRouteListFactory onGenerateInitialRoutes;
>         ^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/get-2.0.10/lib/src/root/root_widget.dart:180:7: Error: No named parameter with the name 'onGenerateInitialRoutes'.
>       onGenerateInitialRoutes: widget.onGenerateInitialRoutes,
>       ^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../development/flutter/packages/flutter/lib/src/material/app.dart:165:9: Context: Found this candidate, but the arguments don't match.
>   const MaterialApp({
>         ^^^^^^^^^^^
> ```
> 
> **Flutter Version:**
> 1.12.13+hotfix.9
> 
> **Get Version:**
> ^2.0.10
> 
> **Describe on which device you found the bug:**
> ex: Moto z2 - Android.
> 
> **Minimal reproduce code**
> Provide a minimum reproduction code for the problem

Hi, you are using a legacy version of Flutter.
Use version (2.0.6) of Get instead of (2.0.10), it is the latest version compatible with legacy Flutter 1.12

**Comment by ChickenAhn** [comment]
Thank you! I'll try that version with my flutter.
I finally can taste `get` for now!
