### ISSUE TITLE
Hiding Snackbar

### ISSUE THREAD

**Issue by mithilesh-parmar** [jonataslaw/get#78]
**Describe the bug**

If there's a snackbar displaying then we cannot go back to previous screen till snackbar is completed displaying.
I couldn't find a way to hide the visible snackbar. We have a way to check if the snackBar is visible or not. 

**Flutter Version:**
Flutter 1.12.13+hotfix.9 • channel stable 

**Get Version:**
get: ^2.0.3

**Describe on which device you found the bug:**
iOS 13.4 Simulator iPhone XS Max

**Comment by jonataslaw** [comment]
This is not a mistake. Get allows you to close dialogs, bottomsheet, and snackbars dynamically.
If you want to close all overlays to return, you must use:
Get.back(closeOverlays: true);
