### ISSUE TITLE
How to get rid of default route '/'

### ISSUE THREAD

**Issue by j33tmane** [jonataslaw/get#80]
if my initial route is '/login' 

Route stack is created like
'/login'
'/'

after app start it opens login screen but when i click back it goes to blank screen coz i haven't specified
default route page.
Is there any way to not use that route or disable it?

**Comment by jonataslaw** [comment]
> if my initial route is '/login'
> 
> Route stack is created like
> '/login'
> '/'
> 
> after app start it opens login screen but when i click back it goes to blank screen coz i haven't specified
> default route page.
> Is there any way to not use that route or disable it?

If you use the traditional Flutter MaterialApp and add GetObserver to navigatorsObserver to obtain navigation logs you will see that the same behavior happens. Flutter forces you to use Initial Route '/', if you enter another one, it automatically redirects to '/', I don't like that either. But this is configured in the Flutter Engine, I would have to create a Flutter 2.0 and not just a plugin to solve this.
You can open an issue on Flutter about this if it bothers you, everything is ok on our side.
