### ISSUE TITLE
Method not found: 'GetRoute'.

### ISSUE THREAD

**Issue by mjliang** [jonataslaw/get#81]
**Describe the bug**

Compiler message:
lib/constants/routes.dart:5:34: Error: Method not found: 'GetRoute'.
  static get routes => {"/": new GetRoute(page: MainScreen())};

**To Reproduce**
Steps to reproduce the behaviour:
The `GetRoute` class can not be found event I import the `package:get/get.dart`

**Expected behaviour**
The `GetRoute` class should be found when I import the `package:get/get.dart`

**Screenshots**
![image](https://user-images.githubusercontent.com/435010/81490409-3ea6d900-92d6-11ea-871b-2fb74516b8ab.png)

**Flutter Version:**
1.17.0

**Get Version:**
2.2.1

**Describe on which device you found the bug:**
compilation issue 

**Minimal reproduce code**

**Comment by jonataslaw** [comment]
Wow, I was changing this file and I ended up sending an update before saving the export.
Fixed on 2.2.2

**Comment by stefandevo** [comment]
just wondering ... I don't see any commits anymore since 2.0.0 ... any reason?
