### ISSUE TITLE
Navigation using Get

### ISSUE THREAD

**Issue by NiranjanShah** [jonataslaw/get#82]
Will using GET for navigation support the below condition (Permanent Bottom Navigation Bar / Multiple Navigator with bottom bar).

Say the app has 3 bottom bar items , each bar items has a page which further can be navigated into the sub pages, and now when back is pressed, it must close the sub page of the item bar page.

Hope , my query is clear for understanding.

PS: I am looking out to achieve the solution as described on this url

https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf

**Comment by jonataslaw** [comment]
Read the documentation, there's a page on NestedNavigators there.
to each Navigator widget: 
nestedKey(1)
to navigate:
navigator.push(Page(), 1)
