### ISSUE TITLE
fullscreenDialog flag

### ISSUE THREAD

**Issue by RodBr** [jonataslaw/get#87]
Is there a way to use the `fullscreenDialog: true`  flag when using `Get.to`?

**Comment by jonataslaw** [comment]
Get.to(Page(), fullscreenDialog: true) // version 2.3 +

**Comment by RodBr** [comment]
Thanks, that should have been obvious to me.

Brilliant package BTW!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
