### ISSUE TITLE
Nested routes error

### ISSUE THREAD

**Issue by c1zone1** [jonataslaw/get#89]
Hi, i was trying to implement the nested routes on my project. 
As explained [here](https://github.com/jonataslaw/get#nested-navigators)

but i'm getting this error:

```
The return type 'GetRoute' isn't a 'Route<dynamic>', as required by the closure's context.
```
on 

```
return GetRoute(/*....*/);
```

Yeah i'm using `onGenerateRoute` if you want to know.

Or there are some way to obtain 2 navigator (without another ```GetMaterialApp```)? So i can manage this thing differently

**Comment by jonataslaw** [comment]
Use GetRouteBase rather GetRoute. 
I fixed this typo in the documentation.

**Comment by c1zone1** [comment]
Hi, im opening  this issue again because i found another error:

```
Get.toNamed("/nested/abc",id:1)
```

error:

```
The method 'pushNamed' was called on null.
Receiver: null
Tried calling: pushNamed<dynamic>("/nested/abc", arguments: null)
```

OR

```
Get.toNamed("/nested/abc",1)
```

error:

```
Too many positional arguments: 1 expected, but 2 found.
```

**Comment by c1zone1** [comment]
@jonataslaw

**Comment by jonataslaw** [comment]
You add nestedKey(1) to your Navigator widget?

**Comment by c1zone1** [comment]
Yeah i added 
```
Navigator(
     key: Get.nestedKey(1),
    ...
```

**Comment by c1zone1** [comment]
I found a workaround

```
Get.global(1).currentState.pushNamed("/second")
```

I'm trying to understand why with 

```
Get.toNamed("/nested/abc", id: 1);
```

don't work

**Comment by c1zone1** [comment]
Okay now works, but if i have 2 Navigator i can't go from the first navigator to the second... No error provided
