### ISSUE TITLE
Update readme with stream example

### ISSUE THREAD

**Issue by FireJuun** [jonataslaw/get#91]
**Is your feature request related to a problem? Please describe.**
The current readme states GetController can be used to harness streams, albeit with care. It also mentions the `dispose:` property which can call events when the widget is destroyed

**Describe the solution you'd like**
I would like the readme to include very simple example showing:
-how to properly create a stream in the Controller
-how to properly access the stream inside the GetBuilder tree
-how to properly dispose the stream

Using Firebase as an example, within the Controller, would one call: 
```dart
Stream<DocumentSnapshot> get fbStream => Firestore.instance.collection('collection').document('document').snapshots();
```

Then, within the UI, is this the proper call?
```dart
...
GetBuilder<Controller>(
        init: Controller(),
        //dispose: ____
        builder: (controller) => StreamBuilder(
          stream: controller.fbStream,
          builder: (context, snapshot) {
            if (!snapshot.hasData) {
              return CircularProgressIndicator();
            }

            // find the field named 'field', return this
            Map<String, dynamic> documentFields = snapshot.data.data;
            return Text(documentFields['field'], textAlign: TextAlign.center);
          },
        ),
      ),
```

**Describe alternatives you've considered**
Is the suggested method to create a StreamBuilder widget within the GetBuilder widget, passing forward `controller.fbStream`, or is there a better/more streamlined way? How should we access `dispose:`?

I agree that streams should be used sparingly and purposefully. That said, I'd love to harness Get so that it is harnessed properly

**Comment by jonataslaw** [comment]
Hi, thanks for mentioning this.
fbstream should always be on your controller. If you need to dispose, you can call initstate and even dispose of GetBuilder (there are these properties there).
However, I see that this approach of embedding StreamBuilder within a GetBuilder can delay development somewhat, so I am creating a new widget for reactive programming that will allow updating without having to embed a streambuilder within GetBuilder.
I still don't know if I'm going to release it as an optional package, Getx, which will be get turned to reactive programming with rxDart, or if the additional code doesn't get too big, I'll include it within Get myself (I'm trying to use rx, without the rx library to cut the size to the maximum, if you can't, it will be a separate package).

ListView.builder will also get a new widget where you just need to insert the list, and it will configure everything. When arriving at the last widget, the user can define a method for lazyloading, and that is very, very cool. However, before launching any feature, I have to create tests and more tests to see if there will be any side effects.
I'm trying to reconcile this with a feature request for a large case that uses Get and wants to maintain the project, and soon Get will be even better and more facilitator than it is today, practically indispensable for anyone who wants to program with productivity.

And by the way, a safe approach is to create a "close" method in your Controller class where you will close all your streams, and within GetBuilder's available method, you can call controller.close ();

However, I will work to change that, after all, the goal of this package is productivity.

**Comment by cartafelipe** [comment]
É dessa forma como descreveu acima, que se usa stream com RxController, criando get? To apanhando com bad state. Já tentei broadcast, não dá erro mas não aparece nada.
