### ISSUE TITLE
Snackbar is partially cut off on iPhone SE

### ISSUE THREAD

**Issue by volgin** [jonataslaw/get#92]
The following screenshots are created using the same code. It appears that Get assumes the wrong bottom margin for iPhone SE. I don't know if that's Get or Flutter not recognizing SafeArea correctly. I am on Flutter 1.17.0 • channel beta.

```
Get.snackbar(
    "",
    "",
    messageText: Text(
      _message,
      style: TextStyle(color: Colors.white, fontSize: 16.0),
    ),
    backgroundColor: _error ? Colors.red : Color.fromRGBO(51, 101, 189, 1.0),
    borderRadius: 0.0,
    duration: Duration(seconds: _error ? 9 : 3),
    margin: EdgeInsets.zero,
    padding: EdgeInsets.symmetric(vertical: 8.0, horizontal: 24.0),
    isDismissible: true,
    snackPosition: SnackPosition.BOTTOM,
    snackStyle: SnackStyle.GROUNDED,
);
```

![Simulator-Screen-Shot---iPhone-11-Pro---2020-05-12-at-16 24 22](https://user-images.githubusercontent.com/297748/81742680-82cce180-946e-11ea-90e1-e9ed3226bedb.png)
![Simulator-Screen-Shot---iPhone-SE-(2nd-generation)---2020-05-12-at-16 23 26](https://user-images.githubusercontent.com/297748/81742682-82cce180-946e-11ea-82c9-827b0e9df571.png)

**Comment by jonataslaw** [comment]
We use SafeArea to display the snackbar correctly:
https://github.com/jonataslaw/get/blob/master/lib/src/snackbar/snack.dart#L375

Is this the iPhone SE 1 or 2?
If it's 2, I think it's still new and the Flutter team hasn't had time to insert it into the engine yet. If it's the old one, we have a problem.

**Comment by Ahmadre** [comment]
@jonataslaw You're calculating it wrong.

Line 378 + 379: Not `MediaQuery.of(context).viewInsets.bottom`. You've to use: `MediaQuery.of(context).padding.bottom` instead, because the Framework is using that for calculating the correct padding.

**Comment by jonataslaw** [comment]
> @jonataslaw You're calculating it wrong.
> 
> Line 378 + 379: Not `MediaQuery.of(context).viewInsets.bottom`. You've to use: `MediaQuery.of(context).padding.bottom` instead, because the Framework is using that for calculating the correct padding.

The iPhone SE does not have any part obscured by the system. This was not to be the behavior expected by viewInsets, but as the padding is built on the viewInsets limits, your solution should work, thanks for that!

**Comment by jonataslaw** [comment]
Try 2.5.3 version

**Comment by Ahmadre** [comment]
> > @jonataslaw You're calculating it wrong.
> > 
> > Line 378 + 379: Not `MediaQuery.of(context).viewInsets.bottom`. You've to use: `MediaQuery.of(context).padding.bottom` instead, because the Framework is using that for calculating the correct padding.
> 
> The iPhone SE does not have any part obscured by the system. This was not to be the behavior expected by viewInsets, but as the padding is built on the viewInsets limits, your solution should work, thanks for that!

be welcome 😊

**Comment by antonioag95** [comment]
Unfortunately the issue is still reproducible

**Comment by ghenry** [comment]
Can SafeArea() help with this?
