### ISSUE TITLE
What is the convention of using a GetController with a StreamController/Stream?

### ISSUE THREAD

**Issue by MichaelOttink** [jonataslaw/get#94]
I have the following controller

```
class GetStreamController<T> extends GetController
{
  StreamController<T> _streamController = BehaviorSubject();
  Stream<T> get stream => _streamController.stream;

  GetStreamController({Stream<T> stream})
  {
    _streamController.addStream(stream);
  }

  @override
  void close() {
    super.close();
    closeStream();
    print('stream closed');
  }

  Future<void> closeStream() async {
    await stream.drain();
    _streamController.close();
  }
}
```

I use a GetBuilder to supply my app with a stream in the following way.

```
GetBuilder<GetStreamController<GroupModel>>(
        init: GetStreamController<GroupModel>(stream: database.groupStream(_group)),
        builder: (GetStreamController<GroupModel> groupController) => StreamBuilder(
          stream: groupController.stream,
```

Then in a child widget I use the Builder without a init to get the stream once more

```
GetBuilder<GetStreamController<GroupModel>>(
        builder: (GetStreamController<GroupModel> groupController) => StreamBuilder(
          stream: groupController.stream,
```
But how do I dispose of this stream. Because if the second widget get's removed from the widget tree the close method get's called and it tries to close the stream which is not what I want. 

**Desired behavior**
The desired behaviour is that only when the root builder get's removed from the widget tree, the stream get's closed.

**Flutter Version:**
1.17.0

**Get Version:**
  get: ^2.3.1

**Comment by jonataslaw** [comment]
> I have the following controller
> 
> ```
> class GetStreamController<T> extends GetController
> {
>   StreamController<T> _streamController = BehaviorSubject();
>   Stream<T> get stream => _streamController.stream;
> 
>   GetStreamController({Stream<T> stream})
>   {
>     _streamController.addStream(stream);
>   }
> 
>   @override
>   void close() {
>     super.close();
>     closeStream();
>     print('stream closed');
>   }
> 
>   Future<void> closeStream() async {
>     await stream.drain();
>     _streamController.close();
>   }
> }
> ```
> 
> I use a GetBuilder to supply my app with a stream in the following way.
> 
> ```
> GetBuilder<GetStreamController<GroupModel>>(
>         init: GetStreamController<GroupModel>(stream: database.groupStream(_group)),
>         builder: (GetStreamController<GroupModel> groupController) => StreamBuilder(
>           stream: groupController.stream,
> ```
> 
> Then in a child widget I use the Builder without a init to get the stream once more
> 
> ```
> GetBuilder<GetStreamController<GroupModel>>(
>         builder: (GetStreamController<GroupModel> groupController) => StreamBuilder(
>           stream: groupController.stream,
> ```
> 
> But how do I dispose of this stream. Because if the second widget get's removed from the widget tree the close method get's called and it tries to close the stream which is not what I want.
> 
> **Desired behavior**
> The desired behaviour is that only when the root builder get's removed from the widget tree, the stream get's closed.
> 
> **Flutter Version:**
> 1.17.0
> 
> **Get Version:**
> get: ^2.3.1


Thank you very much for opening this issue. For a typo, Get was closing streams without the root GetBuilder being discarded. This has been fixed in the latest version.
The tests did not include this possibility, and its use case helped us to fix a bug and make the internal tests even more secure.
