### ISSUE TITLE
How to kill all dialogs open?

### ISSUE THREAD

**Issue by luissouza** [jonataslaw/get#95]
Hello,
I have this dialog opened and I want to close then without having to click on onConfirm or onClose, is there a way?

**Get.defaultDialog(
              onConfirm: () => print("Ok"),
              middleText: "Dialog made in 3 lines of code");**

**Comment by jonataslaw** [comment]
Pode falar em portugues mesmo, não entendi sua dúvida

**Comment by luissouza** [comment]
Opa, rsrs.
Cara, tem como matar todas dialogs em aberta sem eu ter que clicar no botāo para confirmar ou cancelar? Eu precisava muito de uma funcão que fizesse isso, tipo Get.closeAllDialogs();

**Comment by jonataslaw** [comment]
Não testei, mas eu suponho que isso deve resolver seu problema:
 
Get.until((route) {
      return Get.isDialogOpen;
  });

**Comment by luissouza** [comment]
@jonataslaw Testei aqui e aparentemente deu certo sim!! Muito obrigado pela ajuda.

**Comment by luissouza** [comment]
@jonataslaw , testei aqui, infelizmente nāo funcionou, o que estou tentando é fechar um dialog antes de abrir outro, e isso nāo resolveu :/

**Comment by jonataslaw** [comment]
Pra fechar um dialog se tiver aberto, você pode usar a mesma API pra isso:
if(Get.isDialogOpen){
Get.back();
}
Get.dialog();

**Comment by jonataslaw** [comment]
Foram fornecidos dois exemplos de fechamento de dialogs antes de chamar um outro, dessa forma, estou fechando essa questão.

**Comment by luissouza** [comment]
@jonataslaw desculpe pela demora, eu certo as duas soluçōes. Muito obrigado!!!
