### ISSUE TITLE
FocusScope with no context?

### ISSUE THREAD

**Issue by blinkn** [jonataslaw/get#96]
Hi, in docs you mention that if I need to use an Stateful widget, probably I am using Get wrong.
Is there a way/alternative to call `FocusScope.of(context).requestFocus()` without context?

This piece of code is inside another method outside `build` standard method. in stateful widgets, the context is shared to the entire widget class, but in stateless, I need to pass through parameters the context from standard `build` method to my custom methods to get the context.

Any tips or is this expected?

**Comment by jonataslaw** [comment]
I particularly use focusNode on my controller and attach it to the TextField, this gives me more control over when to open or close the focus, and allows me to close the keyboard for example, when the user has sent a message. I didn't quite understand how your approach works. Could you give me an example code?

**Comment by blinkn** [comment]
Nevermind, I managed to get it working by passing context to my method and it works well, maybe not as beautiful as if it doesn't require that but it's ok. Closing issue. Thank you.
