### ISSUE TITLE
Wrong transition animation in iOS

### ISSUE THREAD

**Issue by WingCH** [jonataslaw/get#98]
In example, i just change `/details` transition 

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_state/home/views/country_view.dart';
import 'home/views/details_view.dart';
import 'home/views/home_view.dart';

void main() {
  runApp(GetMaterialApp(
    debugShowCheckedModeBanner: false,
    initialRoute: '/',
    namedRoutes: {
      '/': GetRoute(page: HomePage()),
      '/country': GetRoute(page: CountryPage()),
      '/details': GetRoute(
        page: DetailsPage(),
        transition: Transition.scale, // changed
      ),
    },
  ));
}
```

Demo

![2020-05-14 13 40 59](https://user-images.githubusercontent.com/19588517/81897508-5c7f8100-95e9-11ea-9407-528efdf37a43.gif)

In iOS,  `/country` to `/details`  screen will move from left to right.

Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (29 hours ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2

**Comment by jonataslaw** [comment]
Watching the video I could see that the transition works correctly. The scale animation is being displayed (moving from the upper right to the left). If you want to hide the animation of the bottom page being slid, you can use: opaque = true.

**Comment by WingCH** [comment]
i tried add ` opaque = true`, but still have black bar when `/country` to `/details` screen will move from left to right.
![image](https://user-images.githubusercontent.com/19588517/82000355-a8363700-968a-11ea-897f-af5256b72af7.png)

**Comment by jonataslaw** [comment]
Did you remove the Scaffold transparency? Why it is necessary to remove:
// backgroundColor: Colors.transparent
If you don't want to see a black background.

**Comment by WingCH** [comment]
no, I do not have remove the Scaffold transparency.
I just  change /details transition in your example.

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_state/home/views/country_view.dart';
import 'home/views/details_view.dart';
import 'home/views/home_view.dart';

void main() {
  runApp(GetMaterialApp(
    debugShowCheckedModeBanner: false,
    initialRoute: '/',
    namedRoutes: {
      '/': GetRoute(page: HomePage()),
      '/country': GetRoute(page: CountryPage()),
      '/details': GetRoute(
        page: DetailsPage(),
        transition: Transition.scale, // changed
      ),
    },
  ));
}
```

**Comment by WingCH** [comment]
This situation will only happen on iOS, android everything is normal

**Comment by WingCH** [comment]
android everything is normal
![2020-05-15 11 57 06](https://user-images.githubusercontent.com/19588517/82010027-7bdae480-96a3-11ea-9ccc-081b50bb77e7.gif)

**Comment by jonataslaw** [comment]
Try this:

'/country': GetRoute(page: CountryPage(),  transition: Transition.fade),
      '/details': GetRoute(
        page: DetailsPage(),
        transition: Transition.scale,

I think this is peculiar to the Cupertino route,

The cupertino transition (default) cannot be changed, it has many peculiarities, so we simply use the native Flutter transition. On iOS, if no transition is defined, the default transition will be displayed (cupertino). We have no control over cupertino animations, and by its description, there is a 99.9999% chance of being an issue with the native iOS transition. If you set a transition to fade, it will change the default transition, and probably solve the problem.

**Comment by WingCH** [comment]
Thanks for your quick help!

![2020-05-15 15 10 51](https://user-images.githubusercontent.com/19588517/82021919-54dddc00-96be-11ea-9057-b31185dd661c.gif)
